// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Body of `POST /api/master-data/{entity}/import/preview` (from the backend validation rules). */
export type PostMasterDataEntityImportPreviewBody = {
  branch_id?: number;
  rows: unknown[] | Record<string, unknown>;
};

/** Response of `POST /api/master-data/{entity}/import/preview` (no capture: keys from backend code only). */
export type PostMasterDataEntityImportPreviewResponse = {
  branch_id?: unknown;
  rows?: unknown;
};

/** Body of `POST /api/master-data/{entity}/import` (from the backend validation rules). */
export type PostMasterDataEntityImportBody = {
  branch_id?: number;
  rows: unknown[] | Record<string, unknown>;
};

/** Response of `POST /api/master-data/{entity}/import` (no capture: keys from backend code only). */
export type PostMasterDataEntityImportResponse = {
  branch_id?: unknown;
  message?: unknown;
  rows?: unknown;
};

/** Body of `POST /api/attachments` (from the backend validation rules). */
export type PostAttachmentsBody = {
  attachable_id: number;
  attachable_type: string;
  captured_at?: string;
  file: string;
  latitude?: string | number;
  longitude?: string | number;
  type: string;
};

/** Response of `POST /api/attachments` (no capture: keys from backend code only). */
export type PostAttachmentsResponse = {
  captured_at?: unknown;
  download_url?: unknown;
  file_size?: unknown;
  id?: unknown;
  latitude?: unknown;
  longitude?: unknown;
  message?: unknown;
  mime_type?: unknown;
  name?: unknown;
  original_name?: unknown;
  type?: unknown;
  uploaded_at?: unknown;
  uploaded_by?: unknown;
};

/** Response of `GET /api/attachments/{attachment}/download` (no capture: keys from backend code only). */
export type GetAttachmentsAttachmentDownloadResponse = Record<string, unknown>;
