// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Body of `POST /api/login` (from the backend validation rules). */
export type PostLoginBody = {
  device_name: string;
  email: string;
  password: string;
};

/** Response of `POST /api/login` (no capture: keys from backend code only). */
export type PostLoginResponse = {
  email?: unknown;
  employee?: unknown;
  expires_at?: unknown;
  id?: unknown;
  message?: unknown;
  name?: unknown;
  permissions?: unknown;
  roles?: unknown;
  token?: unknown;
  user?: unknown;
};

/** Response of `GET /api/me` (from live captures). */
export type GetMeResponse = {
  success: boolean;
  user: {
    id: number;
    name: string;
    email: string;
    employee: {
      id: number;
      employee_code: string;
      name: string;
      phone: string | null;
      job_title: string;
      position_code: string;
      is_active: boolean;
      branch_id: number;
      branch: {
        id: number;
        code: string;
        name: string;
        city: string;
        is_active: boolean;
      };
    };
    roles: string[];
    permissions: string[];
  };
};

/** Response of `POST /api/logout` (no capture: keys from backend code only). */
export type PostLogoutResponse = {
  message?: unknown;
};
