// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/warehouses` (from the backend validation rules). */
export type GetWarehousesQuery = {
  branch_id?: number;
  is_active?: boolean;
};

/** Response of `GET /api/warehouses` (from live captures). */
export type GetWarehousesResponse = {
  success: boolean;
  summary: {
    count: number;
  };
  data: {
    id: number;
    code: string;
    name: string;
    address: null;
    is_active: boolean;
    branch_id: number;
    branch: string;
  }[];
};

/** Query of `GET /api/branches` (from the backend validation rules). */
export type GetBranchesQuery = {
  is_active?: boolean;
};

/** Response of `GET /api/branches` (from live captures). */
export type GetBranchesResponse = {
  success: boolean;
  data: {
    id: number;
    code: string;
    name: string;
    city: string;
    phone: null;
    address: null;
    is_active: boolean;
  }[];
};

/** Response of `GET /api/branches/{branch}` (from live captures). */
export type GetBranchesBranchResponse = {
  success: boolean;
  data: {
    id: number;
    code: string;
    name: string;
    city: string;
    phone: null;
    address: null;
    is_active: boolean;
    warehouses: {
      id: number;
      code: string;
      name: string;
      is_active: boolean;
    }[];
  };
};

/** Query of `GET /api/employees` (from the backend validation rules). */
export type GetEmployeesQuery = {
  is_active?: boolean;
  position_code?: string;
  q?: string;
};

/** Response of `GET /api/employees` (from live captures). */
export type GetEmployeesResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    employee_code: string;
    name: string;
    phone: string | null;
    job_title: string;
    position_code: string;
    hire_date: string;
    is_active: boolean;
    has_login: boolean;
    email: string;
    q?: unknown;
  }[];
};

/** Response of `GET /api/employees/{employee}` (from live captures). */
export type GetEmployeesEmployeeResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    employee_code: string;
    name: string;
    phone: null;
    job_title: string;
    position_code: string;
    hire_date: string;
    is_active: boolean;
    has_login: boolean;
    email: string;
    manager: null;
    subordinates: unknown[];
  };
};

/** Body of `POST /api/employees` (from the backend validation rules). */
export type PostEmployeesBody = {
  branch_id?: number;
  employee_code: string;
  hire_date?: string;
  is_active?: boolean;
  job_title: string;
  name: string;
  phone?: string;
  position_code: string;
};

/** Response of `POST /api/employees` (no capture: keys from backend code only). */
export type PostEmployeesResponse = {
  branch_id?: unknown;
  email?: unknown;
  employee_code?: unknown;
  has_login?: unknown;
  hire_date?: unknown;
  id?: unknown;
  is_active?: unknown;
  job_title?: unknown;
  message?: unknown;
  name?: unknown;
  phone?: unknown;
  position_code?: unknown;
};

/** Body of `PATCH /api/employees/{employee}` (from the backend validation rules). */
export type PatchEmployeesEmployeeBody = {
  branch_id?: number;
  employee_code?: string;
  hire_date?: string;
  is_active?: boolean;
  job_title?: string;
  name?: string;
  phone?: string;
  position_code?: string;
};

/** Response of `PATCH /api/employees/{employee}` (no capture: keys from backend code only). */
export type PatchEmployeesEmployeeResponse = {
  branch_id?: unknown;
  email?: unknown;
  employee_code?: unknown;
  has_login?: unknown;
  hire_date?: unknown;
  id?: unknown;
  is_active?: unknown;
  job_title?: unknown;
  message?: unknown;
  name?: unknown;
  phone?: unknown;
  position_code?: unknown;
};

/** Response of `GET /api/employees/{employee}/hierarchy` (from live captures). */
export type GetEmployeesEmployeeHierarchyResponse = {
  success: boolean;
  data: {
    employee: {
      id: number;
      employee_code: string;
      name: string;
      position_code: string;
    };
    manager: null;
    subordinates: unknown[];
  };
};

/** Body of `POST /api/employees/{employee}/hierarchy` (from the backend validation rules). */
export type PostEmployeesEmployeeHierarchyBody = {
  manager_id: number;
  start_date?: string;
};

/** Response of `POST /api/employees/{employee}/hierarchy` (no capture: keys from backend code only). */
export type PostEmployeesEmployeeHierarchyResponse = {
  id?: unknown;
  is_active?: unknown;
  manager_id?: unknown;
  message?: unknown;
  start_date?: unknown;
  subordinate_id?: unknown;
};

/** Body of `POST /api/employees/{employee}/hierarchy/end` (from the backend validation rules). */
export type PostEmployeesEmployeeHierarchyEndBody = {
  end_date?: string;
};

/** Response of `POST /api/employees/{employee}/hierarchy/end` (no capture: keys from backend code only). */
export type PostEmployeesEmployeeHierarchyEndResponse = {
  end_date?: unknown;
  id?: unknown;
  is_active?: unknown;
  manager_id?: unknown;
  message?: unknown;
  subordinate_id?: unknown;
};

/** Response of `GET /api/users` (from live captures). */
export type GetUsersResponse = {
  success: boolean;
  data: {
    id: number;
    employee_id: number;
    employee: string;
    branch_id: number;
    name: string;
    email: string;
    roles: string[];
  }[];
};

/** Response of `GET /api/roles` (from live captures). */
export type GetRolesResponse = {
  success: boolean;
  data: string[];
};

/** Body of `POST /api/employees/{employee}/login` (from the backend validation rules). */
export type PostEmployeesEmployeeLoginBody = {
  email: string;
  name?: string;
  password: string;
  roles?: unknown[] | Record<string, unknown>;
};

/** Response of `POST /api/employees/{employee}/login` (no capture: keys from backend code only). */
export type PostEmployeesEmployeeLoginResponse = {
  branch_id?: unknown;
  email?: unknown;
  employee?: unknown;
  employee_id?: unknown;
  id?: unknown;
  message?: unknown;
  name?: unknown;
  password?: unknown;
  roles?: unknown;
};

/** Body of `PATCH /api/users/{user}` (from the backend validation rules). */
export type PatchUsersUserBody = {
  email?: string;
  name?: string;
  password?: string;
  roles?: unknown[] | Record<string, unknown>;
};

/** Response of `PATCH /api/users/{user}` (no capture: keys from backend code only). */
export type PatchUsersUserResponse = {
  branch_id?: unknown;
  email?: unknown;
  employee?: unknown;
  employee_id?: unknown;
  id?: unknown;
  message?: unknown;
  name?: unknown;
  password?: unknown;
  roles?: unknown;
};

/** Body of `PUT /api/users/{user}/roles` (from the backend validation rules). */
export type PutUsersUserRolesBody = {
  roles?: unknown[] | Record<string, unknown>;
};

/** Response of `PUT /api/users/{user}/roles` (from live captures). */
export type PutUsersUserRolesResponse = {
  success: boolean;
  message: string;
  data: {
    id: number;
    employee_id: number;
    employee: string;
    branch_id: number;
    name: string;
    email: string;
    roles: unknown[];
  };
};
