// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Body of `POST /api/collections` (from the backend validation rules). */
export type PostCollectionsBody = {
  allocations: {
    amount: string | number;
    receivable_id: number;
  }[];
  cheque_bank?: string;
  cheque_due_date?: string;
  cheque_no?: string;
  customer_visit_id: number;
  notes?: string;
  payment_method?: string;
  transfer_reference?: string;
};

/** Response of `POST /api/collections` (no capture: keys from backend code only). */
export type PostCollectionsResponse = {
  message?: unknown;
};

/** Query of `GET /api/collections` (from the backend validation rules). */
export type GetCollectionsQuery = {
  clearance_status?: string;
  customer_id?: number;
  daily_session_id?: number;
  from?: string;
  page?: string;
  payment_method?: string;
  per_page?: string;
  salesman_id?: number;
  to?: string;
};

/** Response of `GET /api/collections` (from live captures). */
export type GetCollectionsResponse = {
  success: boolean;
  data: {
    id: number;
    collection_no: string;
    branch_id: number;
    daily_session_id: number;
    customer: {
      id: number;
      customer_code: string;
      name: string;
    };
    salesman: {
      id: number;
      name: string;
    };
    amount: string;
    payment_method: string;
    clearance_status: string;
    cheque_no: string | null;
    cheque_due_date: string | null;
    transfer_reference: null;
    collected_at: string;
    customer_id?: unknown;
    salesman_id?: unknown;
  }[];
  meta: {
    total: number;
    per_page: number;
    current_page: number;
    last_page: number;
  };
};

/** Response of `GET /api/collections/{collection}` (from live captures). */
export type GetCollectionsCollectionResponse = {
  success: boolean;
  data: {
    id: number;
    collection_no: string;
    branch_id: number;
    daily_session_id: number;
    customer: {
      id: number;
      customer_code: string;
      name: string;
    };
    salesman: {
      id: number;
      name: string;
    };
    amount: string;
    payment_method: string;
    clearance_status: string;
    cheque_no: null;
    cheque_due_date: null;
    transfer_reference: null;
    collected_at: string;
    allocations: {
      receivable_id: number;
      receivable_no: string;
      amount: string;
      due_date: string;
    }[];
  };
};

/** Response of `GET /api/credit-follow-up/summary` (from live captures). */
export type GetCreditFollowUpSummaryResponse = {
  data: {
    salesman: {
      id: number;
      employee_code: string;
      name: string;
      branch_id: number;
    };
    as_of_date: string;
    period: {
      from: string;
      to: string;
    };
    credit_given_this_month: string;
    collected_this_month: string;
    total_outstanding: string;
    brought_forward: string;
    not_due_amount: string;
    due_today_amount: string;
    overdue_amount: string;
    unbilled_amount: string;
    open_receivables_count: number;
    overdue_receivables_count: number;
    oldest_open_due_date: string | null;
  };
};

/** Response of `GET /api/credit-follow-up/receivables` (from live captures). */
export type GetCreditFollowUpReceivablesResponse = {
  data: {
    id: number;
    receivable_no: string;
    sale_id: number;
    customer_id: number;
    salesman_id: number;
    original_amount: string;
    paid_amount: string;
    remaining_amount: string;
    due_date: string | null;
    payment_status: string;
    aging_status: string;
    days_overdue: number;
    aging_bucket: string;
    allowed_filters?: unknown;
    message?: unknown;
  }[];
};

/** Response of `GET /api/credit-follow-up/aging` (from live captures). */
export type GetCreditFollowUpAgingResponse = {
  data: {
    salesman_id: number;
    as_of_date: string;
    buckets: {
      unbilled: string;
      not_due: string;
      due_today: string;
      overdue_1_7_days: string;
      overdue_8_15_days: string;
      overdue_16_30_days: string;
      overdue_31_60_days: string;
      overdue_61_plus_days: string;
    };
  };
};

/** Response of `GET /api/supervisor/credit-dashboard` (from live captures). */
export type GetSupervisorCreditDashboardResponse = {
  data: {
    supervisor: {
      id: number;
      employee_code: string;
      name: string;
      branch_id: number;
    };
    as_of_date: string;
    team_summary: {
      assigned_salesmen_count: number;
      credit_given_this_month: string;
      collected_this_month: string;
      brought_forward: string;
      total_outstanding: string;
      total_overdue: string;
      unbilled_amount: string;
      open_receivables_count: number;
      overdue_receivables_count: number;
    };
    salesmen: {
      salesman: {
        id: number;
        employee_code: string;
        name: string;
        branch_id: number;
      };
      assignment: {
        start_date: string;
        end_date: null;
        is_active: boolean;
      };
      credit_given_this_month: string;
      collected_this_month: string;
      total_outstanding: string;
      brought_forward: string;
      overdue_amount: string;
      unbilled_amount: string;
      open_receivables_count: number;
      overdue_receivables_count: number;
      customers_with_outstanding_balance: number;
      oldest_open_due_date: string | null;
    }[];
  };
};

/** Query of `GET /api/credit/book` (from the backend validation rules). */
export type GetCreditBookQuery = {
  as_of?: string;
  branch_id?: number;
  channel?: string;
  group?: string;
  include_settled?: boolean;
  only_overdue?: boolean;
  route_id?: number;
  salesman_id?: number;
};

/** Response of `GET /api/credit/book` (from live captures). */
export type GetCreditBookResponse = {
  success: boolean;
  data: {
    as_of: string;
    branch_id: number;
    group: string;
    summary: {
      accounts: number;
      exposure: string;
      overdue: string;
      unbilled: string;
      over_limit_accounts: number;
    };
    accounts: {
      customer_id: number;
      customer_code: string;
      name: string;
      channel: string;
      payment_terms: string;
      billing_cycle: string;
      credit_days: number;
      outlet_count: number;
      routes: {
        id: number;
        code: string;
        name: string;
      }[];
      salesmen: {
        id: number;
        name: string;
        route_id: number;
      }[];
      balance: string;
      overdue: string;
      unbilled: string;
      oldest_unpaid_days: number | null;
      credit_limit: string;
      headroom: string;
      over_limit: boolean;
      chain: null;
      aging: {
        not_due: string;
        days_1_30: string;
        days_31_60: string;
        days_61_90: string;
        days_over_90: string;
        total: string;
      };
    }[];
    integrity: {
      customer_id: number;
      name: string;
      problem: string;
    }[];
    include_settled?: unknown;
    only_overdue?: unknown;
    salesman_id?: unknown;
  };
};

/** Query of `GET /api/credit/customers/{customer}/statement` (from the backend validation rules). */
export type GetCreditCustomersCustomerStatementQuery = {
  from?: string;
  to?: string;
};

/** Response of `GET /api/credit/customers/{customer}/statement` (from live captures). */
export type GetCreditCustomersCustomerStatementResponse = {
  success: boolean;
  data: {
    account: {
      id: number;
      customer_code: string;
      name: string;
      channel: string;
      payment_terms: string;
      credit_days: null;
      credit_account: {
        id: number;
        name: string;
        customer_code: string;
      };
      is_credit_account: boolean;
      outlet_count: number;
    };
    period: {
      from: string;
      to: string;
    };
    opening_balance: string;
    lines: unknown[];
    totals: {
      invoiced: string;
      collected: string;
      movement: string;
      line_count: number;
    };
    closing_balance: string;
    aging: {
      not_due: string;
      days_1_30: string;
      days_31_60: string;
      days_61_90: string;
      days_over_90: string;
      total: string;
    };
    oldest_unpaid_days: null;
    overdue_total: string;
    unbilled_total: string;
    uncleared_receipts: string;
    billing_cycle: string;
    credit_limit: null;
    headroom: null;
    over_limit: boolean;
  };
};

/** Query of `GET /api/credit/period-invoices/pending` (from the backend validation rules). */
export type GetCreditPeriodInvoicesPendingQuery = {
  as_of?: string;
};

/** Response of `GET /api/credit/period-invoices/pending` (from live captures). */
export type GetCreditPeriodInvoicesPendingResponse = {
  success: boolean;
  data: {
    as_of: string;
    branch_id: number | null;
    summary: {
      customers: number;
      unbilled_total: string;
    };
    customers: {
      customer_id: number;
      customer_code: string;
      name: string;
      delivery_count: number;
      amount: string;
      earliest_delivery: string;
      latest_delivery: string;
    }[];
  };
};

/** Query of `GET /api/credit/period-invoices` (from the backend validation rules). */
export type GetCreditPeriodInvoicesQuery = {
  customer_id?: number;
  from?: string;
  to?: string;
};

/** Response of `GET /api/credit/period-invoices` (from live captures). */
export type GetCreditPeriodInvoicesResponse = {
  success: boolean;
  data: {
    id: number;
    invoice_no: string;
    customer: {
      id: number;
      name: string;
      customer_code: string;
    };
    period_start: string;
    period_end: string;
    issued_on: string;
    due_date: string;
    total_amount: string;
    delivery_count: number;
    status: string;
    issued_by: string;
    notes: string;
    amount?: unknown;
    customer_id?: unknown;
    delivered_on?: unknown;
    from?: unknown;
    receivable_no?: unknown;
    remaining?: unknown;
    salesbuzz_invoice_no?: unknown;
    salesman?: unknown;
    to?: unknown;
  }[];
};

/** Response of `GET /api/credit/period-invoices/{periodInvoice}` (from live captures). */
export type GetCreditPeriodInvoicesPeriodInvoiceResponse = {
  success: boolean;
  data: {
    id: number;
    invoice_no: string;
    customer: {
      id: number;
      name: string;
      customer_code: string;
    };
    period_start: string;
    period_end: string;
    issued_on: string;
    due_date: string;
    total_amount: string;
    delivery_count: number;
    status: string;
    issued_by: string;
    notes: string;
    deliveries: {
      receivable_no: string;
      delivered_on: string;
      salesbuzz_invoice_no: string;
      salesman: string;
      amount: string;
      remaining: string;
      status: string;
    }[];
  };
};

/** Body of `POST /api/credit/period-invoices` (from the backend validation rules). */
export type PostCreditPeriodInvoicesBody = {
  customer_id: number;
  notes?: string;
  period_end: string;
  period_start: string;
};

/** Response of `POST /api/credit/period-invoices` (no capture: keys from backend code only). */
export type PostCreditPeriodInvoicesResponse = {
  amount?: unknown;
  customer?: unknown;
  customer_code?: unknown;
  customer_id?: unknown;
  delivered_on?: unknown;
  delivery_count?: unknown;
  due_date?: unknown;
  id?: unknown;
  invoice_no?: unknown;
  issued_by?: unknown;
  issued_on?: unknown;
  message?: unknown;
  name?: unknown;
  notes?: unknown;
  period_end?: unknown;
  period_start?: unknown;
  receivable_no?: unknown;
  remaining?: unknown;
  salesbuzz_invoice_no?: unknown;
  salesman?: unknown;
  status?: unknown;
  total_amount?: unknown;
};
