// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/areas` (from the backend validation rules). */
export type GetAreasQuery = {
  is_active?: boolean;
  q?: string;
};

/** Response of `GET /api/areas` (from live captures). */
export type GetAreasResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    code: string;
    name: string;
    customer_count: number;
    routes: {
      id: number;
      code: string;
      name: string;
    }[];
    is_active: boolean;
    q?: unknown;
  }[];
};

/** Body of `POST /api/areas` (from the backend validation rules). */
export type PostAreasBody = {
  branch_id?: number;
  code: string;
  is_active?: boolean;
  name: string;
};

/** Response of `POST /api/areas` (no capture: keys from backend code only). */
export type PostAreasResponse = {
  branch_id?: unknown;
  code?: unknown;
  id?: unknown;
  is_active?: unknown;
  message?: unknown;
  name?: unknown;
};

/** Body of `PATCH /api/areas/{area}` (from the backend validation rules). */
export type PatchAreasAreaBody = {
  branch_id?: number;
  code?: string;
  is_active?: boolean;
  name?: string;
};

/** Response of `PATCH /api/areas/{area}` (no capture: keys from backend code only). */
export type PatchAreasAreaResponse = {
  branch_id?: unknown;
  code?: unknown;
  id?: unknown;
  is_active?: unknown;
  message?: unknown;
  name?: unknown;
};

/** Response of `GET /api/customers/{customer}` (from live captures). */
export type GetCustomersCustomerResponse = {
  success: boolean;
  data: {
    id: number;
    customer_code: string;
    salesbuzz_code: string;
    name: string;
    phone: string;
    address: string;
    area: string;
    channel: string;
    customer_type: string;
    latitude: number;
    longitude: number;
    discount_rate: number;
    payment_terms: string;
    tax_rate: number;
    credit: {
      account_customer_id: number;
      limit: null;
      outstanding: string;
      available: null;
      days: null;
    };
    is_active: boolean;
  };
};

/** Response of `GET /api/customer-channels` (from live captures). */
export type GetCustomerChannelsResponse = {
  success: boolean;
  data: {
    id: null;
    code: string;
    name_ar: string;
    name_en: string;
    sort_order: number;
    company_wide: boolean;
  }[];
};

/** Body of `POST /api/customer-channels` (from the backend validation rules). */
export type PostCustomerChannelsBody = {
  code: string;
  name_ar: string;
  name_en?: string;
  sort_order?: number;
};

/** Response of `POST /api/customer-channels` (no capture: keys from backend code only). */
export type PostCustomerChannelsResponse = {
  branch_id?: unknown;
  code?: unknown;
  company_wide?: unknown;
  id?: unknown;
  is_active?: unknown;
  message?: unknown;
  name_ar?: unknown;
  name_en?: unknown;
  sort_order?: unknown;
};

/** Response of `POST /api/customer-channels/{customerChannel}/retire` (no capture: keys from backend code only). */
export type PostCustomerChannelsCustomerChannelRetireResponse = Record<string, unknown>;

/** Query of `GET /api/customers` (from the backend validation rules). */
export type GetCustomersQuery = {
  area_id?: number;
  channel?: string;
  is_active?: boolean;
  payment_terms?: string;
  per_page?: number;
  q?: string;
  route_id?: number;
};

/** Response of `GET /api/customers` (from live captures). */
export type GetCustomersResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    customer_code: string;
    salesbuzz_code: string;
    name: string;
    phone: string;
    address: string;
    area: string;
    area_id: number;
    channel: string;
    customer_type: string;
    chain: null;
    credit: {
      payment_terms: string;
      billing_cycle: string;
      credit_limit: string | null;
      credit_days: number | null;
      discount_rate: string;
    };
    tax_registration_no: null;
    tax_rate: string;
    latitude: number;
    longitude: number;
    notes: null;
    is_active: boolean;
    code?: unknown;
    q?: unknown;
    route_id?: unknown;
    visit_order?: unknown;
  }[];
  meta: {
    total: number;
    per_page: number;
    current_page: number;
    last_page: number;
  };
};

/** Body of `POST /api/customers` (from the backend validation rules). */
export type PostCustomersBody = {
  address?: string;
  area_id?: number;
  billing_cycle?: string;
  branch_id?: number;
  channel?: string;
  credit_days?: number;
  credit_limit?: string | number;
  customer_code: string;
  customer_type?: string;
  discount_rate?: string | number;
  is_active?: boolean;
  latitude?: string | number;
  longitude?: string | number;
  name: string;
  notes?: string;
  parent_customer_id?: number;
  payment_terms?: string;
  phone?: string;
  routes?: {
    is_active?: boolean;
    route_id: number;
    visit_order?: number;
  }[];
  salesbuzz_code?: string;
  tax_rate?: string | number;
  tax_registration_no?: string;
};

/** Response of `POST /api/customers` (no capture: keys from backend code only). */
export type PostCustomersResponse = {
  address?: unknown;
  area?: unknown;
  area_id?: unknown;
  billing_cycle?: unknown;
  branch_id?: unknown;
  chain?: unknown;
  channel?: unknown;
  code?: unknown;
  credit?: unknown;
  credit_days?: unknown;
  credit_limit?: unknown;
  customer_code?: unknown;
  customer_type?: unknown;
  discount_rate?: unknown;
  id?: unknown;
  is_active?: unknown;
  latitude?: unknown;
  longitude?: unknown;
  message?: unknown;
  name?: unknown;
  notes?: unknown;
  payment_terms?: unknown;
  phone?: unknown;
  route_id?: unknown;
  salesbuzz_code?: unknown;
  tax_rate?: unknown;
  tax_registration_no?: unknown;
  visit_order?: unknown;
};

/** Body of `PATCH /api/customers/{customer}` (from the backend validation rules). */
export type PatchCustomersCustomerBody = {
  address?: string;
  area_id?: number;
  billing_cycle?: string;
  branch_id?: number;
  channel?: string;
  credit_days?: number;
  credit_limit?: string | number;
  customer_code?: string;
  customer_type?: string;
  discount_rate?: string | number;
  is_active?: boolean;
  latitude?: string | number;
  longitude?: string | number;
  name?: string;
  notes?: string;
  parent_customer_id?: number;
  payment_terms?: string;
  phone?: string;
  routes?: {
    is_active?: boolean;
    route_id: number;
    visit_order?: number;
  }[];
  salesbuzz_code?: string;
  tax_rate?: string | number;
  tax_registration_no?: string;
};

/** Response of `PATCH /api/customers/{customer}` (no capture: keys from backend code only). */
export type PatchCustomersCustomerResponse = {
  address?: unknown;
  area?: unknown;
  area_id?: unknown;
  billing_cycle?: unknown;
  branch_id?: unknown;
  chain?: unknown;
  channel?: unknown;
  code?: unknown;
  credit?: unknown;
  credit_days?: unknown;
  credit_limit?: unknown;
  customer_code?: unknown;
  customer_type?: unknown;
  discount_rate?: unknown;
  id?: unknown;
  is_active?: unknown;
  latitude?: unknown;
  longitude?: unknown;
  message?: unknown;
  name?: unknown;
  notes?: unknown;
  payment_terms?: unknown;
  phone?: unknown;
  route_id?: unknown;
  salesbuzz_code?: unknown;
  tax_rate?: unknown;
  tax_registration_no?: unknown;
  visit_order?: unknown;
};

/** Body of `POST /api/customers/import/preview` (from the backend validation rules). */
export type PostCustomersImportPreviewBody = {
  branch_id?: number;
  rows: {
    address?: string;
    area_id?: number;
    billing_cycle?: string;
    channel?: string;
    credit_days?: number;
    credit_limit?: string | number;
    customer_code: string;
    customer_type?: string;
    discount_rate?: string | number;
    is_active?: boolean;
    latitude?: string | number;
    longitude?: string | number;
    name: string;
    notes?: string;
    parent_customer_id?: number;
    payment_terms?: string;
    phone?: string;
    routes?: {
      is_active?: boolean;
      route_id: number;
      visit_order?: number;
    }[];
    salesbuzz_code?: string;
    tax_rate?: string | number;
    tax_registration_no?: string;
  }[];
};

/** Response of `POST /api/customers/import/preview` (no capture: keys from backend code only). */
export type PostCustomersImportPreviewResponse = Record<string, unknown>;

/** Body of `POST /api/customers/import` (from the backend validation rules). */
export type PostCustomersImportBody = {
  branch_id?: number;
  rows: {
    address?: string;
    area_id?: number;
    billing_cycle?: string;
    channel?: string;
    credit_days?: number;
    credit_limit?: string | number;
    customer_code: string;
    customer_type?: string;
    discount_rate?: string | number;
    is_active?: boolean;
    latitude?: string | number;
    longitude?: string | number;
    name: string;
    notes?: string;
    parent_customer_id?: number;
    payment_terms?: string;
    phone?: string;
    routes?: {
      is_active?: boolean;
      route_id: number;
      visit_order?: number;
    }[];
    salesbuzz_code?: string;
    tax_rate?: string | number;
    tax_registration_no?: string;
  }[];
};

/** Response of `POST /api/customers/import` (no capture: keys from backend code only). */
export type PostCustomersImportResponse = {
  message?: unknown;
};

/** Response of `GET /api/customers/{customer}/receivables` (from live captures). */
export type GetCustomersCustomerReceivablesResponse = {
  customer: {
    id: number;
    name: string;
  };
  outstanding_total: number;
  data: unknown[];
};
