// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Response of `GET /api/my/day` (from live captures). */
export type GetMyDayResponse = {
  success: boolean;
  data: {
    synced_at: string;
    employee: {
      id: number;
      name: string;
      employee_code: string;
      position_code: string;
      branch_id: number;
    };
    trip: {
      id: number;
      session_no: string;
      business_date: string;
      trip_no: number;
      status: string;
      branch: {
        id: number;
        code: string;
        name: string;
      };
      route: {
        id: number;
        code: string;
        name: string;
      };
      vehicle: {
        id: number;
        code: string;
        plate_number: string;
      };
      driver: string;
      started_at: string;
      route_started_at: null;
      open_visit: null;
      stock_closing: null;
      cash_closing: null;
    } | null;
    customers: unknown[];
    products: {
      id: number;
      code: string;
      name: string;
      category: string | null;
      barcode: string;
      salesbuzz_code: string;
      units_per_carton: number;
      price: string;
      sellable: boolean;
    }[];
    vehicle_stock: unknown[];
    expense_categories: {
      id: number;
      code: string;
      name: string;
      name_ar: string;
      requires_vehicle: boolean;
      requires_odometer: boolean;
    }[];
    capabilities: string[];
  };
};

/** Response of `GET /api/my/customers` (from live captures). */
export type GetMyCustomersResponse = {
  success: boolean;
  trip: {
    id: number;
    route: string;
    business_date: string;
  } | null;
  data: unknown[];
};

/** Query of `GET /api/my/catalogue` (from the backend validation rules). */
export type GetMyCatalogueQuery = {
  business_date?: string;
};

/** Response of `GET /api/my/catalogue` (from live captures). */
export type GetMyCatalogueResponse = {
  success: boolean;
  business_date: string;
  data: {
    id: number;
    code: string;
    name: string;
    category: string | null;
    barcode: string;
    salesbuzz_code: string;
    units_per_carton: number;
    price: string;
    sellable: boolean;
  }[];
};

/** Query of `GET /api/my/performance` (from the backend validation rules). */
export type GetMyPerformanceQuery = {
  as_of?: string;
  period_end: string;
  period_start: string;
};

/** Response of `GET /api/my/performance` (from live captures). */
export type GetMyPerformanceResponse = {
  success: boolean;
  data: {
    branch_id: number;
    period_start: string;
    period_end: string;
    as_of: string;
    last_working_day: string;
    working_days: number;
    working_days_elapsed: number;
    working_days_remaining: number;
    time_gone_percent: null;
    rows: unknown[];
    totals: {
      nps_target: number;
      nps_actual: number;
      nps_percent: null;
      invoice_target: number;
      invoice_actual: number;
      invoice_percent: null;
      new_customers: number;
      drop_size: number;
    };
  };
};

/** Query of `GET /api/my/sales-by-channel` (from the backend validation rules). */
export type GetMySalesByChannelQuery = {
  business_date?: string;
};

/** Response of `GET /api/my/sales-by-channel` (from live captures). */
export type GetMySalesByChannelResponse = {
  success: boolean;
  data: {
    branch_id: number;
    business_date: string;
    salesman_id: number;
    rows: {
      code: string;
      name_ar: string;
      name_en: string;
      is_active: boolean;
      invoice_count: number;
      customer_count: number;
      sales_amount: string;
      cash_amount: string;
      credit_amount: string;
      tpp_amount: string;
      discount_amount: string;
    }[];
    totals: {
      invoice_count: number;
      customer_count: number;
      sales_amount: string;
      cash_amount: string;
      credit_amount: string;
      tpp_amount: string;
      discount_amount: string;
    };
  };
};

/** Body of `POST /api/daily-sessions` (from the backend validation rules). */
export type PostDailySessionsBody = {
  business_date: string;
  driver_id: number;
  route_id: number;
  salesman_id: number;
  supervisor_id?: number;
  trip_no?: number;
  vehicle_id: number;
};

/** Response of `POST /api/daily-sessions` (no capture: keys from backend code only). */
export type PostDailySessionsResponse = {
  message?: unknown;
};

/** Response of `POST /api/daily-sessions/{dailySession}/start-route` (no capture: keys from backend code only). */
export type PostDailySessionsDailySessionStartRouteResponse = {
  message?: unknown;
};

/** Response of `GET /api/my/salesman-stock-requests` (from live captures). */
export type GetMySalesmanStockRequestsResponse = {
  data: {
    id: number;
    request_no: string;
    daily_session_id: number;
    branch_id: number;
    salesman_id: number;
    vehicle_id: number;
    requested_by: number;
    status: string;
    submitted_at: string;
    processed_by: number;
    processed_at: string;
    notes: string;
    created_at: string;
    updated_at: string;
    session: {
      id: number;
      session_no: string;
      branch_id: number;
      salesman_id: number;
      driver_id: number;
      supervisor_id: number;
      vehicle_id: number;
      route_id: number;
      business_date: string;
      trip_no: number;
      status: string;
      started_at: string;
      route_started_at: string | null;
      route_completed_at: null;
      returned_at: string | null;
      closed_at: string | null;
      created_at: string;
      updated_at: string;
    };
    vehicle: {
      id: number;
      branch_id: number;
      code: string;
      plate_number: string;
      model: string;
      make: null;
      year_of_manufacture: null;
      chassis_number: null;
      engine_number: null;
      fuel_type: null;
      tank_capacity_litres: null;
      licence_expires_on: null;
      insurance_expires_on: null;
      current_odometer: null;
      status: string;
      notes: null;
      is_active: boolean;
      created_at: string;
      updated_at: string;
    };
    items: {
      id: number;
      salesman_stock_request_id: number;
      product_id: number;
      requested_quantity_cartons: string;
      created_at: string;
      updated_at: string;
      product: {
        id: number;
        code: string;
        name: string;
        category: string | null;
        unit_cost: string;
        trade_price: string;
        units_per_carton: number;
        barcode: string;
        salesbuzz_code: string;
        shelf_life_days: number;
        storage_temp_min: string;
        storage_temp_max: string;
        is_active: boolean;
        created_at: string;
        updated_at: string;
      };
    }[];
  }[];
};

/** Response of `GET /api/my/pending-stock-issues` (from live captures). */
export type GetMyPendingStockIssuesResponse = {
  data: {
    id: number;
    issue_no: string;
    daily_session_id: number;
    salesman_stock_request_id: number;
    warehouse_id: number;
    salesman_id: number;
    vehicle_id: number;
    issued_by: number;
    confirmed_by: null;
    status: string;
    issued_at: string;
    confirmed_at: null;
    notes: null;
    created_at: string;
    updated_at: string;
    items: {
      id: number;
      stock_issue_id: number;
      product_id: number;
      quantity_cartons: number;
      created_at: string;
      updated_at: string;
      product: {
        id: number;
        code: string;
        name: string;
        category: string | null;
        unit_cost: string;
        trade_price: string;
        units_per_carton: number;
        barcode: string;
        salesbuzz_code: string;
        shelf_life_days: number;
        storage_temp_min: string;
        storage_temp_max: string;
        is_active: boolean;
        created_at: string;
        updated_at: string;
      };
    }[];
    warehouse: {
      id: number;
      branch_id: number;
      code: string;
      name: string;
      address: null;
      is_active: boolean;
      created_at: string;
      updated_at: string;
    };
    vehicle: {
      id: number;
      branch_id: number;
      code: string;
      plate_number: string;
      model: string;
      make: null;
      year_of_manufacture: null;
      chassis_number: null;
      engine_number: null;
      fuel_type: null;
      tank_capacity_litres: null;
      licence_expires_on: null;
      insurance_expires_on: null;
      current_odometer: null;
      status: string;
      notes: null;
      is_active: boolean;
      created_at: string;
      updated_at: string;
    };
    salesman_stock_request: {
      id: number;
      request_no: string;
      daily_session_id: number;
      branch_id: number;
      salesman_id: number;
      vehicle_id: number;
      requested_by: number;
      status: string;
      submitted_at: string;
      processed_by: number;
      processed_at: string;
      notes: string;
      created_at: string;
      updated_at: string;
    };
    session: {
      id: number;
      session_no: string;
      branch_id: number;
      salesman_id: number;
      driver_id: number;
      supervisor_id: number;
      vehicle_id: number;
      route_id: number;
      business_date: string;
      trip_no: number;
      status: string;
      started_at: string;
      route_started_at: null;
      route_completed_at: null;
      returned_at: null;
      closed_at: null;
      created_at: string;
      updated_at: string;
      route: {
        id: number;
        branch_id: number;
        code: string;
        name: string;
        description: string;
        is_active: boolean;
        created_at: string;
        updated_at: string;
      };
    };
  }[];
};

/** Response of `GET /api/my/stock` (from live captures). */
export type GetMyStockResponse = {
  vehicle: {
    id: number;
    code: string;
    plate_number: string;
  } | null;
  location: {
    id: number;
    name: string;
    type: string;
  } | null;
  data: unknown[];
  trip?: {
    id: number;
    session_no: string;
    business_date: string;
    trip_no: number;
    status: string;
  };
};

/** Response of `GET /api/daily-sessions/{dailySession}/count-sheet` (from live captures). */
export type GetDailySessionsDailySessionCountSheetResponse = {
  success: boolean;
  trip: {
    id: number;
    session_no: string;
    business_date: string;
    status: string;
    vehicle_id: number;
  };
  data: unknown[];
  code?: unknown;
  name?: unknown;
  product?: unknown;
  product_id?: unknown;
  system_quantity_cartons?: unknown;
};
