// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Body of `POST /api/fuel-vouchers` (from the backend validation rules). */
export type PostFuelVouchersBody = {
  driver_id?: number;
  issued_on?: string;
  notes?: string;
  vehicle_id: number;
  voucher_no: string;
};

/** Response of `POST /api/fuel-vouchers` (no capture: keys from backend code only). */
export type PostFuelVouchersResponse = {
  driver_id?: unknown;
  issued_on?: unknown;
  notes?: unknown;
  vehicle_id?: unknown;
  voucher_no?: unknown;
};

/** Query of `GET /api/fuel-vouchers` (from the backend validation rules). */
export type GetFuelVouchersQuery = {
  from?: string;
  status?: string;
  to?: string;
  vehicle_id?: number;
};

/** Response of `GET /api/fuel-vouchers` (from live captures). */
export type GetFuelVouchersResponse = {
  success: boolean;
  data: {
    branch_id: number | null;
    summary: {
      issued: number;
      outstanding: number;
      redeemed: number;
      cancelled: number;
      total_litres: number;
      total_amount: string;
    };
    vouchers: {
      id: number;
      voucher_no: string;
      status: string;
      vehicle: {
        id: number;
        code: string;
        plate_number: string;
      };
      driver: string;
      issued_on: string;
      issued_by: string;
      litres: number;
      amount: string;
      station: string;
      redeemed_on: string;
      redeemed_by: string;
      expense_id: null;
      notes: null;
    }[];
    from?: unknown;
    to?: unknown;
    vehicle_id?: unknown;
  };
};

/** Body of `POST /api/fuel-vouchers/settle-invoice` (from the backend validation rules). */
export type PostFuelVouchersSettleInvoiceBody = {
  branch_id?: number;
  expense_id?: number;
  invoiced_on?: string;
  lines: {
    amount?: string | number;
    litres?: string | number;
    voucher_no: string;
  }[];
  station?: string;
};

/** Response of `POST /api/fuel-vouchers/settle-invoice` (no capture: keys from backend code only). */
export type PostFuelVouchersSettleInvoiceResponse = {
  branch_id?: unknown;
  expense_id?: unknown;
  invoiced_on?: unknown;
  lines?: unknown;
  station?: unknown;
};

/** Body of `POST /api/fuel-vouchers/pay-invoice` (from the backend validation rules). */
export type PostFuelVouchersPayInvoiceBody = {
  amount: string | number;
  branch_id?: number;
  description?: string;
  expense_category_id: number;
  invoice_no?: string;
  odometer_readings?: unknown[] | Record<string, unknown>;
  paid_on?: string;
  payment_method?: string;
  station?: string;
  voucher_nos: unknown[] | Record<string, unknown>;
};

/** Response of `POST /api/fuel-vouchers/pay-invoice` (no capture: keys from backend code only). */
export type PostFuelVouchersPayInvoiceResponse = {
  amount?: unknown;
  branch_id?: unknown;
  description?: unknown;
  expense_category_id?: unknown;
  invoice_no?: unknown;
  odometer_readings?: unknown;
  paid_on?: unknown;
  payment_method?: unknown;
  station?: unknown;
  voucher_nos?: unknown;
};

/** Body of `POST /api/fuel-vouchers/{fuelVoucher}/redeem` (from the backend validation rules). */
export type PostFuelVouchersFuelVoucherRedeemBody = {
  amount?: string | number;
  litres?: string | number;
  notes?: string;
  redeemed_on?: string;
  station?: string;
};

/** Response of `POST /api/fuel-vouchers/{fuelVoucher}/redeem` (no capture: keys from backend code only). */
export type PostFuelVouchersFuelVoucherRedeemResponse = {
  amount?: unknown;
  litres?: unknown;
  notes?: unknown;
  redeemed_on?: unknown;
  station?: unknown;
};

/** Body of `POST /api/fuel-vouchers/{fuelVoucher}/cancel` (from the backend validation rules). */
export type PostFuelVouchersFuelVoucherCancelBody = {
  notes?: string;
};

/** Response of `POST /api/fuel-vouchers/{fuelVoucher}/cancel` (no capture: keys from backend code only). */
export type PostFuelVouchersFuelVoucherCancelResponse = {
  notes?: unknown;
};

/** Query of `GET /api/expense-categories` (from the backend validation rules). */
export type GetExpenseCategoriesQuery = {
  scope?: string;
};

/** Response of `GET /api/expense-categories` (from live captures). */
export type GetExpenseCategoriesResponse = {
  success: boolean;
  data: {
    id: number;
    code: string;
    name: string;
    name_ar: string;
    parent_id: number | null;
    scope: string;
    requires_vehicle: boolean;
    requires_odometer: boolean;
  }[];
};

/** Query of `GET /api/expenses` (from the backend validation rules). */
export type GetExpensesQuery = {
  daily_session_id?: number;
  from?: string;
  status?: string;
  to?: string;
};

/** Response of `GET /api/expenses` (from live captures). */
export type GetExpensesResponse = {
  success: boolean;
  summary: {
    count: number;
    total_amount: string;
  };
  data: {
    id: number;
    expense_no: string;
    amount: string;
    expense_date: string;
    status: string;
    funding_source: string;
    payment_method: string;
    odometer_reading: null;
    category: {
      id: number;
      code: string;
      name: string;
      name_ar: string;
    };
    daily_session_id: number | null;
    vehicle_id: number | null;
    employee: string;
    is_route_expense: boolean;
    cash_movement_id: number | null;
    receipt_required: boolean;
    attachment_count: number;
    attachments: {
      id: number;
      type: string;
      original_name: string;
      mime_type: string;
      file_size: number;
      uploaded_at: string;
      download_url: string;
    }[];
    supplier_name: string | null;
    document_no: string | null;
    description: string;
    reviewed_by: string | null;
    reviewed_at: string | null;
    review_notes: string | null;
    from?: unknown;
    to?: unknown;
  }[];
};

/** Body of `POST /api/expenses` (from the backend validation rules). */
export type PostExpensesBody = {
  amount: string | number;
  branch_id?: number;
  daily_session_id?: number;
  description?: string;
  document_no?: string;
  employee_id?: number;
  expense_category_id: number;
  expense_date?: string;
  funding_source?: string;
  odometer_reading?: number;
  payment_method?: string;
  supplier_name?: string;
  vehicle_id?: number;
};

/** Response of `POST /api/expenses` (no capture: keys from backend code only). */
export type PostExpensesResponse = {
  amount?: unknown;
  attachment_count?: unknown;
  attachments?: unknown;
  cash_movement_id?: unknown;
  category?: unknown;
  code?: unknown;
  daily_session_id?: unknown;
  description?: unknown;
  document_no?: unknown;
  download_url?: unknown;
  employee?: unknown;
  expense_date?: unknown;
  expense_no?: unknown;
  file_size?: unknown;
  funding_source?: unknown;
  id?: unknown;
  is_route_expense?: unknown;
  message?: unknown;
  mime_type?: unknown;
  name?: unknown;
  name_ar?: unknown;
  odometer_reading?: unknown;
  original_name?: unknown;
  payment_method?: unknown;
  receipt_required?: unknown;
  review_notes?: unknown;
  reviewed_at?: unknown;
  reviewed_by?: unknown;
  status?: unknown;
  supplier_name?: unknown;
  type?: unknown;
  uploaded_at?: unknown;
  vehicle_id?: unknown;
};

/** Body of `POST /api/expenses/{expense}/approve` (from the backend validation rules). */
export type PostExpensesExpenseApproveBody = {
  notes?: string;
};

/** Response of `POST /api/expenses/{expense}/approve` (from live captures). */
export type PostExpensesExpenseApproveResponse = {
  success: boolean;
  message: string;
  data: {
    id: number;
    expense_no: string;
    amount: string;
    expense_date: string;
    status: string;
    funding_source: string;
    payment_method: string;
    odometer_reading: null;
    category: {
      id: number;
      code: string;
      name: string;
      name_ar: string;
    };
    daily_session_id: number;
    vehicle_id: number;
    employee: string;
    is_route_expense: boolean;
    cash_movement_id: number;
    receipt_required: boolean;
    attachment_count: number;
    attachments: {
      id: number;
      type: string;
      original_name: string;
      mime_type: string;
      file_size: number;
      uploaded_at: string;
      download_url: string;
    }[];
    supplier_name: null;
    document_no: null;
    description: string;
    reviewed_by: string;
    reviewed_at: string;
    review_notes: null;
    notes?: unknown;
  };
};

/** Body of `POST /api/expenses/{expense}/reject` (from the backend validation rules). */
export type PostExpensesExpenseRejectBody = {
  reason: string;
};

/** Response of `POST /api/expenses/{expense}/reject` (no capture: keys from backend code only). */
export type PostExpensesExpenseRejectResponse = {
  amount?: unknown;
  attachment_count?: unknown;
  attachments?: unknown;
  cash_movement_id?: unknown;
  category?: unknown;
  code?: unknown;
  daily_session_id?: unknown;
  description?: unknown;
  document_no?: unknown;
  download_url?: unknown;
  employee?: unknown;
  expense_date?: unknown;
  expense_no?: unknown;
  file_size?: unknown;
  funding_source?: unknown;
  id?: unknown;
  is_route_expense?: unknown;
  message?: unknown;
  mime_type?: unknown;
  name?: unknown;
  name_ar?: unknown;
  odometer_reading?: unknown;
  original_name?: unknown;
  payment_method?: unknown;
  reason?: unknown;
  receipt_required?: unknown;
  review_notes?: unknown;
  reviewed_at?: unknown;
  reviewed_by?: unknown;
  status?: unknown;
  supplier_name?: unknown;
  type?: unknown;
  uploaded_at?: unknown;
  vehicle_id?: unknown;
};
