// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/gate/movements` (from the backend validation rules). */
export type GetGateMovementsQuery = {
  business_date?: string;
  vehicle_id?: number;
};

/** Response of `GET /api/gate/movements` (from live captures). */
export type GetGateMovementsResponse = {
  success: boolean;
  data: {
    id: number;
    direction: string;
    business_date: string;
    occurred_at: string;
    vehicle: {
      id: number;
      code: string;
      plate_number: string;
    };
    route: string;
    driver: string;
    salesman: string;
    odometer_reading: number;
    refrigeration_ok: boolean;
    fuel_issued_litres: number | null;
    seal_no: string | null;
    notes: null;
    daily_session_id: number;
    recorded_by: string;
    vehicle_id?: unknown;
  }[];
};

/** Body of `POST /api/gate/movements` (from the backend validation rules). */
export type PostGateMovementsBody = {
  business_date?: string;
  daily_session_id?: number;
  direction: string;
  driver_id?: number;
  fuel_issued_litres?: string | number;
  notes?: string;
  occurred_at?: string;
  odometer_reading?: number;
  refrigeration_ok?: boolean;
  route_id?: number;
  salesman_id?: number;
  seal_no?: string;
  vehicle_id: number;
};

/** Response of `POST /api/gate/movements` (no capture: keys from backend code only). */
export type PostGateMovementsResponse = {
  business_date?: unknown;
  code?: unknown;
  daily_session_id?: unknown;
  direction?: unknown;
  driver?: unknown;
  driver_id?: unknown;
  fuel_issued_litres?: unknown;
  id?: unknown;
  message?: unknown;
  notes?: unknown;
  occurred_at?: unknown;
  odometer_reading?: unknown;
  plate_number?: unknown;
  recorded_by?: unknown;
  refrigeration_ok?: unknown;
  route?: unknown;
  route_id?: unknown;
  salesman?: unknown;
  salesman_id?: unknown;
  seal_no?: unknown;
  vehicle?: unknown;
  vehicle_id?: unknown;
};

/** Query of `GET /api/gate/exceptions` (from the backend validation rules). */
export type GetGateExceptionsQuery = {
  branch_id?: number;
  business_date?: string;
};

/** Response of `GET /api/gate/exceptions` (from live captures). */
export type GetGateExceptionsResponse = {
  success: boolean;
  summary: {
    count: number;
  };
  data: {
    type: string;
    vehicle: string;
    salesman: string;
    detail: string;
    branch_id?: unknown;
    business_date?: unknown;
  }[];
};

/** Body of `POST /api/cold-rooms` (from the backend validation rules). */
export type PostColdRoomsBody = {
  code: string;
  is_active?: boolean;
  max_celsius?: string | number;
  min_celsius?: string | number;
  name?: string;
};

/** Response of `POST /api/cold-rooms` (no capture: keys from backend code only). */
export type PostColdRoomsResponse = {
  code?: unknown;
  is_active?: unknown;
  max_celsius?: unknown;
  min_celsius?: unknown;
  name?: unknown;
};

/** Response of `GET /api/cold-rooms` (from live captures). */
export type GetColdRoomsResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    code: string;
    name: string;
    min_celsius: string;
    max_celsius: string;
    monitored_only: boolean;
    is_active: boolean;
  }[];
};

/** Body of `POST /api/cold-rooms/readings` (from the backend validation rules). */
export type PostColdRoomsReadingsBody = {
  business_date?: string;
  celsius: string | number;
  cold_room_id: number;
  notes?: string;
  reading_hour: number;
};

/** Response of `POST /api/cold-rooms/readings` (no capture: keys from backend code only). */
export type PostColdRoomsReadingsResponse = {
  business_date?: unknown;
  celsius?: unknown;
  cold_room_id?: unknown;
  notes?: unknown;
  reading_hour?: unknown;
};

/** Query of `GET /api/cold-rooms/sheet` (from the backend validation rules). */
export type GetColdRoomsSheetQuery = {
  business_date?: string;
};

/** Response of `GET /api/cold-rooms/sheet` (from live captures). */
export type GetColdRoomsSheetResponse = {
  success: boolean;
  data: {
    branch_id: number | null;
    business_date: string;
    rooms: {
      cold_room: {
        id: number;
        code: string;
        name: string;
        min_celsius: string;
        max_celsius: string;
        monitored_only: boolean;
      };
      readings: {
        id: number;
        cold_room_id: number;
        business_date: string;
        reading_hour: number;
        celsius: number;
        out_of_range: boolean;
        recorded_by: string;
        recorded_at: string;
        notes: null;
      }[];
      breaches: number;
      hours_not_read: number[];
    }[];
  };
};

/** Query of `GET /api/cold-rooms/breaches` (from the backend validation rules). */
export type GetColdRoomsBreachesQuery = {
  from?: string;
  to?: string;
};

/** Response of `GET /api/cold-rooms/breaches` (from live captures). */
export type GetColdRoomsBreachesResponse = {
  success: boolean;
  data: {
    id: number;
    business_date: string;
    reading_hour: number;
    celsius: number;
    room: string;
    min_celsius: string;
    max_celsius: string;
    recorded_by: string;
    from?: unknown;
    to?: unknown;
  }[];
};

/** Query of `GET /api/attendance` (from the backend validation rules). */
export type GetAttendanceQuery = {
  business_date?: string;
};

/** Response of `GET /api/attendance` (from live captures). */
export type GetAttendanceResponse = {
  success: boolean;
  data: {
    id: number;
    employee: string;
    employee_id: number;
    business_date: string;
    shift: string;
    checked_in_at: string;
    checked_out_at: null;
    notes: null;
  }[];
};

/** Body of `POST /api/attendance` (from the backend validation rules). */
export type PostAttendanceBody = {
  business_date?: string;
  checked_in_at?: string;
  checked_out_at?: string;
  employee_id: number;
  notes?: string;
  shift?: string;
};

/** Response of `POST /api/attendance` (from live captures). */
export type PostAttendanceResponse = {
  success: boolean;
  message: string;
  data: {
    id: number;
    employee: string;
    business_date: string;
    shift: string;
    checked_in_at: string;
    checked_out_at: string;
    employee_id?: unknown;
    notes?: unknown;
  };
};
