// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/opening-balances` (from the backend validation rules). */
export type GetOpeningBalancesQuery = {
  branch_id?: number;
};

/** Response of `GET /api/opening-balances` (from live captures). */
export type GetOpeningBalancesResponse = {
  success: boolean;
  data: {
    branch_id: number;
    status: string;
    customer_count: number;
    total: string;
    outstanding: string;
    collected: string;
    editable: boolean;
    as_of: string;
    verified_by: string;
    verified_at: string;
    journal_entry_no: string;
    notes: string;
  };
};

/** Query of `GET /api/opening-balances/entries` (from the backend validation rules). */
export type GetOpeningBalancesEntriesQuery = {
  branch_id?: number;
};

/** Response of `GET /api/opening-balances/entries` (from live captures). */
export type GetOpeningBalancesEntriesResponse = {
  success: boolean;
  data: {
    id: number;
    customer_id: number;
    customer_code: string;
    customer_name: string;
    amount: string;
    outstanding: string;
    locked: boolean;
    branch_id?: unknown;
  }[];
};

/** Body of `POST /api/opening-balances/preview` (from the backend validation rules). */
export type PostOpeningBalancesPreviewBody = {
  branch_id?: number;
  rows: {
    amount: string | number;
    customer_code: string;
  }[];
};

/** Response of `POST /api/opening-balances/preview` (no capture: keys from backend code only). */
export type PostOpeningBalancesPreviewResponse = Record<string, unknown>;

/** Body of `POST /api/opening-balances/entries` (from the backend validation rules). */
export type PostOpeningBalancesEntriesBody = {
  amount: string | number;
  branch_id?: number;
  customer_code: string;
};

/** Response of `POST /api/opening-balances/entries` (no capture: keys from backend code only). */
export type PostOpeningBalancesEntriesResponse = {
  amount?: unknown;
  branch_id?: unknown;
  customer_code?: unknown;
  message?: unknown;
};

/** Response of `DELETE /api/opening-balances/entries/{receivable}` (no capture: keys from backend code only). */
export type DeleteOpeningBalancesEntriesReceivableResponse = {
  message?: unknown;
};

/** Body of `POST /api/opening-balances/import` (from the backend validation rules). */
export type PostOpeningBalancesImportBody = {
  branch_id?: number;
  rows: {
    amount: string | number;
    customer_code: string;
  }[];
};

/** Response of `POST /api/opening-balances/import` (no capture: keys from backend code only). */
export type PostOpeningBalancesImportResponse = {
  message?: unknown;
};

/** Body of `POST /api/opening-balances/verify` (from the backend validation rules). */
export type PostOpeningBalancesVerifyBody = {
  as_of: string;
  branch_id?: number;
  notes?: string;
};

/** Response of `POST /api/opening-balances/verify` (no capture: keys from backend code only). */
export type PostOpeningBalancesVerifyResponse = {
  as_of?: unknown;
  branch_id?: unknown;
  message?: unknown;
  notes?: unknown;
};

/** Response of `GET /api/ledger/accounts` (from live captures). */
export type GetLedgerAccountsResponse = {
  success: boolean;
  data: {
    code: string;
    name: string;
    name_en: string;
    type: string;
    normal_balance: string;
    is_postable: boolean;
  }[];
};

/** Query of `GET /api/ledger/entries` (from the backend validation rules). */
export type GetLedgerEntriesQuery = {
  from?: string;
  period?: string;
  to?: string;
};

/** Response of `GET /api/ledger/entries` (from live captures). */
export type GetLedgerEntriesResponse = {
  success: boolean;
  data: {
    id: number;
    entry_no: string;
    branch_id: number;
    entry_date: string;
    period: string;
    status: string;
    description: string;
    source: {
      type: string;
      id: number;
    } | null;
    reverses_entry_id: number | null;
    lines: {
      account: string;
      account_name: string;
      debit: string;
      credit: string;
      description: string;
    }[];
    total_debit: number;
    total_credit: number;
    from?: unknown;
    to?: unknown;
  }[];
};

/** Query of `GET /api/ledger/trial-balance` (from the backend validation rules). */
export type GetLedgerTrialBalanceQuery = {
  branch_id?: number;
  from?: string;
  up_to: string;
};

/** Response of `GET /api/ledger/trial-balance` (from live captures). */
export type GetLedgerTrialBalanceResponse = {
  success: boolean;
  data: {
    branch_id: number;
    from: string;
    up_to: string;
    rows: {
      code: string;
      name: string;
      name_en: string;
      type: string;
      debit: string;
      credit: string;
      balance: string;
    }[];
    totals: {
      debit: string;
      credit: string;
      balanced: boolean;
    };
  };
};

/** Body of `POST /api/ledger/entries` (from the backend validation rules). */
export type PostLedgerEntriesBody = {
  branch_id?: number;
  description?: string;
  entry_date: string;
  lines: {
    account: string;
    credit?: string | number;
    debit?: string | number;
    description?: string;
  }[];
};

/** Response of `POST /api/ledger/entries` (no capture: keys from backend code only). */
export type PostLedgerEntriesResponse = {
  account?: unknown;
  account_name?: unknown;
  branch_id?: unknown;
  credit?: unknown;
  debit?: unknown;
  description?: unknown;
  entry_date?: unknown;
  entry_no?: unknown;
  id?: unknown;
  lines?: unknown;
  message?: unknown;
  period?: unknown;
  reverses_entry_id?: unknown;
  source?: unknown;
  status?: unknown;
  total_credit?: unknown;
  total_debit?: unknown;
  type?: unknown;
};

/** Body of `POST /api/ledger/entries/{entry}/reverse` (from the backend validation rules). */
export type PostLedgerEntriesEntryReverseBody = {
  reason?: string;
};

/** Response of `POST /api/ledger/entries/{entry}/reverse` (from live captures). */
export type PostLedgerEntriesEntryReverseResponse = {
  success: boolean;
  message: string;
  data: {
    id: number;
    entry_no: string;
    branch_id: number;
    entry_date: string;
    period: string;
    status: string;
    description: string;
    source: null;
    reverses_entry_id: number;
    lines: {
      account: string;
      account_name: string;
      debit: string;
      credit: string;
      description: string;
    }[];
    total_debit: number;
    total_credit: number;
    reason?: unknown;
    type?: unknown;
  };
};

/** Body of `POST /api/ledger/post-day` (from the backend validation rules). */
export type PostLedgerPostDayBody = {
  branch_id?: number;
  business_date: string;
};

/** Response of `POST /api/ledger/post-day` (from live captures). */
export type PostLedgerPostDayResponse = {
  success: boolean;
  message: string;
  data: {
    branch_id: number;
    business_date: string;
    posted: {
      sales: number;
      collections: number;
      expenses: number;
      goods_receipts: number;
      fridge_deposits: number;
    };
  };
};

/** Body of `POST /api/ledger/close-period` (from the backend validation rules). */
export type PostLedgerClosePeriodBody = {
  branch_id?: number;
  notes?: string;
  period: string;
};

/** Response of `POST /api/ledger/close-period` (no capture: keys from backend code only). */
export type PostLedgerClosePeriodResponse = {
  branch_id?: unknown;
  closed_at?: unknown;
  message?: unknown;
  notes?: unknown;
  period?: unknown;
  status?: unknown;
};
