// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/maintenance/faults` (from the backend validation rules). */
export type GetMaintenanceFaultsQuery = {
  from?: string;
  status?: string;
  to?: string;
};

/** Response of `GET /api/maintenance/faults` (from live captures). */
export type GetMaintenanceFaultsResponse = {
  success: boolean;
  data: {
    id: number;
    type: string;
    severity: string;
    business_date: string;
    message: string;
    subject: {
      type: string;
      id: number;
    };
    status: string;
    from?: unknown;
    to?: unknown;
  }[];
  summary: {
    open: number;
    critical: number;
  };
};
