// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/products` (from the backend validation rules). */
export type GetProductsQuery = {
  category?: string;
  is_active?: boolean;
  per_page?: number;
  q?: string;
};

/** Response of `GET /api/products` (from live captures). */
export type GetProductsResponse = {
  success: boolean;
  data: {
    id: number;
    code: string;
    name: string;
    category: string | null;
    barcode: string;
    salesbuzz_code: string;
    unit_cost: string;
    trade_price: string;
    units_per_carton: number;
    cold_chain: {
      shelf_life_days: number;
      storage_temp_min: string;
      storage_temp_max: string;
    };
    is_active: boolean;
    q?: unknown;
  }[];
  meta: {
    total: number;
    per_page: number;
    current_page: number;
    last_page: number;
  };
};

/** Body of `POST /api/products` (from the backend validation rules). */
export type PostProductsBody = {
  barcode?: string;
  category?: string;
  code?: string;
  is_active?: boolean;
  name?: string;
  salesbuzz_code?: string;
  shelf_life_days?: number;
  storage_temp_max?: string | number;
  storage_temp_min?: string | number;
  trade_price?: string | number;
  unit_cost?: string | number;
  units_per_carton?: string;
};

/** Response of `POST /api/products` (no capture: keys from backend code only). */
export type PostProductsResponse = {
  barcode?: unknown;
  category?: unknown;
  code?: unknown;
  cold_chain?: unknown;
  id?: unknown;
  is_active?: unknown;
  message?: unknown;
  name?: unknown;
  salesbuzz_code?: unknown;
  shelf_life_days?: unknown;
  storage_temp_max?: unknown;
  storage_temp_min?: unknown;
  trade_price?: unknown;
  unit_cost?: unknown;
  units_per_carton?: unknown;
};

/** Body of `POST /api/products/details` (from the backend validation rules). */
export type PostProductsDetailsBody = {
  commit?: boolean;
  rows: {
    barcode?: string;
    category?: string;
    code: string;
    salesbuzz_code?: string;
    shelf_life_days?: number;
    storage_temp_max?: string | number;
    storage_temp_min?: string | number;
    units_per_carton?: number;
  }[];
};

/** Response of `POST /api/products/details` (no capture: keys from backend code only). */
export type PostProductsDetailsResponse = {
  commit?: unknown;
  rows?: unknown;
};

/** Query of `GET /api/products/units/pending` (from the backend validation rules). */
export type GetProductsUnitsPendingQuery = {
  category?: string;
  q?: string;
};

/** Response of `GET /api/products/units/pending` (from live captures). */
export type GetProductsUnitsPendingResponse = {
  success: boolean;
  data: unknown[];
  summary: {
    pending: number;
    total_active: number;
  };
  category?: unknown;
  code?: unknown;
  id?: unknown;
  name?: unknown;
  q?: unknown;
  units_per_carton?: unknown;
};

/** Body of `PATCH /api/products/{product}` (from the backend validation rules). */
export type PatchProductsProductBody = {
  barcode?: string;
  category?: string;
  code?: string;
  is_active?: boolean;
  name?: string;
  salesbuzz_code?: string;
  shelf_life_days?: number;
  storage_temp_max?: string | number;
  storage_temp_min?: string | number;
  trade_price?: string | number;
  unit_cost?: string | number;
  units_per_carton?: string;
};

/** Response of `PATCH /api/products/{product}` (from live captures). */
export type PatchProductsProductResponse = {
  success: boolean;
  message: string;
  data: {
    id: number;
    code: string;
    name: string;
    category: null;
    barcode: string;
    salesbuzz_code: string;
    unit_cost: string;
    trade_price: string;
    units_per_carton: number;
    cold_chain: {
      shelf_life_days: number;
      storage_temp_min: string;
      storage_temp_max: string;
    };
    is_active: boolean;
  };
};

/** Response of `GET /api/products/{product}/prices` (from live captures). */
export type GetProductsProductPricesResponse = {
  success: boolean;
  data: {
    product: {
      id: number;
      code: string;
      name: string;
    };
    prices: {
      id: number;
      price: string;
      effective_from: string;
      effective_to: null;
      is_active: boolean;
    }[];
  };
};

/** Body of `POST /api/products/{product}/prices` (from the backend validation rules). */
export type PostProductsProductPricesBody = {
  effective_from: string;
  effective_to?: string;
  is_active?: boolean;
  price: string | number;
};

/** Response of `POST /api/products/{product}/prices` (no capture: keys from backend code only). */
export type PostProductsProductPricesResponse = {
  effective_from?: unknown;
  effective_to?: unknown;
  id?: unknown;
  is_active?: unknown;
  message?: unknown;
  price?: unknown;
};

/** Body of `POST /api/products/{product}/prices/{price}/end` (from the backend validation rules). */
export type PostProductsProductPricesPriceEndBody = {
  effective_to: string;
};

/** Response of `POST /api/products/{product}/prices/{price}/end` (no capture: keys from backend code only). */
export type PostProductsProductPricesPriceEndResponse = {
  effective_from?: unknown;
  effective_to?: unknown;
  id?: unknown;
  message?: unknown;
  price?: unknown;
};
