// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Response of `GET /api/refrigerator-stocktakes` (from live captures). */
export type GetRefrigeratorStocktakesResponse = {
  success: boolean;
  data: {
    id: number;
    stocktake_no: string;
    business_date: string;
    period_type: string;
    status: string;
  }[];
};

/** Response of `GET /api/refrigerator-stocktakes/{stocktake}` (from live captures). */
export type GetRefrigeratorStocktakesStocktakeResponse = {
  success: boolean;
  data: {
    id: number;
    stocktake_no: string;
    branch_id: number;
    business_date: string;
    period_type: string;
    status: string;
    counted_by: string;
    reviewed_by: null;
    reviewed_at: null;
    summary: {
      total: number;
      not_counted_yet: number;
      matched: number;
      state_differs: number;
      not_found: number;
    };
    by_expected_status: {
      WITH_CUSTOMER: number;
      IN_STORE: number;
    };
    items: {
      refrigerator_id: number;
      code: string;
      expected_status: string;
      expected_at: string | null;
      found_status: null;
      verdict: null;
      counted: boolean;
      notes: null;
    }[];
  };
};

/** Body of `POST /api/refrigerator-stocktakes` (from the backend validation rules). */
export type PostRefrigeratorStocktakesBody = {
  branch_id?: number;
  business_date?: string;
  period_type?: string;
};

/** Response of `POST /api/refrigerator-stocktakes` (from live captures). */
export type PostRefrigeratorStocktakesResponse = {
  success: boolean;
  message: string;
  data: {
    id: number;
    stocktake_no: string;
    branch_id: number;
    business_date: string;
    period_type: string;
    status: string;
    counted_by: string;
    reviewed_by: null;
    reviewed_at: null;
    summary: {
      total: number;
      not_counted_yet: number;
      matched: number;
      state_differs: number;
      not_found: number;
    };
    by_expected_status: {
      WITH_CUSTOMER: number;
      IN_STORE: number;
    };
    items: {
      refrigerator_id: number;
      code: string;
      expected_status: string;
      expected_at: string | null;
      found_status: null;
      verdict: null;
      counted: boolean;
      notes: null;
    }[];
  };
};

/** Body of `POST /api/refrigerator-stocktakes/{stocktake}/items` (from the backend validation rules). */
export type PostRefrigeratorStocktakesStocktakeItemsBody = {
  found_status?: string;
  notes?: string;
  refrigerator_id: number;
};

/** Response of `POST /api/refrigerator-stocktakes/{stocktake}/items` (no capture: keys from backend code only). */
export type PostRefrigeratorStocktakesStocktakeItemsResponse = {
  found_status?: unknown;
  notes?: unknown;
  refrigerator_id?: unknown;
  verdict?: unknown;
};

/** Body of `POST /api/refrigerator-stocktakes/{stocktake}/review` (from the backend validation rules). */
export type PostRefrigeratorStocktakesStocktakeReviewBody = {
  notes?: string;
};

/** Response of `POST /api/refrigerator-stocktakes/{stocktake}/review` (no capture: keys from backend code only). */
export type PostRefrigeratorStocktakesStocktakeReviewResponse = {
  message?: unknown;
  notes?: unknown;
};

/** Query of `GET /api/refrigerators/maintenance/due` (from the backend validation rules). */
export type GetRefrigeratorsMaintenanceDueQuery = {
  branch_id?: number;
  within_days?: number;
};

/** Response of `GET /api/refrigerators/maintenance/due` (from live captures). */
export type GetRefrigeratorsMaintenanceDueResponse = {
  success: boolean;
  data: unknown[];
  branch_id?: unknown;
  within_days?: unknown;
};

/** Query of `GET /api/refrigerators/{refrigerator}/file` (from the backend validation rules). */
export type GetRefrigeratorsRefrigeratorFileQuery = {
  from?: string;
  to?: string;
};

/** Response of `GET /api/refrigerators/{refrigerator}/file` (from live captures). */
export type GetRefrigeratorsRefrigeratorFileResponse = {
  success: boolean;
  data: {
    refrigerator: {
      id: number;
      code: string;
      type: string;
      model: string;
      capacity: string;
      status: string;
      is_active: boolean;
    };
    period: {
      from: string;
      to: string;
    };
    placements: unknown[];
    costs: {
      by_category: unknown[];
      total: string;
      entry_count: number;
    };
    service_history: unknown[];
    next_due: null;
    last_counted: null;
  };
};

/** Body of `POST /api/refrigerators/maintenance` (from the backend validation rules). */
export type PostRefrigeratorsMaintenanceBody = {
  description?: string;
  document_no?: string;
  expense_id?: number;
  next_service_due_on?: string;
  notes?: string;
  parts?: {
    notes?: string;
    part_name: string;
    quantity?: string | number;
    unit_cost?: string | number;
  }[];
  performed_on?: string;
  refrigerator_id: number;
  restored_to_service?: boolean;
  type: string;
  workshop?: string;
};

/** Response of `POST /api/refrigerators/maintenance` (no capture: keys from backend code only). */
export type PostRefrigeratorsMaintenanceResponse = {
  description?: unknown;
  document_no?: unknown;
  expense_id?: unknown;
  id?: unknown;
  message?: unknown;
  next_service_due_on?: unknown;
  notes?: unknown;
  parts?: unknown;
  parts_total?: unknown;
  performed_on?: unknown;
  refrigerator_id?: unknown;
  restored_to_service?: unknown;
  service_no?: unknown;
  type?: unknown;
  workshop?: unknown;
};

/** Query of `GET /api/refrigerators` (from the backend validation rules). */
export type GetRefrigeratorsQuery = {
  customer_id?: number;
  is_active?: boolean;
  q?: string;
  status?: string;
};

/** Response of `GET /api/refrigerators` (from live captures). */
export type GetRefrigeratorsResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    code: string;
    type: string;
    model: string;
    capacity: string;
    status: string;
    is_active: boolean;
    notes: null;
    with_customer: {
      customer_id: number;
      customer: string;
      placed_on: string;
      deposit_amount: string;
    } | null;
    q?: unknown;
  }[];
};

/** Response of `GET /api/refrigerators/{refrigerator}` (from live captures). */
export type GetRefrigeratorsRefrigeratorResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    code: string;
    type: string;
    model: string;
    capacity: string;
    status: string;
    is_active: boolean;
    notes: null;
    with_customer: null;
    placements: {
      id: number;
      refrigerator_id: number;
      refrigerator_code: string;
      customer_id: number;
      customer: string;
      supervisor: string;
      placed_on: string;
      deposit_amount: string;
      returned_on: string;
      refund_amount: string;
      is_open: boolean;
      notes: string;
    }[];
  };
};

/** Body of `POST /api/refrigerators` (from the backend validation rules). */
export type PostRefrigeratorsBody = {
  branch_id?: number;
  capacity?: string;
  code: string;
  model?: string;
  notes?: string;
  status?: string;
  type?: string;
};

/** Response of `POST /api/refrigerators` (no capture: keys from backend code only). */
export type PostRefrigeratorsResponse = {
  branch_id?: unknown;
  capacity?: unknown;
  code?: unknown;
  customer?: unknown;
  customer_id?: unknown;
  deposit_amount?: unknown;
  id?: unknown;
  is_active?: unknown;
  message?: unknown;
  model?: unknown;
  notes?: unknown;
  placed_on?: unknown;
  status?: unknown;
  type?: unknown;
  with_customer?: unknown;
};

/** Body of `PATCH /api/refrigerators/{refrigerator}` (from the backend validation rules). */
export type PatchRefrigeratorsRefrigeratorBody = {
  capacity?: string;
  code?: string;
  is_active?: boolean;
  model?: string;
  notes?: string;
  status?: string;
  type?: string;
};

/** Response of `PATCH /api/refrigerators/{refrigerator}` (no capture: keys from backend code only). */
export type PatchRefrigeratorsRefrigeratorResponse = {
  branch_id?: unknown;
  capacity?: unknown;
  code?: unknown;
  customer?: unknown;
  customer_id?: unknown;
  deposit_amount?: unknown;
  id?: unknown;
  is_active?: unknown;
  message?: unknown;
  model?: unknown;
  notes?: unknown;
  placed_on?: unknown;
  status?: unknown;
  type?: unknown;
  with_customer?: unknown;
};

/** Body of `POST /api/refrigerators/{refrigerator}/place` (from the backend validation rules). */
export type PostRefrigeratorsRefrigeratorPlaceBody = {
  customer_id: number;
  deposit_amount: string | number;
  notes?: string;
  placed_on: string;
  supervisor_id?: number;
};

/** Response of `POST /api/refrigerators/{refrigerator}/place` (no capture: keys from backend code only). */
export type PostRefrigeratorsRefrigeratorPlaceResponse = {
  customer?: unknown;
  customer_id?: unknown;
  deposit_amount?: unknown;
  id?: unknown;
  is_open?: unknown;
  message?: unknown;
  notes?: unknown;
  placed_on?: unknown;
  refrigerator_code?: unknown;
  refrigerator_id?: unknown;
  refund_amount?: unknown;
  returned_on?: unknown;
  supervisor?: unknown;
  supervisor_id?: unknown;
};

/** Body of `POST /api/refrigerators/{refrigerator}/collect` (from the backend validation rules). */
export type PostRefrigeratorsRefrigeratorCollectBody = {
  notes?: string;
  refund_amount: string | number;
  returned_on: string;
  status?: string;
};

/** Response of `POST /api/refrigerators/{refrigerator}/collect` (from live captures). */
export type PostRefrigeratorsRefrigeratorCollectResponse = {
  success: boolean;
  message: string;
  data: {
    id: number;
    refrigerator_id: number;
    refrigerator_code: string;
    customer_id: number;
    customer: string;
    supervisor: string;
    placed_on: string;
    deposit_amount: string;
    returned_on: string;
    refund_amount: string;
    is_open: boolean;
    notes: string;
    status?: unknown;
  };
};
