// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Response of `GET /api/reports` (from live captures). */
export type GetReportsResponse = {
  success: boolean;
  summary: {
    count: number;
    branch_required: boolean;
  };
  data: {
    key: string;
    title_ar: string;
    title_en: string;
    reports: {
      key: string;
      method: string;
      path: string;
      title_ar: string;
      title_en: string;
      required: string[];
      optional: string[];
      branch_scoped: boolean;
    }[];
  }[];
};

/** Query of `GET /api/alerts` (from the backend validation rules). */
export type GetAlertsQuery = {
  business_date?: string;
  severity?: string;
  status?: string;
};

/** Response of `GET /api/alerts` (from live captures). */
export type GetAlertsResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    type: string;
    severity: string;
    business_date: string;
    message: string;
    subject: {
      type: string;
      id: number;
    };
    status: string;
    acknowledged_by: string | null;
    acknowledged_at: string | null;
    notes: null;
  }[];
  summary: {
    open: number;
    critical: number;
  };
};

/** Body of `POST /api/alerts/sweep` (from the backend validation rules). */
export type PostAlertsSweepBody = {
  branch_id?: number;
  business_date?: string;
};

/** Response of `POST /api/alerts/sweep` (from live captures). */
export type PostAlertsSweepResponse = {
  success: boolean;
  message: string;
  data: {
    raised: number;
    open: number;
    branch_id?: unknown;
    business_date?: unknown;
  };
};

/** Body of `POST /api/alerts/{alert}/acknowledge` (from the backend validation rules). */
export type PostAlertsAlertAcknowledgeBody = {
  notes?: string;
};

/** Response of `POST /api/alerts/{alert}/acknowledge` (from live captures). */
export type PostAlertsAlertAcknowledgeResponse = {
  success: boolean;
  message: string;
  data: {
    id: number;
    branch_id: number;
    type: string;
    severity: string;
    business_date: string;
    message: string;
    subject: {
      type: string;
      id: number;
    };
    status: string;
    acknowledged_by: string;
    acknowledged_at: string;
    notes: null;
  };
};

/** Query of `GET /api/reports/sales-performance` (from the backend validation rules). */
export type GetReportsSalesPerformanceQuery = {
  as_of?: string;
  branch_id?: number;
  period_end: string;
  period_start: string;
};

/** Response of `GET /api/reports/sales-performance` (from live captures). */
export type GetReportsSalesPerformanceResponse = {
  success: boolean;
  data: {
    branch_id: number;
    period_start: string;
    period_end: string;
    as_of: string;
    last_working_day: string;
    working_days: number;
    working_days_elapsed: number;
    working_days_remaining: number;
    time_gone_percent: null;
    rows: unknown[];
    totals: {
      nps_target: number;
      nps_actual: number;
      nps_percent: null;
      invoice_target: number;
      invoice_actual: number;
      invoice_percent: null;
      new_customers: number;
      drop_size: number;
    };
  };
};

/** Query of `GET /api/reports/team-performance` (from the backend validation rules). */
export type GetReportsTeamPerformanceQuery = {
  as_of?: string;
  period_end: string;
  period_start: string;
};

/** Response of `GET /api/reports/team-performance` (from live captures). */
export type GetReportsTeamPerformanceResponse = {
  success: boolean;
  data: {
    branch_id: number;
    period_start: string;
    period_end: string;
    as_of: string;
    last_working_day: string;
    working_days: number;
    working_days_elapsed: number;
    working_days_remaining: number;
    time_gone_percent: null;
    rows: unknown[];
    totals: {
      nps_target: number;
      nps_actual: number;
      nps_percent: null;
      invoice_target: number;
      invoice_actual: number;
      invoice_percent: null;
      new_customers: number;
      drop_size: number;
    };
    team_size: number;
  };
};

/** Query of `GET /api/reports/sales-by-channel` (from the backend validation rules). */
export type GetReportsSalesByChannelQuery = {
  branch_id?: number;
  business_date?: string;
  salesman_id?: number;
};

/** Response of `GET /api/reports/sales-by-channel` (from live captures). */
export type GetReportsSalesByChannelResponse = {
  success: boolean;
  data: {
    branch_id: number;
    business_date: string;
    salesman_id: null;
    rows: {
      code: string;
      name_ar: string;
      name_en: string;
      is_active: boolean;
      invoice_count: number;
      customer_count: number;
      sales_amount: string;
      cash_amount: string;
      credit_amount: string;
      tpp_amount: string;
      discount_amount: string;
    }[];
    totals: {
      invoice_count: number;
      customer_count: number;
      sales_amount: string;
      cash_amount: string;
      credit_amount: string;
      tpp_amount: string;
      discount_amount: string;
    };
  };
};

/** Query of `GET /api/audit/master-data-changes` (from the backend validation rules). */
export type GetAuditMasterDataChangesQuery = {
  changed_by?: number;
  field?: string;
  from?: string;
  page?: string;
  per_page?: string;
  subject_id?: number;
  subject_type?: string;
  to?: string;
};

/** Response of `GET /api/audit/master-data-changes` (from live captures). */
export type GetAuditMasterDataChangesResponse = {
  success: boolean;
  data: unknown[];
  meta: {
    total: number;
    per_page: number;
    current_page: number;
    last_page: number;
  };
  branch_id?: unknown;
  changed_at?: unknown;
  changed_by?: unknown;
  field?: unknown;
  id?: unknown;
  name?: unknown;
  new_value?: unknown;
  old_value?: unknown;
  subject_id?: unknown;
  subject_name?: unknown;
  subject_type?: unknown;
};

/** Query of `GET /api/reports/stock-balances` (from the backend validation rules). */
export type GetReportsStockBalancesQuery = {
  branch_id?: number;
  category?: string;
  include_retired?: boolean;
};

/** Response of `GET /api/reports/stock-balances` (from live captures). */
export type GetReportsStockBalancesResponse = {
  success: boolean;
  data: {
    branch_id: number;
    as_of: string;
    valued_at: string;
    rows: {
      product_id: number;
      category: string | null;
      code: string;
      name: string;
      trade_price: string;
      warehouse_cartons: number;
      warehouse_value: string;
      vehicle_cartons: number;
      vehicle_value: string;
      total_cartons: number;
      total_value: string;
      total_value_at_cost: string;
    }[];
    totals: {
      products: number;
      warehouse_cartons: number;
      warehouse_value: string;
      vehicle_cartons: number;
      vehicle_value: string;
      total_cartons: number;
      total_value: string;
      total_value_at_cost: string;
    };
    include_retired?: unknown;
  };
};

/** Query of `GET /api/reports/expenses` (from the backend validation rules). */
export type GetReportsExpensesQuery = {
  branch_id?: number;
  period_end: string;
  period_start: string;
};

/** Response of `GET /api/reports/expenses` (from live captures). */
export type GetReportsExpensesResponse = {
  success: boolean;
  data: {
    branch_id: number;
    period_start: string;
    period_end: string;
    includes: string;
    accounts: {
      id: number;
      code: string;
      name: string;
      name_en: string;
      scope: string;
      total: string;
    }[];
    days: {
      date: string;
      accounts: {
        "32"?: string;
        "23"?: string;
        "31"?: string;
        "3"?: string;
        "24"?: string;
        "12"?: string;
        "10"?: string;
      };
      total: string;
    }[];
    totals: {
      expenses: number;
      total: string;
      on_trips: string;
      branch_only: string;
    };
  };
};

/** Query of `GET /api/reports/product-sales` (from the backend validation rules). */
export type GetReportsProductSalesQuery = {
  branch_id?: number;
  category?: string;
  channel?: string;
  limit?: number;
  period_end: string;
  period_start: string;
  salesman_id?: number;
  sort?: string;
};

/** Response of `GET /api/reports/product-sales` (from live captures). */
export type GetReportsProductSalesResponse = {
  success: boolean;
  data: {
    branch_id: number;
    period_start: string;
    period_end: string;
    compared_with: {
      period_start: string;
      period_end: string;
    };
    sorted_by: string;
    totals: {
      products_sold: number;
      cartons: number;
      pieces: number;
      bonus_cartons: number;
      sales_amount: string;
    };
    rows: {
      product_id: number;
      code: string;
      name: string;
      category: string | null;
      cartons: number;
      pieces: number;
      bonus_cartons: number;
      sales_amount: string;
      share_percent: number;
      invoices: number;
      customers: number;
      previous_cartons: number;
      previous_sales_amount: string;
      change_percent: number;
    }[];
    channel?: unknown;
    limit?: unknown;
    salesman_id?: unknown;
    sort?: unknown;
  };
};

/** Query of `GET /api/reports/stock-cover` (from the backend validation rules). */
export type GetReportsStockCoverQuery = {
  as_of?: string;
  branch_id?: number;
  category?: string;
  days?: number;
  include_retired?: boolean;
  low_days?: number;
};

/** Response of `GET /api/reports/stock-cover` (from live captures). */
export type GetReportsStockCoverResponse = {
  success: boolean;
  data: {
    branch_id: number;
    as_of: string;
    window_days: number;
    window_start: string;
    low_days: number;
    summary: {
      OUT: number;
      LOW: number;
      DEAD: number;
      OK: number;
    };
    rows: {
      product_id: number;
      code: string;
      name: string;
      category: string | null;
      warehouse_cartons: number;
      vehicle_cartons: number;
      total_cartons: number;
      cartons_out: number;
      pieces_out: number;
      cartons_per_day: number;
      days_of_cover: number;
      status: string;
    }[];
    days?: unknown;
    include_retired?: unknown;
  };
};

/** Query of `GET /api/reports/supervisors` (from the backend validation rules). */
export type GetReportsSupervisorsQuery = {
  as_of?: string;
  branch_id?: number;
  period_end: string;
  period_start: string;
};

/** Response of `GET /api/reports/supervisors` (from live captures). */
export type GetReportsSupervisorsResponse = {
  success: boolean;
  data: {
    branch_id: number;
    period_start: string;
    period_end: string;
    team_as_of: string;
    rows: {
      supervisor_id: number;
      supervisor: string;
      is_assigned: boolean;
      reps: number;
      reps_who_sold: number;
      target_amount: string;
      sales_amount: string;
      own_target_amount: null;
      own_achievement_percent: null;
      remaining_amount: string;
      achievement_percent: null;
      invoice_target: number;
      invoices: number;
      customers: number;
      drop_size: string;
    }[];
    totals: {
      supervisors: number;
      reps: number;
      target_amount: string;
      sales_amount: string;
      achievement_percent: null;
      invoice_target: number;
      invoices: number;
      customers: number;
      drop_size: string;
    };
    as_of?: unknown;
  };
};

/** Query of `GET /api/reports/treasury-sheet` (from the backend validation rules). */
export type GetReportsTreasurySheetQuery = {
  branch_id?: number;
  business_date: string;
};

/** Response of `GET /api/reports/treasury-sheet` (from live captures). */
export type GetReportsTreasurySheetResponse = {
  success: boolean;
  data: {
    branch_id: number;
    business_date: string;
    day: {
      status: string;
      counted_amount: null;
      expected_amount: null;
      count_variance_amount: string;
      closed_at: null;
    };
    rows: {
      handover_id: number;
      handover_no: string;
      salesman_id: number;
      salesman: string;
      routes: {
        id: number;
        code: string;
        name: string;
      }[];
      handheld_invoice_total: string | null;
      salesbuzz_invoice_total: null;
      source_variance_amount: null;
      credit_total: string;
      expenses_amount: string;
      opening_shortage_amount: string;
      tpp_amount: string | null;
      commission_amount: null;
      price_difference_amount: null;
      expected_amount: string;
      received_amount: string | null;
      shortage_amount: string;
      excess_amount: string;
      collections: {
        cash: string;
        cheque: string;
        transfer: string;
        card: string;
      };
      status: string;
      confirmed_at: string | null;
    }[];
    totals: {
      handheld_invoice_total: string;
      credit_total: string;
      expenses_amount: string;
      expected_amount: string;
      received_amount: string;
      shortage_amount: string;
      excess_amount: string;
      collections: {
        cash: string;
        cheque: string;
        transfer: string;
        card: string;
      };
      salesbuzz_compared_trips: number;
      source_variance_amount: null;
    };
    unavailable_columns: string[];
  };
};
