// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Body of `POST /api/customer-returns` (from the backend validation rules). */
export type PostCustomerReturnsBody = {
  customer_visit_id: number;
  items: {
    notes?: string;
    original_sale_item_id?: number;
    product_id: number;
    quantity_cartons: number;
  }[];
  notes?: string;
  original_sale_id?: number;
  reason: string;
  requested_action: string;
};

/** Response of `POST /api/customer-returns` (no capture: keys from backend code only). */
export type PostCustomerReturnsResponse = {
  message?: unknown;
};

/** Query of `GET /api/customer-returns` (from the backend validation rules). */
export type GetCustomerReturnsQuery = {
  customer_id?: number;
  daily_session_id?: number;
  from?: string;
  page?: string;
  per_page?: string;
  reason?: string;
  salesman_id?: number;
  status?: string;
  to?: string;
};

/** Response of `GET /api/customer-returns` (from live captures). */
export type GetCustomerReturnsResponse = {
  success: boolean;
  data: {
    id: number;
    return_no: string;
    branch_id: number;
    daily_session_id: number;
    customer: {
      id: number;
      customer_code: string;
      name: string;
    };
    salesman: {
      id: number;
      name: string;
    };
    reason: string;
    requested_action: string;
    status: string;
    line_count: number;
    returned_at: string;
    customer_id?: unknown;
    salesman_id?: unknown;
  }[];
  meta: {
    total: number;
    per_page: number;
    current_page: number;
    last_page: number;
  };
};

/** Response of `GET /api/customer-returns/{customerReturn}` (from live captures). */
export type GetCustomerReturnsCustomerReturnResponse = {
  success: boolean;
  data: {
    id: number;
    return_no: string;
    branch_id: number;
    daily_session_id: number;
    customer: {
      id: number;
      customer_code: string;
      name: string;
    };
    salesman: {
      id: number;
      name: string;
    };
    reason: string;
    requested_action: string;
    status: string;
    line_count: number;
    returned_at: string;
    original_sale: null;
    lines: {
      id: number;
      product_id: number;
      product_code: string;
      product_name: string;
      quantity_cartons: number;
    }[];
    inspection: {
      id: number;
      status: string;
    };
    sale_no?: unknown;
    salesbuzz_invoice_no?: unknown;
  };
};

/** Body of `POST /api/return-inspections` (from the backend validation rules). */
export type PostReturnInspectionsBody = {
  customer_return_id: number;
  items: {
    allocations: {
      condition: string;
      notes?: string;
      quantity_cartons: number;
    }[];
    customer_return_item_id: number;
  }[];
  notes?: string;
  warehouse_id: number;
};

/** Response of `POST /api/return-inspections` (no capture: keys from backend code only). */
export type PostReturnInspectionsResponse = {
  message?: unknown;
};

/** Body of `POST /api/customer-replacements` (from the backend validation rules). */
export type PostCustomerReplacementsBody = {
  customer_return_id: number;
  notes?: string;
};

/** Response of `POST /api/customer-replacements` (no capture: keys from backend code only). */
export type PostCustomerReplacementsResponse = {
  message?: unknown;
};

/** Query of `GET /api/customer-replacements` (from the backend validation rules). */
export type GetCustomerReplacementsQuery = {
  customer_id?: number;
  customer_return_id?: number;
  daily_session_id?: number;
  from?: string;
  page?: string;
  per_page?: string;
  salesman_id?: number;
  source?: string;
  status?: string;
  to?: string;
};

/** Response of `GET /api/customer-replacements` (from live captures). */
export type GetCustomerReplacementsResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    daily_session_id: null;
    customer_return_id: number;
    customer: {
      id: number;
      customer_code: string;
      name: string;
    };
    salesman: {
      id: number;
      name: string;
    };
    status: string;
    line_count: number;
    created_at: string;
    customer_id?: unknown;
    salesman_id?: unknown;
    source?: unknown;
  }[];
  meta: {
    total: number;
    per_page: number;
    current_page: number;
    last_page: number;
  };
};

/** Response of `GET /api/customer-replacements/{customerReplacement}` (from live captures). */
export type GetCustomerReplacementsCustomerReplacementResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    daily_session_id: null;
    customer_return_id: number;
    customer: {
      id: number;
      customer_code: string;
      name: string;
    };
    salesman: {
      id: number;
      name: string;
    };
    status: string;
    line_count: number;
    created_at: string;
    customer_return: {
      id: number;
      return_no: string;
      reason: string;
    };
    lines: {
      id: number;
      customer_return_item_id: number;
      product_id: number;
      product_code: string;
      product_name: string;
      status: string;
      fulfillment_source: string;
      required_quantity_cartons: number;
      warehouse_issued_quantity_cartons: number;
      delivered_quantity_cartons: number;
      warehouse_id: number;
      warehouse: string;
      warehouse_issued_at: string;
      salesman_received_at: null;
      delivered_at: null;
    }[];
    progress: {
      lines: number;
      delivered: number;
      with_salesman: number;
      waiting_on_warehouse: number;
    };
  };
};

/** Response of `POST /api/customer-replacements/{customerReplacement}/deliver-immediate` (no capture: keys from backend code only). */
export type PostCustomerReplacementsCustomerReplacementDeliverImmediateResponse = {
  message?: unknown;
};

/** Body of `POST /api/customer-replacements/{customerReplacement}/prepare-from-warehouse` (from the backend validation rules). */
export type PostCustomerReplacementsCustomerReplacementPrepareFromWarehouseBody = {
  notes?: string;
  warehouse_id: number;
};

/** Response of `POST /api/customer-replacements/{customerReplacement}/prepare-from-warehouse` (from live captures). */
export type PostCustomerReplacementsCustomerReplacementPrepareFromWarehouseResponse = {
  message: string;
  data: {
    id: number;
    replacement_no: string;
    client_transaction_uuid: string;
    customer_return_id: number;
    created_session_id: number;
    branch_id: number;
    salesman_id: number;
    customer_id: number;
    created_by: number;
    status: string;
    completed_at: null;
    notes: null;
    created_at: string;
    updated_at: string;
    customer_return: {
      id: number;
      return_no: string;
      client_transaction_uuid: string;
      daily_session_id: number;
      customer_visit_id: number;
      branch_id: number;
      salesman_id: number;
      customer_id: number;
      original_sale_id: null;
      reason: string;
      requested_action: string;
      status: string;
      returned_at: string;
      notes: string;
      created_at: string;
      updated_at: string;
      items: {
        id: number;
        customer_return_id: number;
        product_id: number;
        original_sale_item_id: null;
        quantity_cartons: number;
        notes: null;
        created_at: string;
        updated_at: string;
        product: {
          id: number;
          code: string;
          name: string;
          category: string;
          unit_cost: string;
          trade_price: string;
          units_per_carton: number;
          barcode: string;
          salesbuzz_code: string;
          shelf_life_days: number;
          storage_temp_min: string;
          storage_temp_max: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
      }[];
    };
    customer: {
      id: number;
      branch_id: number;
      parent_customer_id: null;
      area_id: number;
      customer_code: string;
      salesbuzz_code: string;
      tax_registration_no: null;
      tax_rate: string;
      name: string;
      phone: string;
      address: string;
      customer_type: string;
      channel: string;
      discount_rate: string;
      payment_terms: string;
      billing_cycle: string;
      credit_limit: null;
      credit_days: null;
      latitude: string;
      longitude: string;
      notes: null;
      is_active: boolean;
      created_at: string;
      updated_at: string;
    };
    salesman: {
      id: number;
      branch_id: number;
      employee_code: string;
      name: string;
      phone: string;
      job_title: string;
      position_code: string;
      hire_date: string;
      is_active: boolean;
      created_at: string;
      updated_at: string;
    };
    items: {
      id: number;
      customer_replacement_id: number;
      customer_return_item_id: number;
      product_id: number;
      required_quantity_cartons: number;
      delivered_quantity_cartons: number;
      warehouse_issued_quantity_cartons: number;
      fulfillment_source: string;
      status: string;
      warehouse_id: number;
      delivery_customer_visit_id: null;
      warehouse_issued_by: number;
      warehouse_issued_at: string;
      salesman_received_at: null;
      delivered_at: null;
      notes: null;
      created_at: string;
      updated_at: string;
      product: {
        id: number;
        code: string;
        name: string;
        category: string;
        unit_cost: string;
        trade_price: string;
        units_per_carton: number;
        barcode: string;
        salesbuzz_code: string;
        shelf_life_days: number;
        storage_temp_min: string;
        storage_temp_max: string;
        is_active: boolean;
        created_at: string;
        updated_at: string;
      };
      warehouse: {
        id: number;
        branch_id: number;
        code: string;
        name: string;
        address: null;
        is_active: boolean;
        created_at: string;
        updated_at: string;
      };
      delivery_visit: null;
    }[];
  };
};

/** Response of `POST /api/customer-replacements/{customerReplacement}/confirm-warehouse-receipt` (no capture: keys from backend code only). */
export type PostCustomerReplacementsCustomerReplacementConfirmWarehouseReceiptResponse = {
  message?: unknown;
};

/** Body of `POST /api/customer-replacements/{customerReplacement}/deliver-warehouse` (from the backend validation rules). */
export type PostCustomerReplacementsCustomerReplacementDeliverWarehouseBody = {
  customer_visit_id: number;
  notes?: string;
};

/** Response of `POST /api/customer-replacements/{customerReplacement}/deliver-warehouse` (no capture: keys from backend code only). */
export type PostCustomerReplacementsCustomerReplacementDeliverWarehouseResponse = {
  message?: unknown;
};
