// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/routes` (from the backend validation rules). */
export type GetRoutesQuery = {
  is_active?: boolean;
  q?: string;
};

/** Response of `GET /api/routes` (from live captures). */
export type GetRoutesResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    code: string;
    name: string;
    description: string;
    stop_count: number;
    is_active: boolean;
    q?: unknown;
  }[];
};

/** Body of `POST /api/routes` (from the backend validation rules). */
export type PostRoutesBody = {
  branch_id?: number;
  code: string;
  description?: string;
  is_active?: boolean;
  name: string;
};

/** Response of `POST /api/routes` (no capture: keys from backend code only). */
export type PostRoutesResponse = {
  branch_id?: unknown;
  code?: unknown;
  description?: unknown;
  id?: unknown;
  is_active?: unknown;
  message?: unknown;
  name?: unknown;
};

/** Body of `PATCH /api/routes/{route}` (from the backend validation rules). */
export type PatchRoutesRouteBody = {
  branch_id?: number;
  code?: string;
  description?: string;
  is_active?: boolean;
  name?: string;
};

/** Response of `PATCH /api/routes/{route}` (no capture: keys from backend code only). */
export type PatchRoutesRouteResponse = {
  branch_id?: unknown;
  code?: unknown;
  description?: unknown;
  id?: unknown;
  is_active?: unknown;
  message?: unknown;
  name?: unknown;
};

/** Response of `GET /api/routes/{route}/round` (from live captures). */
export type GetRoutesRouteRoundResponse = {
  success: boolean;
  data: {
    route: {
      id: number;
      branch_id: number;
      code: string;
      name: string;
      description: string;
      is_active: boolean;
    };
    stops: unknown[];
    address?: unknown;
    customer_code?: unknown;
    customer_id?: unknown;
    visit_order?: unknown;
  };
};

/** Body of `PUT /api/routes/{route}/round` (from the backend validation rules). */
export type PutRoutesRouteRoundBody = {
  stops?: {
    customer_id: number;
    is_active?: boolean;
    visit_order?: number;
  }[];
};

/** Response of `PUT /api/routes/{route}/round` (from live captures). */
export type PutRoutesRouteRoundResponse = {
  success: boolean;
  data: {
    route: {
      id: number;
      branch_id: number;
      code: string;
      name: string;
      description: string;
      is_active: boolean;
    };
    stops: unknown[];
    address?: unknown;
    customer_code?: unknown;
    customer_id?: unknown;
    visit_order?: unknown;
  };
};

/** Response of `GET /api/routes/{route}/areas` (from live captures). */
export type GetRoutesRouteAreasResponse = {
  success: boolean;
  data: {
    route: {
      id: number;
      branch_id: number;
      code: string;
      name: string;
      description: string;
      is_active: boolean;
    };
    areas: unknown[];
  };
};

/** Body of `PUT /api/routes/{route}/areas` (from the backend validation rules). */
export type PutRoutesRouteAreasBody = {
  areas?: unknown[] | Record<string, unknown>;
};

/** Response of `PUT /api/routes/{route}/areas` (from live captures). */
export type PutRoutesRouteAreasResponse = {
  success: boolean;
  data: {
    route: {
      id: number;
      branch_id: number;
      code: string;
      name: string;
      description: string;
      is_active: boolean;
    };
    areas: unknown[];
  };
};

/** Response of `GET /api/routes/{route}/assignments` (from live captures). */
export type GetRoutesRouteAssignmentsResponse = {
  success: boolean;
  data: {
    id: number;
    salesman_id: number;
    salesman: string;
    start_date: string;
    end_date: string;
    is_active: boolean;
  }[];
};

/** Body of `POST /api/routes/{route}/assignments` (from the backend validation rules). */
export type PostRoutesRouteAssignmentsBody = {
  end_date?: string;
  salesman_id: number;
  start_date: string;
};

/** Response of `POST /api/routes/{route}/assignments` (no capture: keys from backend code only). */
export type PostRoutesRouteAssignmentsResponse = {
  end_date?: unknown;
  id?: unknown;
  message?: unknown;
  salesman_id?: unknown;
  start_date?: unknown;
};

/** Body of `POST /api/routes/{route}/assignments/{assignment}/end` (from the backend validation rules). */
export type PostRoutesRouteAssignmentsAssignmentEndBody = {
  end_date: string;
};

/** Response of `POST /api/routes/{route}/assignments/{assignment}/end` (from live captures). */
export type PostRoutesRouteAssignmentsAssignmentEndResponse = {
  success: boolean;
  message: string;
  data: {
    id: number;
    salesman_id: number;
    start_date: string;
    end_date: string;
  };
};
