// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Body of `POST /api/sync/push` (from the backend validation rules). */
export type PostSyncPushBody = {
  actions: {
    payload?: unknown[] | Record<string, unknown>;
    type: string;
  }[];
};

/** Response of `POST /api/sync/push` (no capture: keys from backend code only). */
export type PostSyncPushResponse = {
  actions?: unknown;
  message?: unknown;
};

/** Body of `POST /api/customer-visits` (from the backend validation rules). */
export type PostCustomerVisitsBody = {
  customer_id: number;
  daily_session_id: number;
  latitude?: string | number;
  longitude?: string | number;
  notes?: string;
};

/** Response of `POST /api/customer-visits` (no capture: keys from backend code only). */
export type PostCustomerVisitsResponse = {
  message?: unknown;
};

/** Response of `POST /api/customer-visits/{customerVisit}/complete` (no capture: keys from backend code only). */
export type PostCustomerVisitsCustomerVisitCompleteResponse = {
  message?: unknown;
};

/** Query of `GET /api/customer-visits` (from the backend validation rules). */
export type GetCustomerVisitsQuery = {
  customer_id?: number;
  daily_session_id?: number;
  from?: string;
  page?: string;
  per_page?: string;
  salesman_id?: number;
  status?: string;
  to?: string;
};

/** Response of `GET /api/customer-visits` (from live captures). */
export type GetCustomerVisitsResponse = {
  success: boolean;
  data: {
    id: number;
    visit_no: string;
    daily_session_id: number;
    customer: {
      id: number;
      customer_code: string;
      name: string;
    };
    salesman: {
      id: number;
      name: string;
    };
    status: string;
    no_sale_reason: null;
    sales_count: number;
    collections_count: number;
    returns_count: number;
    started_at: string;
    completed_at: string | null;
    customer_id?: unknown;
    salesman_id?: unknown;
  }[];
  meta: {
    total: number;
    per_page: number;
    current_page: number;
    last_page: number;
  };
};

/** Response of `GET /api/customer-visits/{customerVisit}` (from live captures). */
export type GetCustomerVisitsCustomerVisitResponse = {
  success: boolean;
  data: {
    id: number;
    visit_no: string;
    daily_session_id: number;
    customer: {
      id: number;
      customer_code: string;
      name: string;
    };
    salesman: {
      id: number;
      name: string;
    };
    status: string;
    no_sale_reason: null;
    sales_count: number;
    collections_count: number;
    returns_count: number;
    started_at: string;
    completed_at: string;
    session: {
      id: number;
      session_no: string;
      business_date: string;
      route_id: number;
    };
    start_latitude: null;
    start_longitude: null;
    notes: null;
  };
};

/** Body of `POST /api/sales` (from the backend validation rules). */
export type PostSalesBody = {
  customer_visit_id: number;
  due_date?: string;
  items: {
    product_id: number;
    quantity_cartons?: number;
    quantity_pieces?: number;
  }[];
  notes?: string;
  payment_type: string;
  salesbuzz_invoice_no: string;
};

/** Response of `POST /api/sales` (no capture: keys from backend code only). */
export type PostSalesResponse = {
  message?: unknown;
};

/** Query of `GET /api/sales` (from the backend validation rules). */
export type GetSalesQuery = {
  customer_id?: number;
  daily_session_id?: number;
  from?: string;
  invoice_no?: string;
  page?: string;
  payment_type?: string;
  per_page?: string;
  salesman_id?: number;
  status?: string;
  to?: string;
};

/** Response of `GET /api/sales` (from live captures). */
export type GetSalesResponse = {
  success: boolean;
  data: {
    id: number;
    sale_no: string;
    salesbuzz_invoice_no: string;
    branch_id: number;
    daily_session_id: number;
    customer: {
      id: number;
      customer_code: string;
      name: string;
    };
    salesman: {
      id: number;
      name: string;
    };
    payment_type: string;
    status: string;
    subtotal: string;
    discount_total: string;
    tpp_amount: number;
    net_total: string;
    line_count: number;
    due_date: string | null;
    sold_at: string;
    customer_id?: unknown;
    invoice_no?: unknown;
    salesman_id?: unknown;
  }[];
  meta: {
    total: number;
    per_page: number;
    current_page: number;
    last_page: number;
  };
};

/** Response of `GET /api/sales/{sale}` (from live captures). */
export type GetSalesSaleResponse = {
  success: boolean;
  data: {
    id: number;
    sale_no: string;
    salesbuzz_invoice_no: string;
    branch_id: number;
    daily_session_id: number;
    customer: {
      id: number;
      customer_code: string;
      name: string;
    };
    salesman: {
      id: number;
      name: string;
    };
    payment_type: string;
    status: string;
    subtotal: string;
    discount_total: string;
    tpp_amount: number;
    net_total: string;
    line_count: number;
    due_date: string;
    sold_at: string;
    session: {
      id: number;
      session_no: string;
      business_date: string;
    };
    lines: {
      product_id: number;
      product_code: string;
      product_name: string;
      quantity_cartons: number;
      bonus_quantity: number;
      unit_price: string;
      gross_amount: string;
      discount_amount: string;
      net_amount: string;
    }[];
    attachments: {
      id: number;
      type: string;
      original_name: string;
      checksum: string;
    }[];
    receivable: {
      id: number;
      receivable_no: string;
      original_amount: string;
      remaining_amount: string;
      due_date: string;
      status: string;
    };
  };
};
