// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/commission/preview` (from the backend validation rules). */
export type GetCommissionPreviewQuery = {
  branch_id?: number;
  period_end: string;
  period_start: string;
};

/** Response of `GET /api/commission/preview` (from live captures). */
export type GetCommissionPreviewResponse = {
  success: boolean;
  data: {
    branch_id: number;
    period_start: string;
    period_end: string;
    qualifying_percent: number;
    rows: unknown[];
  };
};

/** Query of `GET /api/commission/earnings` (from the backend validation rules). */
export type GetCommissionEarningsQuery = {
  payroll_period?: string;
};

/** Response of `GET /api/commission/earnings` (from live captures). */
export type GetCommissionEarningsResponse = {
  success: boolean;
  data: unknown[];
  achieved_percent?: unknown;
  branch_id?: unknown;
  closed_at?: unknown;
  employee?: unknown;
  employee_id?: unknown;
  id?: unknown;
  payroll_period?: unknown;
  reason?: unknown;
  sales_target_id?: unknown;
  status?: unknown;
  total_amount?: unknown;
};

/** Response of `POST /api/commission/targets/{target}/build` (no capture: keys from backend code only). */
export type PostCommissionTargetsTargetBuildResponse = {
  achieved_percent?: unknown;
  branch_id?: unknown;
  closed_at?: unknown;
  employee?: unknown;
  employee_id?: unknown;
  id?: unknown;
  message?: unknown;
  payroll_period?: unknown;
  reason?: unknown;
  sales_target_id?: unknown;
  status?: unknown;
  total_amount?: unknown;
};

/** Response of `POST /api/commission/earnings/{earning}/close` (no capture: keys from backend code only). */
export type PostCommissionEarningsEarningCloseResponse = {
  achieved_percent?: unknown;
  branch_id?: unknown;
  closed_at?: unknown;
  employee?: unknown;
  employee_id?: unknown;
  id?: unknown;
  message?: unknown;
  payroll_period?: unknown;
  reason?: unknown;
  sales_target_id?: unknown;
  status?: unknown;
  total_amount?: unknown;
};

/** Response of `GET /api/shortages/pending-verification` (from live captures). */
export type GetShortagesPendingVerificationResponse = {
  success: boolean;
  data: {
    id: number;
    daily_session_id: number;
    salesman_id: number;
    vehicle_id: number;
    product_id: number;
    difference_type: string;
    source: string;
    quantity_cartons: string;
    unit_cost: string;
    total_amount: string;
    settled_amount: string;
    remaining_amount: string;
    written_off_amount: string;
    status: string;
    verification_status: string;
    created_by: number;
    verified_by: null;
    verified_at: null;
    verification_notes: null;
    payroll_period: null;
    written_off_by: null;
    written_off_at: null;
    write_off_reason: null;
    notes: null;
    created_at: string;
    updated_at: string;
    salesman: {
      id: number;
      branch_id: number;
      employee_code: string;
      name: string;
      phone: string;
      job_title: string;
      position_code: string;
      hire_date: string;
      is_active: boolean;
      created_at: string;
      updated_at: string;
    };
    product: {
      id: number;
      code: string;
      name: string;
      category: string;
      unit_cost: string;
      trade_price: string;
      units_per_carton: number;
      barcode: string;
      salesbuzz_code: string;
      shelf_life_days: number;
      storage_temp_min: string;
      storage_temp_max: string;
      is_active: boolean;
      created_at: string;
      updated_at: string;
    };
    session: {
      id: number;
      session_no: string;
      branch_id: number;
      salesman_id: number;
      driver_id: number;
      supervisor_id: number;
      vehicle_id: number;
      route_id: number;
      business_date: string;
      trip_no: number;
      status: string;
      started_at: string;
      route_started_at: string;
      route_completed_at: null;
      returned_at: string;
      closed_at: null;
      created_at: string;
      updated_at: string;
    };
  }[];
};

/** Body of `POST /api/shortages/{shortage}/verify` (from the backend validation rules). */
export type PostShortagesShortageVerifyBody = {
  notes?: string;
};

/** Response of `POST /api/shortages/{shortage}/verify` (no capture: keys from backend code only). */
export type PostShortagesShortageVerifyResponse = {
  message?: unknown;
  notes?: unknown;
};

/** Body of `POST /api/shortages/{shortage}/reject` (from the backend validation rules). */
export type PostShortagesShortageRejectBody = {
  reason: string;
};

/** Response of `POST /api/shortages/{shortage}/reject` (no capture: keys from backend code only). */
export type PostShortagesShortageRejectResponse = {
  message?: unknown;
  reason?: unknown;
};

/** Body of `POST /api/shortages/{shortage}/write-off` (from the backend validation rules). */
export type PostShortagesShortageWriteOffBody = {
  reason: string;
};

/** Response of `POST /api/shortages/{shortage}/write-off` (no capture: keys from backend code only). */
export type PostShortagesShortageWriteOffResponse = {
  amount_written_off?: unknown;
  id?: unknown;
  message?: unknown;
  name?: unknown;
  reason?: unknown;
  salesman?: unknown;
  shortage_id?: unknown;
  written_off_at?: unknown;
  written_off_by?: unknown;
};

/** Query of `GET /api/shortages/write-offs` (from the backend validation rules). */
export type GetShortagesWriteOffsQuery = {
  from?: string;
  to?: string;
};

/** Response of `GET /api/shortages/write-offs` (from live captures). */
export type GetShortagesWriteOffsResponse = {
  success: boolean;
  summary: {
    count: number;
    total_amount: string;
  };
  data: {
    shortage_id: number;
    written_off_at: string;
    amount: string;
    salesman: {
      id: number;
      name: string;
      branch: string;
    };
    written_off_by: {
      id: number;
      name: string;
    };
    product: null;
    reason: string;
    from?: unknown;
    to?: unknown;
  }[];
};

/** Query of `GET /api/shortages` (from the backend validation rules). */
export type GetShortagesQuery = {
  open_only?: boolean;
  salesman_id?: number;
  status?: string;
};

/** Response of `GET /api/shortages` (from live captures). */
export type GetShortagesResponse = {
  success: boolean;
  summary: {
    count: number;
  };
  data: {
    id: number;
    daily_session_id: number;
    salesman_id: number;
    vehicle_id: number | null;
    product_id: number | null;
    difference_type: string;
    source: string;
    quantity_cartons: string | null;
    unit_cost: string | null;
    total_amount: string;
    settled_amount: string;
    remaining_amount: string;
    written_off_amount: string;
    status: string;
    verification_status: string;
    created_by: number;
    verified_by: number;
    verified_at: string;
    verification_notes: string;
    payroll_period: null;
    written_off_by: null;
    written_off_at: null;
    write_off_reason: null;
    notes: string | null;
    created_at: string;
    updated_at: string;
    salesman: {
      id: number;
      branch_id: number;
      employee_code: string;
      name: string;
      phone: string;
      job_title: string;
      position_code: string;
      hire_date: string;
      is_active: boolean;
      created_at: string;
      updated_at: string;
    };
    product: {
      id: number;
      code: string;
      name: string;
      category: string;
      unit_cost: string;
      trade_price: string;
      units_per_carton: number;
      barcode: string;
      salesbuzz_code: string;
      shelf_life_days: number;
      storage_temp_min: string;
      storage_temp_max: string;
      is_active: boolean;
      created_at: string;
      updated_at: string;
    } | null;
    session: {
      id: number;
      session_no: string;
      branch_id: number;
      salesman_id: number;
      driver_id: number;
      supervisor_id: number;
      vehicle_id: number;
      route_id: number;
      business_date: string;
      trip_no: number;
      status: string;
      started_at: string;
      route_started_at: string;
      route_completed_at: null;
      returned_at: string;
      closed_at: string;
      created_at: string;
      updated_at: string;
    };
    open_only?: unknown;
  }[];
};

/** Query of `GET /api/payroll/deductions` (from the backend validation rules). */
export type GetPayrollDeductionsQuery = {
  employee_id?: number;
  payroll_period?: string;
  status?: string;
};

/** Response of `GET /api/payroll/deductions` (from live captures). */
export type GetPayrollDeductionsResponse = {
  success: boolean;
  summary: {
    count: number;
  };
  data: unknown[];
  employee_id?: unknown;
  payroll_period?: unknown;
  status?: unknown;
};

/** Body of `POST /api/payroll-deductions` (from the backend validation rules). */
export type PostPayrollDeductionsBody = {
  employee_id: number;
  payroll_period: string;
};

/** Response of `POST /api/payroll-deductions` (no capture: keys from backend code only). */
export type PostPayrollDeductionsResponse = {
  employee_id?: unknown;
  message?: unknown;
  payroll_period?: unknown;
};

/** Response of `POST /api/payroll-deductions/{payrollDeduction}/close` (no capture: keys from backend code only). */
export type PostPayrollDeductionsPayrollDeductionCloseResponse = {
  message?: unknown;
};
