// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/stocktakes` (from the backend validation rules). */
export type GetStocktakesQuery = {
  status?: string;
  type?: string;
  warehouse_id?: number;
};

/** Response of `GET /api/stocktakes` (from live captures). */
export type GetStocktakesResponse = {
  success: boolean;
  data: unknown[];
  branch_id?: unknown;
  business_date?: unknown;
  code?: unknown;
  counted_at?: unknown;
  counted_by?: unknown;
  counted_cartons?: unknown;
  difference?: unknown;
  difference_value?: unknown;
  excess_value?: unknown;
  id?: unknown;
  items?: unknown;
  lines?: unknown;
  notes?: unknown;
  over_lines?: unknown;
  product?: unknown;
  product_id?: unknown;
  reviewed_at?: unknown;
  reviewed_by?: unknown;
  short_lines?: unknown;
  shortage_value?: unknown;
  status?: unknown;
  stocktake_no?: unknown;
  summary?: unknown;
  system_cartons?: unknown;
  type?: unknown;
  unit_cost?: unknown;
  warehouse?: unknown;
  warehouse_id?: unknown;
};

/** Response of `GET /api/stocktakes/{stocktake}` (no capture: keys from backend code only). */
export type GetStocktakesStocktakeResponse = {
  branch_id?: unknown;
  business_date?: unknown;
  code?: unknown;
  counted_at?: unknown;
  counted_by?: unknown;
  counted_cartons?: unknown;
  difference?: unknown;
  difference_value?: unknown;
  excess_value?: unknown;
  id?: unknown;
  items?: unknown;
  lines?: unknown;
  notes?: unknown;
  over_lines?: unknown;
  product?: unknown;
  product_id?: unknown;
  reviewed_at?: unknown;
  reviewed_by?: unknown;
  short_lines?: unknown;
  shortage_value?: unknown;
  status?: unknown;
  stocktake_no?: unknown;
  summary?: unknown;
  system_cartons?: unknown;
  type?: unknown;
  unit_cost?: unknown;
  warehouse?: unknown;
};

/** Body of `POST /api/stocktakes` (from the backend validation rules). */
export type PostStocktakesBody = {
  business_date: string;
  items: {
    counted_cartons: number;
    product_id: number;
  }[];
  notes?: string;
  type: string;
  warehouse_id: number;
};

/** Response of `POST /api/stocktakes` (no capture: keys from backend code only). */
export type PostStocktakesResponse = {
  branch_id?: unknown;
  business_date?: unknown;
  code?: unknown;
  counted_at?: unknown;
  counted_by?: unknown;
  counted_cartons?: unknown;
  difference?: unknown;
  difference_value?: unknown;
  excess_value?: unknown;
  id?: unknown;
  items?: unknown;
  lines?: unknown;
  message?: unknown;
  notes?: unknown;
  over_lines?: unknown;
  product?: unknown;
  product_id?: unknown;
  reviewed_at?: unknown;
  reviewed_by?: unknown;
  short_lines?: unknown;
  shortage_value?: unknown;
  status?: unknown;
  stocktake_no?: unknown;
  summary?: unknown;
  system_cartons?: unknown;
  type?: unknown;
  unit_cost?: unknown;
  warehouse?: unknown;
  warehouse_id?: unknown;
};

/** Response of `POST /api/stocktakes/{stocktake}/review` (no capture: keys from backend code only). */
export type PostStocktakesStocktakeReviewResponse = {
  branch_id?: unknown;
  business_date?: unknown;
  code?: unknown;
  counted_at?: unknown;
  counted_by?: unknown;
  counted_cartons?: unknown;
  difference?: unknown;
  difference_value?: unknown;
  excess_value?: unknown;
  id?: unknown;
  items?: unknown;
  lines?: unknown;
  message?: unknown;
  notes?: unknown;
  over_lines?: unknown;
  product?: unknown;
  product_id?: unknown;
  reviewed_at?: unknown;
  reviewed_by?: unknown;
  short_lines?: unknown;
  shortage_value?: unknown;
  status?: unknown;
  stocktake_no?: unknown;
  summary?: unknown;
  system_cartons?: unknown;
  type?: unknown;
  unit_cost?: unknown;
  warehouse?: unknown;
};

/** Body of `POST /api/salesman-stock-requests` (from the backend validation rules). */
export type PostSalesmanStockRequestsBody = {
  daily_session_id: number;
  items: {
    product_id: number;
    requested_quantity_cartons: string | number;
  }[];
  notes?: string;
};

/** Response of `POST /api/salesman-stock-requests` (no capture: keys from backend code only). */
export type PostSalesmanStockRequestsResponse = {
  message?: unknown;
};

/** Query of `GET /api/salesman-stock-requests` (from the backend validation rules). */
export type GetSalesmanStockRequestsQuery = {
  from?: string;
  page?: string;
  per_page?: string;
  salesman_id?: number;
  status?: string;
  to?: string;
};

/** Response of `GET /api/salesman-stock-requests` (from live captures). */
export type GetSalesmanStockRequestsResponse = {
  success: boolean;
  data: {
    id: number;
    request_no: string;
    daily_session_id: number;
    branch_id: number;
    salesman_id: number;
    vehicle_id: number;
    requested_by: number;
    status: string;
    submitted_at: string;
    processed_by: number | null;
    processed_at: string | null;
    notes: string;
    created_at: string;
    updated_at: string;
    items_count: number;
    salesman: {
      id: number;
      name: string;
    };
    vehicle: {
      id: number;
      code: string;
      plate_number: string;
    };
    session: {
      id: number;
      session_no: string;
      business_date: string;
    };
  }[];
  meta: {
    total: number;
    per_page: number;
    current_page: number;
    last_page: number;
  };
};

/** Response of `GET /api/pending-salesman-stock-requests` (from live captures). */
export type GetPendingSalesmanStockRequestsResponse = {
  data: {
    id: number;
    request_no: string;
    daily_session_id: number;
    branch_id: number;
    salesman_id: number;
    vehicle_id: number;
    requested_by: number;
    status: string;
    submitted_at: string;
    processed_by: null;
    processed_at: null;
    notes: string;
    created_at: string;
    updated_at: string;
    salesman: {
      id: number;
      branch_id: number;
      employee_code: string;
      name: string;
      phone: string;
      job_title: string;
      position_code: string;
      hire_date: string;
      is_active: boolean;
      created_at: string;
      updated_at: string;
    };
    vehicle: {
      id: number;
      branch_id: number;
      code: string;
      plate_number: string;
      model: string;
      make: null;
      year_of_manufacture: null;
      chassis_number: null;
      engine_number: null;
      fuel_type: null;
      tank_capacity_litres: null;
      licence_expires_on: null;
      insurance_expires_on: null;
      current_odometer: number | null;
      status: string;
      notes: null;
      is_active: boolean;
      created_at: string;
      updated_at: string;
    };
    session: {
      id: number;
      session_no: string;
      branch_id: number;
      salesman_id: number;
      driver_id: number;
      supervisor_id: number;
      vehicle_id: number;
      route_id: number;
      business_date: string;
      trip_no: number;
      status: string;
      started_at: string;
      route_started_at: null;
      route_completed_at: null;
      returned_at: null;
      closed_at: null;
      created_at: string;
      updated_at: string;
    };
    items: {
      id: number;
      salesman_stock_request_id: number;
      product_id: number;
      requested_quantity_cartons: string;
      created_at: string;
      updated_at: string;
      product: {
        id: number;
        code: string;
        name: string;
        category: string | null;
        unit_cost: string;
        trade_price: string;
        units_per_carton: number;
        barcode: string;
        salesbuzz_code: string;
        shelf_life_days: number;
        storage_temp_min: string;
        storage_temp_max: string;
        is_active: boolean;
        created_at: string;
        updated_at: string;
      };
    }[];
  }[];
};

/** Query of `GET /api/stock-issues` (from the backend validation rules). */
export type GetStockIssuesQuery = {
  business_date?: string;
  salesman_id?: number;
  status?: string;
  warehouse_id?: number;
};

/** Response of `GET /api/stock-issues` (from live captures). */
export type GetStockIssuesResponse = {
  success: boolean;
  summary: {
    count: number;
  };
  data: unknown[];
  business_date?: unknown;
  daily_session_id?: unknown;
  id?: unknown;
  issue_no?: unknown;
  issued_at?: unknown;
  items_count?: unknown;
  salesman?: unknown;
  salesman_id?: unknown;
  salesman_stock_request_id?: unknown;
  status?: unknown;
  trip_no?: unknown;
  vehicle?: unknown;
  warehouse?: unknown;
  warehouse_id?: unknown;
};

/** Response of `GET /api/stock-issues/{stockIssue}` (from live captures). */
export type GetStockIssuesStockIssueResponse = {
  success: boolean;
  data: {
    id: number;
    issue_no: string;
    status: string;
    daily_session_id: number;
    salesman_stock_request_id: number;
    business_date: string;
    trip_no: number;
    warehouse_id: number;
    warehouse: string;
    salesman_id: number;
    salesman: string;
    vehicle: string;
    issued_at: string;
    lines: {
      id: number;
      product_id: number;
      product_code: string;
      product_name: string;
      units_per_carton: number;
      quantity_cartons: number;
    }[];
  };
};

/** Body of `POST /api/stock-issues` (from the backend validation rules). */
export type PostStockIssuesBody = {
  items: {
    product_id: number;
    quantity_cartons: number;
  }[];
  notes?: string;
  salesman_stock_request_id: number;
  warehouse_id: number;
};

/** Response of `POST /api/stock-issues` (no capture: keys from backend code only). */
export type PostStockIssuesResponse = {
  message?: unknown;
};

/** Response of `POST /api/stock-issues/{stockIssue}/issue` (no capture: keys from backend code only). */
export type PostStockIssuesStockIssueIssueResponse = {
  message?: unknown;
};

/** Response of `POST /api/stock-issues/{stockIssue}/confirm` (no capture: keys from backend code only). */
export type PostStockIssuesStockIssueConfirmResponse = {
  message?: unknown;
};
