// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/suppliers` (from the backend validation rules). */
export type GetSuppliersQuery = {
  is_active?: boolean;
  search?: string;
};

/** Response of `GET /api/suppliers` (from live captures). */
export type GetSuppliersResponse = {
  success: boolean;
  summary: {
    count: number;
  };
  data: {
    id: number;
    code: string;
    name: string;
    phone: null;
    is_active: boolean;
    search?: unknown;
  }[];
};

/** Query of `GET /api/supply-requests` (from the backend validation rules). */
export type GetSupplyRequestsQuery = {
  status?: string;
};

/** Response of `GET /api/supply-requests` (from live captures). */
export type GetSupplyRequestsResponse = {
  success: boolean;
  data: {
    id: number;
    request_no: string;
    branch_id: number;
    supplier: string;
    warehouse: string;
    requested_for: string;
    status: string;
    sent_at: string | null;
    notes: string | null;
    items: {
      product_id: number;
      product: string;
      code: string;
      quantity_cartons: number;
    }[];
  }[];
};

/** Response of `GET /api/supply-requests/{supplyRequest}` (from live captures). */
export type GetSupplyRequestsSupplyRequestResponse = {
  success: boolean;
  data: {
    id: number;
    request_no: string;
    branch_id: number;
    supplier: string;
    warehouse: string;
    requested_for: string;
    status: string;
    sent_at: string;
    notes: string;
    items: {
      product_id: number;
      product: string;
      code: string;
      quantity_cartons: number;
    }[];
  };
};

/** Body of `POST /api/supply-requests` (from the backend validation rules). */
export type PostSupplyRequestsBody = {
  items?: {
    product_id: number;
    quantity_cartons: number;
  }[];
  notes?: string;
  requested_for: string;
  supplier_id?: number;
  warehouse_id: number;
};

/** Response of `POST /api/supply-requests` (from live captures). */
export type PostSupplyRequestsResponse = {
  success: boolean;
  message: string;
  data: {
    id: number;
    request_no: string;
    branch_id: number;
    supplier: string;
    warehouse: string;
    requested_for: string;
    status: string;
    sent_at: null;
    notes: null;
    items: unknown[];
    code?: unknown;
    product?: unknown;
    product_id?: unknown;
    quantity_cartons?: unknown;
    supplier_id?: unknown;
    warehouse_id?: unknown;
  };
};

/** Body of `PATCH /api/supply-requests/{supplyRequest}` (from the backend validation rules). */
export type PatchSupplyRequestsSupplyRequestBody = {
  items?: {
    product_id: number;
    quantity_cartons: number;
  }[];
  notes?: string;
  requested_for?: string;
};

/** Response of `PATCH /api/supply-requests/{supplyRequest}` (no capture: keys from backend code only). */
export type PatchSupplyRequestsSupplyRequestResponse = {
  branch_id?: unknown;
  code?: unknown;
  id?: unknown;
  items?: unknown;
  message?: unknown;
  notes?: unknown;
  product?: unknown;
  product_id?: unknown;
  quantity_cartons?: unknown;
  request_no?: unknown;
  requested_for?: unknown;
  sent_at?: unknown;
  status?: unknown;
  supplier?: unknown;
  warehouse?: unknown;
};

/** Response of `POST /api/supply-requests/{supplyRequest}/send` (no capture: keys from backend code only). */
export type PostSupplyRequestsSupplyRequestSendResponse = {
  branch_id?: unknown;
  code?: unknown;
  id?: unknown;
  items?: unknown;
  message?: unknown;
  notes?: unknown;
  product?: unknown;
  product_id?: unknown;
  quantity_cartons?: unknown;
  request_no?: unknown;
  requested_for?: unknown;
  sent_at?: unknown;
  status?: unknown;
  supplier?: unknown;
  warehouse?: unknown;
};

/** Response of `GET /api/goods-receipts` (from live captures). */
export type GetGoodsReceiptsResponse = {
  success: boolean;
  data: {
    id: number;
    receipt_no: string;
    delivery_note_no: string;
    branch_id: number;
    supply_request_id: number;
    warehouse: string;
    received_on: string;
    status: string;
    confirmed_at: string;
    payment: {
      amount: string;
      reference: string | null;
      paid_on: string;
      confirmed: boolean;
      confirmed_by: string | null;
      confirmed_at: string | null;
    } | null;
    items: {
      product_id: number;
      product: string;
      code: string;
      ordered_cartons: number;
      received_cartons: number;
      variance: number;
    }[];
    has_variance: boolean;
  }[];
};

/** Body of `POST /api/goods-receipts` (from the backend validation rules). */
export type PostGoodsReceiptsBody = {
  delivery_note_no?: string;
  items: {
    barcode?: string;
    lots?: {
      best_before?: string;
      cartons: number;
      lot_no: string;
    }[];
    product_code?: string;
    product_id?: number;
    received_cartons: number;
  }[];
  notes?: string;
  received_on: string;
  supply_request_id?: number;
  warehouse_id?: number;
};

/** Response of `POST /api/goods-receipts` (no capture: keys from backend code only). */
export type PostGoodsReceiptsResponse = {
  amount?: unknown;
  branch_id?: unknown;
  code?: unknown;
  confirmed?: unknown;
  confirmed_at?: unknown;
  confirmed_by?: unknown;
  delivery_note_no?: unknown;
  has_variance?: unknown;
  id?: unknown;
  items?: unknown;
  message?: unknown;
  notes?: unknown;
  ordered_cartons?: unknown;
  paid_on?: unknown;
  payment?: unknown;
  product?: unknown;
  product_id?: unknown;
  receipt_no?: unknown;
  received_cartons?: unknown;
  received_on?: unknown;
  reference?: unknown;
  status?: unknown;
  supply_request_id?: unknown;
  variance?: unknown;
  warehouse?: unknown;
  warehouse_id?: unknown;
};

/** Response of `POST /api/goods-receipts/{goodsReceipt}/confirm` (no capture: keys from backend code only). */
export type PostGoodsReceiptsGoodsReceiptConfirmResponse = {
  amount?: unknown;
  branch_id?: unknown;
  code?: unknown;
  confirmed?: unknown;
  confirmed_at?: unknown;
  confirmed_by?: unknown;
  delivery_note_no?: unknown;
  has_variance?: unknown;
  id?: unknown;
  items?: unknown;
  message?: unknown;
  ordered_cartons?: unknown;
  paid_on?: unknown;
  payment?: unknown;
  product?: unknown;
  product_id?: unknown;
  receipt_no?: unknown;
  received_cartons?: unknown;
  received_on?: unknown;
  reference?: unknown;
  status?: unknown;
  supply_request_id?: unknown;
  variance?: unknown;
  warehouse?: unknown;
};

/** Response of `GET /api/goods-receipts/lots/{lotNo}` (no capture: keys from backend code only). */
export type GetGoodsReceiptsLotsLotNoResponse = Record<string, unknown>;

/** Query of `GET /api/goods-receipts/expiring-lots` (from the backend validation rules). */
export type GetGoodsReceiptsExpiringLotsQuery = {
  by?: string;
};

/** Response of `GET /api/goods-receipts/expiring-lots` (from live captures). */
export type GetGoodsReceiptsExpiringLotsResponse = {
  success: boolean;
  data: unknown[];
  by?: unknown;
};

/** Body of `POST /api/goods-receipts/{goodsReceipt}/payment` (from the backend validation rules). */
export type PostGoodsReceiptsGoodsReceiptPaymentBody = {
  paid_amount: string | number;
  paid_on: string;
  payment_reference?: string;
};

/** Response of `POST /api/goods-receipts/{goodsReceipt}/payment` (from live captures). */
export type PostGoodsReceiptsGoodsReceiptPaymentResponse = {
  success: boolean;
  message: string;
  data: {
    id: number;
    receipt_no: string;
    delivery_note_no: string;
    branch_id: number;
    supply_request_id: number;
    warehouse: string;
    received_on: string;
    status: string;
    confirmed_at: string;
    payment: {
      amount: string;
      reference: null;
      paid_on: string;
      confirmed: boolean;
      confirmed_by: null;
      confirmed_at: null;
    };
    items: {
      product_id: number;
      product: string;
      code: string;
      ordered_cartons: number;
      received_cartons: number;
      variance: number;
    }[];
    has_variance: boolean;
    paid_amount?: unknown;
    payment_reference?: unknown;
  };
};

/** Response of `POST /api/goods-receipts/{goodsReceipt}/payment/confirm` (no capture: keys from backend code only). */
export type PostGoodsReceiptsGoodsReceiptPaymentConfirmResponse = {
  amount?: unknown;
  branch_id?: unknown;
  code?: unknown;
  confirmed?: unknown;
  confirmed_at?: unknown;
  confirmed_by?: unknown;
  delivery_note_no?: unknown;
  has_variance?: unknown;
  id?: unknown;
  items?: unknown;
  message?: unknown;
  ordered_cartons?: unknown;
  paid_on?: unknown;
  payment?: unknown;
  product?: unknown;
  product_id?: unknown;
  receipt_no?: unknown;
  received_cartons?: unknown;
  received_on?: unknown;
  reference?: unknown;
  status?: unknown;
  supply_request_id?: unknown;
  variance?: unknown;
  warehouse?: unknown;
};
