// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/targets` (from the backend validation rules). */
export type GetTargetsQuery = {
  period_start?: string;
  salesman_id?: number;
};

/** Response of `GET /api/targets` (from live captures). */
export type GetTargetsResponse = {
  success: boolean;
  data: unknown[];
  branch_id?: unknown;
  commission?: unknown;
  drop_size?: unknown;
  drop_size_target?: unknown;
  id?: unknown;
  invoice_target?: unknown;
  invoices?: unknown;
  notes?: unknown;
  nps?: unknown;
  nps_target?: unknown;
  period_end?: unknown;
  period_start?: unknown;
  pos?: unknown;
  pos_target?: unknown;
  salesman?: unknown;
  salesman_id?: unknown;
  working_days?: unknown;
};

/** Body of `POST /api/targets` (from the backend validation rules). */
export type PostTargetsBody = {
  drop_size_commission?: string | number;
  drop_size_target?: string | number;
  invoice_commission?: string | number;
  invoice_target?: number;
  notes?: string;
  nps_commission?: string | number;
  nps_target?: string | number;
  period_end: string;
  period_start: string;
  pos_commission?: string | number;
  pos_target?: number;
  salesman_id: number;
  working_days: number;
};

/** Response of `POST /api/targets` (no capture: keys from backend code only). */
export type PostTargetsResponse = {
  branch_id?: unknown;
  commission?: unknown;
  drop_size?: unknown;
  drop_size_commission?: unknown;
  drop_size_target?: unknown;
  id?: unknown;
  invoice_commission?: unknown;
  invoice_target?: unknown;
  invoices?: unknown;
  message?: unknown;
  notes?: unknown;
  nps?: unknown;
  nps_commission?: unknown;
  nps_target?: unknown;
  period_end?: unknown;
  period_start?: unknown;
  pos?: unknown;
  pos_commission?: unknown;
  pos_target?: unknown;
  salesman?: unknown;
  salesman_id?: unknown;
  working_days?: unknown;
};

/** Body of `PATCH /api/targets/{target}` (from the backend validation rules). */
export type PatchTargetsTargetBody = {
  drop_size_commission?: string | number;
  drop_size_target?: string | number;
  invoice_commission?: string | number;
  invoice_target?: number;
  notes?: string;
  nps_commission?: string | number;
  nps_target?: string | number;
  pos_commission?: string | number;
  pos_target?: number;
  working_days?: number;
};

/** Response of `PATCH /api/targets/{target}` (no capture: keys from backend code only). */
export type PatchTargetsTargetResponse = {
  branch_id?: unknown;
  commission?: unknown;
  drop_size?: unknown;
  drop_size_commission?: unknown;
  drop_size_target?: unknown;
  id?: unknown;
  invoice_commission?: unknown;
  invoice_target?: unknown;
  invoices?: unknown;
  message?: unknown;
  notes?: unknown;
  nps?: unknown;
  nps_commission?: unknown;
  nps_target?: unknown;
  period_end?: unknown;
  period_start?: unknown;
  pos?: unknown;
  pos_commission?: unknown;
  pos_target?: unknown;
  salesman?: unknown;
  salesman_id?: unknown;
  working_days?: unknown;
};

/** Query of `GET /api/customer-offers` (from the backend validation rules). */
export type GetCustomerOffersQuery = {
  active_on?: string;
  customer_id?: number;
};

/** Response of `GET /api/customer-offers` (from live captures). */
export type GetCustomerOffersResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    customer_id: number;
    customer: string;
    discount_rate: number;
    discount_amount: null;
    min_invoice_amount: number;
    starts_on: string;
    ends_on: string | null;
    is_active: boolean;
    approved_by: string;
    notes: string;
    active_on?: unknown;
  }[];
};

/** Body of `POST /api/customer-offers` (from the backend validation rules). */
export type PostCustomerOffersBody = {
  customer_id: number;
  discount_amount?: string | number;
  discount_rate?: string | number;
  ends_on?: string;
  min_invoice_amount?: string | number;
  notes?: string;
  starts_on: string;
};

/** Response of `POST /api/customer-offers` (no capture: keys from backend code only). */
export type PostCustomerOffersResponse = {
  approved_by?: unknown;
  branch_id?: unknown;
  customer?: unknown;
  customer_id?: unknown;
  discount_amount?: unknown;
  discount_rate?: unknown;
  ends_on?: unknown;
  id?: unknown;
  is_active?: unknown;
  message?: unknown;
  min_invoice_amount?: unknown;
  notes?: unknown;
  starts_on?: unknown;
};

/** Body of `POST /api/customer-offers/{offer}/end` (from the backend validation rules). */
export type PostCustomerOffersOfferEndBody = {
  ends_on: string;
};

/** Response of `POST /api/customer-offers/{offer}/end` (from live captures). */
export type PostCustomerOffersOfferEndResponse = {
  success: boolean;
  message: string;
  data: {
    id: number;
    branch_id: number;
    customer_id: number;
    customer: string;
    discount_rate: number;
    discount_amount: null;
    min_invoice_amount: number;
    starts_on: string;
    ends_on: string;
    is_active: boolean;
    approved_by: string;
    notes: string;
  };
};
