// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/daily-stock-closings` (from the backend validation rules). */
export type GetDailyStockClosingsQuery = {
  business_date?: string;
  salesman_id?: number;
  status?: string;
};

/** Response of `GET /api/daily-stock-closings` (from live captures). */
export type GetDailyStockClosingsResponse = {
  success: boolean;
  summary: {
    count: number;
  };
  data: {
    id: number;
    closing_no: string;
    status: string;
    daily_session_id: number;
    business_date: string;
    trip_no: number;
    vehicle: string;
    salesman_id: number;
    salesman: string;
    submitted_by: string;
    submitted_at: string;
    confirmed_at: null;
  }[];
};

/** Response of `GET /api/daily-stock-closings/{dailyStockClosing}` (from live captures). */
export type GetDailyStockClosingsDailyStockClosingResponse = {
  success: boolean;
  data: {
    id: number;
    closing_no: string;
    status: string;
    daily_session_id: number;
    business_date: string;
    trip_no: number;
    vehicle: string;
    salesman_id: number;
    salesman: string;
    submitted_by: string;
    submitted_at: string;
    confirmed_by: null;
    confirmed_at: null;
    notes: null;
    lines: {
      id: number;
      product_id: number;
      product_code: string;
      product_name: string;
      units_per_carton: number;
      system_quantity_cartons: number;
      salesman_counted_quantity_cartons: number;
      storekeeper_received_quantity_cartons: null;
      shortage_quantity_cartons: number;
      excess_quantity_cartons: number;
    }[];
  };
};

/** Body of `POST /api/daily-stock-closings` (from the backend validation rules). */
export type PostDailyStockClosingsBody = {
  daily_session_id: number;
  items?: {
    counted_quantity_cartons: number;
    product_id: number;
  }[];
  notes?: string;
};

/** Response of `POST /api/daily-stock-closings` (no capture: keys from backend code only). */
export type PostDailyStockClosingsResponse = {
  message?: unknown;
};

/** Body of `POST /api/daily-stock-closings/{dailyStockClosing}/confirm` (from the backend validation rules). */
export type PostDailyStockClosingsDailyStockClosingConfirmBody = {
  items?: {
    product_id: number;
    received_quantity_cartons: number;
  }[];
  notes?: string;
  warehouse_id: number;
};

/** Response of `POST /api/daily-stock-closings/{dailyStockClosing}/confirm` (no capture: keys from backend code only). */
export type PostDailyStockClosingsDailyStockClosingConfirmResponse = {
  message?: unknown;
};

/** Body of `POST /api/daily-cash-closings` (from the backend validation rules). */
export type PostDailyCashClosingsBody = {
  daily_session_id: number;
  notes?: string;
  salesbuzz_invoice_total?: string | number;
};

/** Response of `POST /api/daily-cash-closings` (no capture: keys from backend code only). */
export type PostDailyCashClosingsResponse = {
  message?: unknown;
};

/** Body of `POST /api/treasury-handovers` (from the backend validation rules). */
export type PostTreasuryHandoversBody = {
  cash_closing_ids: unknown[] | Record<string, unknown>;
  notes?: string;
};

/** Response of `POST /api/treasury-handovers` (no capture: keys from backend code only). */
export type PostTreasuryHandoversResponse = {
  message?: unknown;
};

/** Body of `POST /api/treasury-handovers/{treasuryHandover}/confirm` (from the backend validation rules). */
export type PostTreasuryHandoversTreasuryHandoverConfirmBody = {
  notes?: string;
  received_amount: string | number;
};

/** Response of `POST /api/treasury-handovers/{treasuryHandover}/confirm` (no capture: keys from backend code only). */
export type PostTreasuryHandoversTreasuryHandoverConfirmResponse = {
  message?: unknown;
};

/** Query of `GET /api/treasury/daily` (from the backend validation rules). */
export type GetTreasuryDailyQuery = {
  branch_id?: number;
  business_date: string;
};

/** Response of `GET /api/treasury/daily` (from live captures). */
export type GetTreasuryDailyResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    business_date: string;
    status: string;
    collected: {
      cash: string;
      cheque: string;
      transfer: string;
      card: string;
    };
    deposits: {
      fridge_received: string;
      fridge_refunded: string;
      other: string;
    };
    expenses_amount: string;
    net_cash_amount: string;
    count: {
      denominations: null;
      counted_cash_amount: null;
      variance_amount: string;
      counted_by: null;
      counted_at: null;
    };
    remitted_to_bank_amount: string;
    remittance: {
      status: string;
      expected_amount: null;
      remitted_amount: null;
      remitted_by: null;
      remitted_at: null;
      received_amount: null;
      variance_amount: null;
      confirmed_by: null;
      confirmed_at: null;
      notes: null;
    };
    handover_count: number;
    pending_session_count: number;
    closed_by: null;
    closed_at: null;
    notes: null;
  };
};

/** Body of `POST /api/treasury/daily/count` (from the backend validation rules). */
export type PostTreasuryDailyCountBody = {
  branch_id?: number;
  business_date: string;
  denominations: unknown[] | Record<string, unknown>;
  notes?: string;
  other_deposits_amount?: string | number;
  remitted_to_bank_amount?: string | number;
};

/** Response of `POST /api/treasury/daily/count` (no capture: keys from backend code only). */
export type PostTreasuryDailyCountResponse = {
  branch_id?: unknown;
  business_date?: unknown;
  card?: unknown;
  cash?: unknown;
  cheque?: unknown;
  closed_at?: unknown;
  closed_by?: unknown;
  collected?: unknown;
  confirmed_at?: unknown;
  confirmed_by?: unknown;
  count?: unknown;
  counted_at?: unknown;
  counted_by?: unknown;
  counted_cash_amount?: unknown;
  denominations?: unknown;
  deposits?: unknown;
  expected_amount?: unknown;
  expenses_amount?: unknown;
  fridge_received?: unknown;
  fridge_refunded?: unknown;
  handover_count?: unknown;
  id?: unknown;
  message?: unknown;
  net_cash_amount?: unknown;
  notes?: unknown;
  other?: unknown;
  other_deposits_amount?: unknown;
  pending_session_count?: unknown;
  received_amount?: unknown;
  remittance?: unknown;
  remitted_amount?: unknown;
  remitted_at?: unknown;
  remitted_by?: unknown;
  remitted_to_bank_amount?: unknown;
  status?: unknown;
  transfer?: unknown;
  variance_amount?: unknown;
};

/** Body of `POST /api/treasury/daily/{branchDailyTreasury}/close` (from the backend validation rules). */
export type PostTreasuryDailyBranchDailyTreasuryCloseBody = {
  notes?: string;
};

/** Response of `POST /api/treasury/daily/{branchDailyTreasury}/close` (no capture: keys from backend code only). */
export type PostTreasuryDailyBranchDailyTreasuryCloseResponse = {
  branch_id?: unknown;
  business_date?: unknown;
  card?: unknown;
  cash?: unknown;
  cheque?: unknown;
  closed_at?: unknown;
  closed_by?: unknown;
  collected?: unknown;
  confirmed_at?: unknown;
  confirmed_by?: unknown;
  count?: unknown;
  counted_at?: unknown;
  counted_by?: unknown;
  counted_cash_amount?: unknown;
  denominations?: unknown;
  deposits?: unknown;
  expected_amount?: unknown;
  expenses_amount?: unknown;
  fridge_received?: unknown;
  fridge_refunded?: unknown;
  handover_count?: unknown;
  id?: unknown;
  message?: unknown;
  net_cash_amount?: unknown;
  notes?: unknown;
  other?: unknown;
  pending_session_count?: unknown;
  received_amount?: unknown;
  remittance?: unknown;
  remitted_amount?: unknown;
  remitted_at?: unknown;
  remitted_by?: unknown;
  remitted_to_bank_amount?: unknown;
  status?: unknown;
  transfer?: unknown;
  variance_amount?: unknown;
};

/** Body of `POST /api/treasury/daily/{branchDailyTreasury}/remit` (from the backend validation rules). */
export type PostTreasuryDailyBranchDailyTreasuryRemitBody = {
  amount: string | number;
  notes?: string;
};

/** Response of `POST /api/treasury/daily/{branchDailyTreasury}/remit` (no capture: keys from backend code only). */
export type PostTreasuryDailyBranchDailyTreasuryRemitResponse = {
  amount?: unknown;
  branch_id?: unknown;
  business_date?: unknown;
  card?: unknown;
  cash?: unknown;
  cheque?: unknown;
  closed_at?: unknown;
  closed_by?: unknown;
  collected?: unknown;
  confirmed_at?: unknown;
  confirmed_by?: unknown;
  count?: unknown;
  counted_at?: unknown;
  counted_by?: unknown;
  counted_cash_amount?: unknown;
  denominations?: unknown;
  deposits?: unknown;
  expected_amount?: unknown;
  expenses_amount?: unknown;
  fridge_received?: unknown;
  fridge_refunded?: unknown;
  handover_count?: unknown;
  id?: unknown;
  message?: unknown;
  net_cash_amount?: unknown;
  notes?: unknown;
  other?: unknown;
  pending_session_count?: unknown;
  received_amount?: unknown;
  remittance?: unknown;
  remitted_amount?: unknown;
  remitted_at?: unknown;
  remitted_by?: unknown;
  remitted_to_bank_amount?: unknown;
  status?: unknown;
  transfer?: unknown;
  variance_amount?: unknown;
};

/** Body of `POST /api/treasury/daily/{branchDailyTreasury}/remit/confirm` (from the backend validation rules). */
export type PostTreasuryDailyBranchDailyTreasuryRemitConfirmBody = {
  notes?: string;
  received_amount: string | number;
};

/** Response of `POST /api/treasury/daily/{branchDailyTreasury}/remit/confirm` (no capture: keys from backend code only). */
export type PostTreasuryDailyBranchDailyTreasuryRemitConfirmResponse = {
  branch_id?: unknown;
  business_date?: unknown;
  card?: unknown;
  cash?: unknown;
  cheque?: unknown;
  closed_at?: unknown;
  closed_by?: unknown;
  collected?: unknown;
  confirmed_at?: unknown;
  confirmed_by?: unknown;
  count?: unknown;
  counted_at?: unknown;
  counted_by?: unknown;
  counted_cash_amount?: unknown;
  denominations?: unknown;
  deposits?: unknown;
  expected_amount?: unknown;
  expenses_amount?: unknown;
  fridge_received?: unknown;
  fridge_refunded?: unknown;
  handover_count?: unknown;
  id?: unknown;
  message?: unknown;
  net_cash_amount?: unknown;
  notes?: unknown;
  other?: unknown;
  pending_session_count?: unknown;
  received_amount?: unknown;
  remittance?: unknown;
  remitted_amount?: unknown;
  remitted_at?: unknown;
  remitted_by?: unknown;
  remitted_to_bank_amount?: unknown;
  status?: unknown;
  transfer?: unknown;
  variance_amount?: unknown;
};
