// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Body of `POST /api/vehicle-inventory-counts` (from the backend validation rules). */
export type PostVehicleInventoryCountsBody = {
  daily_session_id: number;
  items: {
    actual_quantity_cartons: string | number;
    product_id: number;
  }[];
  notes?: string;
};

/** Response of `POST /api/vehicle-inventory-counts` (no capture: keys from backend code only). */
export type PostVehicleInventoryCountsResponse = {
  cartons_over?: unknown;
  cartons_short?: unknown;
  counted_at?: unknown;
  counted_by?: unknown;
  daily_session_id?: unknown;
  id?: unknown;
  items?: unknown;
  lines_counted?: unknown;
  lines_over?: unknown;
  lines_short?: unknown;
  message?: unknown;
  name?: unknown;
  salesman?: unknown;
  status?: unknown;
  summary?: unknown;
  vehicle_id?: unknown;
};

/** Query of `GET /api/vehicle-inventory-counts/pending` (from the backend validation rules). */
export type GetVehicleInventoryCountsPendingQuery = {
  business_date?: string;
};

/** Response of `GET /api/vehicle-inventory-counts/pending` (from live captures). */
export type GetVehicleInventoryCountsPendingResponse = {
  success: boolean;
  data: {
    daily_session_id: number;
    session_no: string;
    business_date: string;
    status: string;
    salesman: string;
    vehicle: string;
    plate_number: string;
    route: string;
    returned_at: string;
  }[];
};

/** Query of `GET /api/vehicle-inventory-counts` (from the backend validation rules). */
export type GetVehicleInventoryCountsQuery = {
  daily_session_id?: number;
  from?: string;
  page?: string;
  per_page?: string;
  status?: string;
  to?: string;
  vehicle_id?: number;
};

/** Response of `GET /api/vehicle-inventory-counts` (from live captures). */
export type GetVehicleInventoryCountsResponse = {
  success: boolean;
  data: {
    id: number;
    daily_session_id: number;
    vehicle: {
      id: number;
      code: string;
      plate_number: string;
    };
    counted_by: {
      id: number;
      name: string;
    };
    session: {
      id: number;
      session_no: string;
      business_date: string;
    };
    status: string;
    line_count: number;
    counted_at: string;
    vehicle_id?: unknown;
  }[];
  meta: {
    total: number;
    per_page: number;
    current_page: number;
    last_page: number;
  };
};

/** Response of `GET /api/vehicle-inventory-counts/{vehicleInventoryCount}` (from live captures). */
export type GetVehicleInventoryCountsVehicleInventoryCountResponse = {
  success: boolean;
  data: {
    id: number;
    daily_session_id: number;
    vehicle: {
      id: number;
      code: string;
      plate_number: string;
    };
    counted_by: {
      id: number;
      name: string;
    };
    session: {
      id: number;
      session_no: string;
      business_date: string;
    };
    status: string;
    line_count: number;
    counted_at: string;
    lines: {
      product_id: number;
      product_code: string;
      product_name: string;
      system_cartons: number;
      counted_cartons: number;
      difference_cartons: number;
      difference_type: string;
    }[];
  };
};
