// Generated by dev/api-audit/gen-types.ts. Do not edit by hand.

/** Query of `GET /api/vehicles/{vehicle}/file` (from the backend validation rules). */
export type GetVehiclesVehicleFileQuery = {
  from?: string;
  to?: string;
};

/** Response of `GET /api/vehicles/{vehicle}/file` (from live captures). */
export type GetVehiclesVehicleFileResponse = {
  success: boolean;
  data: {
    vehicle: {
      id: number;
      code: string;
      plate_number: string;
      make: null;
      model: string;
      year_of_manufacture: null;
      chassis_number: null;
      engine_number: null;
      fuel_type: null;
      tank_capacity_litres: null;
      status: string;
      current_odometer: null;
    };
    compliance: {
      licence_expires_on: null;
      licence_days_left: null;
      insurance_expires_on: null;
      insurance_days_left: null;
    };
    period: {
      from: string;
      to: string;
    };
    costs: {
      by_category: {
        FUEL_VEHICLE: string;
        MAINT_VEHICLE: string;
        OIL_VEHICLE: string;
        VEH_LICENCE: string;
        OTHER: string;
      };
      total: string;
      entry_count: number;
    };
    running: {
      distance_km: number;
      fuel_litres: string;
      litres_per_100km: string;
      odometer_readings_missing: number;
      measurement_complete: boolean;
    };
    service_history: unknown[];
    next_due: null;
  };
};

/** Query of `GET /api/vehicles/maintenance/due` (from the backend validation rules). */
export type GetVehiclesMaintenanceDueQuery = {
  branch_id?: number;
  within_days?: number;
};

/** Response of `GET /api/vehicles/maintenance/due` (from live captures). */
export type GetVehiclesMaintenanceDueResponse = {
  success: boolean;
  data: unknown[];
  branch_id?: unknown;
  within_days?: unknown;
};

/** Body of `POST /api/vehicles/maintenance` (from the backend validation rules). */
export type PostVehiclesMaintenanceBody = {
  description?: string;
  document_no?: string;
  expense_id?: number;
  next_service_due_km?: number;
  next_service_due_on?: string;
  notes?: string;
  odometer_reading?: number;
  parts?: {
    notes?: string;
    part_name: string;
    quantity?: string | number;
    unit_cost?: string | number;
  }[];
  performed_on?: string;
  type: string;
  vehicle_id: number;
  workshop?: string;
};

/** Response of `POST /api/vehicles/maintenance` (no capture: keys from backend code only). */
export type PostVehiclesMaintenanceResponse = {
  description?: unknown;
  document_no?: unknown;
  expense_id?: unknown;
  id?: unknown;
  message?: unknown;
  next_service_due_km?: unknown;
  next_service_due_on?: unknown;
  notes?: unknown;
  odometer_reading?: unknown;
  parts?: unknown;
  parts_total?: unknown;
  performed_on?: unknown;
  service_no?: unknown;
  type?: unknown;
  vehicle_id?: unknown;
  workshop?: unknown;
};

/** Query of `GET /api/vehicles` (from the backend validation rules). */
export type GetVehiclesQuery = {
  is_active?: boolean;
  q?: string;
  status?: string;
};

/** Response of `GET /api/vehicles` (from live captures). */
export type GetVehiclesResponse = {
  success: boolean;
  data: {
    id: number;
    branch_id: number;
    code: string;
    plate_number: string;
    model: string;
    status: string;
    notes: null;
    is_active: boolean;
    q?: unknown;
  }[];
};

/** Body of `POST /api/vehicles` (from the backend validation rules). */
export type PostVehiclesBody = {
  branch_id?: number;
  code: string;
  is_active?: boolean;
  model?: string;
  notes?: string;
  plate_number: string;
  status?: string;
};

/** Response of `POST /api/vehicles` (no capture: keys from backend code only). */
export type PostVehiclesResponse = {
  branch_id?: unknown;
  code?: unknown;
  id?: unknown;
  is_active?: unknown;
  message?: unknown;
  model?: unknown;
  notes?: unknown;
  plate_number?: unknown;
  status?: unknown;
};

/** Body of `PATCH /api/vehicles/{vehicle}` (from the backend validation rules). */
export type PatchVehiclesVehicleBody = {
  branch_id?: number;
  code?: string;
  is_active?: boolean;
  model?: string;
  notes?: string;
  plate_number?: string;
  status?: string;
};

/** Response of `PATCH /api/vehicles/{vehicle}` (no capture: keys from backend code only). */
export type PatchVehiclesVehicleResponse = {
  branch_id?: unknown;
  code?: unknown;
  id?: unknown;
  is_active?: unknown;
  message?: unknown;
  model?: unknown;
  notes?: unknown;
  plate_number?: unknown;
  status?: unknown;
};

/** Response of `GET /api/vehicles/{vehicle}/assignments` (from live captures). */
export type GetVehiclesVehicleAssignmentsResponse = {
  success: boolean;
  data: {
    vehicle: {
      id: number;
      branch_id: number;
      code: string;
      plate_number: string;
      model: string;
      status: string;
      notes: null;
      is_active: boolean;
    };
    salesmen: {
      id: number;
      employee_id: number;
      employee: string;
      start_date: string;
      end_date: null;
      is_active: boolean;
    }[];
    drivers: {
      id: number;
      employee_id: number;
      employee: string;
      start_date: string;
      end_date: null;
      is_active: boolean;
    }[];
  };
};

/** Body of `POST /api/vehicles/{vehicle}/assignments/salesman` (from the backend validation rules). */
export type PostVehiclesVehicleAssignmentsSalesmanBody = {
  end_date?: string;
  salesman_id: number;
  start_date: string;
};

/** Response of `POST /api/vehicles/{vehicle}/assignments/salesman` (no capture: keys from backend code only). */
export type PostVehiclesVehicleAssignmentsSalesmanResponse = {
  employee_id?: unknown;
  end_date?: unknown;
  id?: unknown;
  message?: unknown;
  salesman_id?: unknown;
  start_date?: unknown;
};

/** Body of `POST /api/vehicles/{vehicle}/assignments/driver` (from the backend validation rules). */
export type PostVehiclesVehicleAssignmentsDriverBody = {
  driver_id: number;
  end_date?: string;
  start_date: string;
};

/** Response of `POST /api/vehicles/{vehicle}/assignments/driver` (no capture: keys from backend code only). */
export type PostVehiclesVehicleAssignmentsDriverResponse = {
  driver_id?: unknown;
  employee_id?: unknown;
  end_date?: unknown;
  id?: unknown;
  message?: unknown;
  start_date?: unknown;
};

/** Body of `POST /api/vehicles/{vehicle}/assignments/salesman/{assignment}/end` (from the backend validation rules). */
export type PostVehiclesVehicleAssignmentsSalesmanAssignmentEndBody = {
  end_date?: string;
};

/** Response of `POST /api/vehicles/{vehicle}/assignments/salesman/{assignment}/end` (no capture: keys from backend code only). */
export type PostVehiclesVehicleAssignmentsSalesmanAssignmentEndResponse = {
  employee_id?: unknown;
  end_date?: unknown;
  id?: unknown;
  message?: unknown;
  start_date?: unknown;
};

/** Body of `POST /api/vehicles/{vehicle}/assignments/driver/{assignment}/end` (from the backend validation rules). */
export type PostVehiclesVehicleAssignmentsDriverAssignmentEndBody = {
  end_date?: string;
};

/** Response of `POST /api/vehicles/{vehicle}/assignments/driver/{assignment}/end` (no capture: keys from backend code only). */
export type PostVehiclesVehicleAssignmentsDriverAssignmentEndResponse = {
  employee_id?: unknown;
  end_date?: unknown;
  id?: unknown;
  message?: unknown;
  start_date?: unknown;
};
