/** How a value is displayed. Nothing here computes; it only formats what the backend sent. */
export type FieldKind = 'money' | 'date' | 'datetime' | 'percent' | 'enum' | 'number' | 'boolean' | 'text' | 'branch';

export interface FieldDef {
  label: string;
  kind?: FieldKind;
}

/*
 * Keyed by the backend's JSON key. One key means the same thing in every report, so one entry
 * serves all of them. A key missing here shows its raw English name: that is the signal to add it.
 */
export const FIELDS: Record<string, FieldDef> = {
  // Structure (section titles)
  data: { label: 'البيانات' },
  rows: { label: 'التفاصيل' },
  totals: { label: 'الإجمالي' },
  summary: { label: 'الملخص' },
  compared_with: { label: 'مقارنة بفترة' },
  day: { label: 'اليوم' },
  collections: { label: 'التحصيلات' },
  deposits: { label: 'الإيداعات' },
  denominations: { label: 'الفئات' },
  remittance: { label: 'التوريد' },
  integrity: { label: 'ملاحظات المراجعة' },
  buckets: { label: 'الشرائح' },
  salesman: { label: 'المندوب' },
  period: { label: 'الفترة' },
  vouchers: { label: 'البونات' },
  rooms: { label: 'الغرف' },
  cold_room: { label: 'غرفة التبريد' },
  readings: { label: 'القراءات' },
  unavailable_columns: { label: 'أعمدة غير متاحة' },
  meta: { label: 'الصفحات' },

  // Branch and identity
  branch_id: { label: 'الفرع', kind: 'branch' },
  code: { label: 'الكود' },
  name: { label: 'الاسم' },
  name_ar: { label: 'الاسم' },
  name_en: { label: 'الاسم بالإنجليزية' },
  customer_name: { label: 'العميل' },
  employee_code: { label: 'كود الموظف' },
  supervisor: { label: 'المشرف' },
  category: { label: 'الفئة' },
  type: { label: 'النوع', kind: 'enum' },
  status: { label: 'الحالة', kind: 'enum' },
  scope: { label: 'النطاق', kind: 'enum' },
  group: { label: 'التجميع', kind: 'enum' },
  sorted_by: { label: 'الترتيب حسب', kind: 'enum' },
  valued_at: { label: 'التقييم بسعر', kind: 'enum' },
  normal_balance: { label: 'الطبيعة', kind: 'enum' },
  includes: { label: 'يشمل' },
  notes: { label: 'ملاحظات' },
  is_active: { label: 'نشط', kind: 'boolean' },
  is_assigned: { label: 'مُسند', kind: 'boolean' },
  is_postable: { label: 'يقبل القيد', kind: 'boolean' },
  balanced: { label: 'متوازن', kind: 'boolean' },
  editable: { label: 'قابل للتعديل', kind: 'boolean' },
  monitored_only: { label: 'مراقبة فقط', kind: 'boolean' },

  // Dates and people who acted
  period_start: { label: 'من', kind: 'date' },
  period_end: { label: 'إلى', kind: 'date' },
  from: { label: 'من', kind: 'date' },
  to: { label: 'إلى', kind: 'date' },
  up_to: { label: 'حتى', kind: 'date' },
  as_of: { label: 'حتى تاريخ', kind: 'date' },
  as_of_date: { label: 'حتى تاريخ', kind: 'date' },
  team_as_of: { label: 'الفريق حتى', kind: 'date' },
  business_date: { label: 'يوم العمل', kind: 'date' },
  last_working_day: { label: 'آخر يوم عمل', kind: 'date' },
  window_start: { label: 'بداية الفترة', kind: 'date' },
  starts_on: { label: 'يبدأ', kind: 'date' },
  ends_on: { label: 'ينتهي', kind: 'date' },
  oldest_open_due_date: { label: 'أقدم استحقاق مفتوح', kind: 'date' },
  expected_at: { label: 'العميل المتوقع' },
  counted_by: { label: 'عدّها' },
  counted_at: { label: 'وقت العدّ', kind: 'datetime' },
  remitted_by: { label: 'وردها' },
  remitted_at: { label: 'وقت التوريد', kind: 'datetime' },
  confirmed_by: { label: 'أكدها' },
  confirmed_at: { label: 'وقت التأكيد', kind: 'datetime' },
  closed_by: { label: 'أغلقها' },
  closed_at: { label: 'وقت الإغلاق', kind: 'datetime' },
  verified_by: { label: 'راجعها' },
  verified_at: { label: 'وقت المراجعة', kind: 'datetime' },
  journal_entry_no: { label: 'رقم القيد' },
  entry_no: { label: 'رقم القيد' },
  entry_date: { label: 'تاريخ القيد', kind: 'date' },
  total_debit: { label: 'إجمالي المدين', kind: 'money' },
  total_credit: { label: 'إجمالي الدائن', kind: 'money' },
  account_name: { label: 'الحساب' },

  // Working days and targets
  working_days: { label: 'أيام العمل', kind: 'number' },
  working_days_elapsed: { label: 'أيام عمل مضت', kind: 'number' },
  working_days_remaining: { label: 'أيام عمل متبقية', kind: 'number' },
  time_gone_percent: { label: 'نسبة الوقت المنقضي', kind: 'percent' },
  nps_target: { label: 'مستهدف NPS', kind: 'number' },
  nps_actual: { label: 'فعلي NPS', kind: 'number' },
  nps_percent: { label: 'نسبة NPS', kind: 'percent' },
  invoice_target: { label: 'مستهدف الفواتير', kind: 'number' },
  invoice_actual: { label: 'فعلي الفواتير', kind: 'number' },
  invoice_percent: { label: 'نسبة الفواتير', kind: 'percent' },
  target_amount: { label: 'المستهدف', kind: 'money' },
  own_target_amount: { label: 'المستهدف الشخصي', kind: 'money' },
  own_achievement_percent: { label: 'نسبة التحقيق الشخصي', kind: 'percent' },
  achievement_percent: { label: 'نسبة التحقيق', kind: 'percent' },
  remaining_amount: { label: 'المتبقي', kind: 'money' },
  new_customers: { label: 'عملاء جدد', kind: 'number' },
  drop_size: { label: 'متوسط الفاتورة', kind: 'money' },

  // Counts
  products: { label: 'الأصناف', kind: 'number' },
  products_sold: { label: 'أصناف مباعة', kind: 'number' },
  invoices: { label: 'الفواتير', kind: 'number' },
  invoice_count: { label: 'عدد الفواتير', kind: 'number' },
  customers: { label: 'العملاء', kind: 'number' },
  customer_count: { label: 'عدد العملاء', kind: 'number' },
  would_import: { label: 'سيُستورد', kind: 'number' },
  rejected: { label: 'مرفوض', kind: 'number' },
  reps: { label: 'المناديب', kind: 'number' },
  reps_who_sold: { label: 'مناديب باعوا', kind: 'number' },
  supervisors: { label: 'المشرفون', kind: 'number' },
  team_size: { label: 'حجم الفريق', kind: 'number' },
  accounts: { label: 'الحسابات', kind: 'number' },
  expenses: { label: 'المصاريف', kind: 'number' },
  count: { label: 'العدد', kind: 'number' },
  handover_count: { label: 'عدد التسليمات', kind: 'number' },
  pending_session_count: { label: 'جلسات لم تُسلَّم', kind: 'number' },
  over_limit_accounts: { label: 'حسابات تجاوزت الحد', kind: 'number' },
  open_receivables_count: { label: 'ذمم مفتوحة', kind: 'number' },
  overdue_receivables_count: { label: 'ذمم متأخرة', kind: 'number' },
  salesbuzz_compared_trips: { label: 'رحلات مقارنة بـ SalesBuzz', kind: 'number' },
  issued: { label: 'صادرة', kind: 'number' },
  redeemed: { label: 'مصروفة', kind: 'number' },
  cancelled: { label: 'ملغاة', kind: 'number' },
  open: { label: 'مفتوحة', kind: 'number' },
  critical: { label: 'حرجة', kind: 'number' },
  breaches: { label: 'التجاوزات', kind: 'number' },
  hours_not_read: { label: 'ساعات بلا قراءة', kind: 'number' },
  total_litres: { label: 'إجمالي اللترات', kind: 'number' },

  // Pagination (meta)
  total: { label: 'الإجمالي', kind: 'money' },
  per_page: { label: 'لكل صفحة', kind: 'number' },
  current_page: { label: 'الصفحة', kind: 'number' },
  last_page: { label: 'آخر صفحة', kind: 'number' },

  // Stock quantities and cover
  cartons: { label: 'كراتين', kind: 'number' },
  pieces: { label: 'قطع', kind: 'number' },
  bonus_cartons: { label: 'كراتين بونص', kind: 'number' },
  warehouse_cartons: { label: 'كراتين المخزن', kind: 'number' },
  vehicle_cartons: { label: 'كراتين العربيات', kind: 'number' },
  total_cartons: { label: 'إجمالي الكراتين', kind: 'number' },
  cartons_out: { label: 'كراتين خارجة', kind: 'number' },
  pieces_out: { label: 'قطع خارجة', kind: 'number' },
  cartons_per_day: { label: 'كراتين في اليوم', kind: 'number' },
  days_of_cover: { label: 'أيام التغطية', kind: 'number' },
  window_days: { label: 'أيام الفترة', kind: 'number' },
  low_days: { label: 'حد الانخفاض (أيام)', kind: 'number' },
  days: { label: 'الأيام', kind: 'number' },
  OUT: { label: 'نفد', kind: 'number' },
  LOW: { label: 'منخفض', kind: 'number' },
  DEAD: { label: 'راكد', kind: 'number' },
  OK: { label: 'سليم', kind: 'number' },

  // Money
  trade_price: { label: 'سعر الجملة', kind: 'money' },
  warehouse_value: { label: 'قيمة المخزن', kind: 'money' },
  vehicle_value: { label: 'قيمة العربيات', kind: 'money' },
  total_value: { label: 'إجمالي القيمة', kind: 'money' },
  total_value_at_cost: { label: 'القيمة بالتكلفة', kind: 'money' },
  sales_amount: { label: 'المبيعات', kind: 'money' },
  cash_amount: { label: 'نقدي', kind: 'money' },
  credit_amount: { label: 'آجل', kind: 'money' },
  tpp_amount: { label: 'TPP', kind: 'money' },
  discount_amount: { label: 'الخصم', kind: 'money' },
  min_invoice_amount: { label: 'حد أدنى للفاتورة', kind: 'money' },
  collected: { label: 'المحصّل', kind: 'money' },
  cash: { label: 'نقدي', kind: 'money' },
  cheque: { label: 'شيك', kind: 'money' },
  transfer: { label: 'تحويل', kind: 'money' },
  card: { label: 'بطاقة', kind: 'money' },
  other: { label: 'أخرى', kind: 'money' },
  fridge_received: { label: 'تأمين ثلاجات مستلم', kind: 'money' },
  fridge_refunded: { label: 'تأمين ثلاجات مرتجع', kind: 'money' },
  expenses_amount: { label: 'المصاريف', kind: 'money' },
  net_cash_amount: { label: 'صافي النقدية', kind: 'money' },
  counted_cash_amount: { label: 'النقدية المعدودة', kind: 'money' },
  counted_amount: { label: 'المعدود', kind: 'money' },
  variance_amount: { label: 'الفرق', kind: 'money' },
  count_variance_amount: { label: 'فرق العدّ', kind: 'money' },
  remitted_to_bank_amount: { label: 'مورد للبنك', kind: 'money' },
  expected_amount: { label: 'المتوقع', kind: 'money' },
  remitted_amount: { label: 'المورد', kind: 'money' },
  received_amount: { label: 'المستلم', kind: 'money' },
  handheld_invoice_total: { label: 'فواتير الجهاز', kind: 'money' },
  credit_total: { label: 'إجمالي الآجل', kind: 'money' },
  shortage_amount: { label: 'العجز', kind: 'money' },
  excess_amount: { label: 'الزيادة', kind: 'money' },
  source_variance_amount: { label: 'فرق المصدر', kind: 'money' },
  debit: { label: 'مدين', kind: 'money' },
  credit: { label: 'دائن', kind: 'money' },
  outstanding: { label: 'المستحق', kind: 'money' },
  on_trips: { label: 'على الرحلات', kind: 'money' },
  branch_only: { label: 'على الفرع', kind: 'money' },
  exposure: { label: 'المديونية', kind: 'money' },
  overdue: { label: 'متأخر', kind: 'money' },
  unbilled: { label: 'لم يُفوتر', kind: 'money' },
  not_due: { label: 'لم يستحق', kind: 'money' },
  due_today: { label: 'مستحق اليوم', kind: 'money' },
  overdue_1_7_days: { label: 'متأخر 1–7 أيام', kind: 'money' },
  overdue_8_15_days: { label: 'متأخر 8–15 يوم', kind: 'money' },
  overdue_16_30_days: { label: 'متأخر 16–30 يوم', kind: 'money' },
  overdue_31_60_days: { label: 'متأخر 31–60 يوم', kind: 'money' },
  overdue_61_plus_days: { label: 'متأخر أكثر من 60 يوم', kind: 'money' },
  credit_given_this_month: { label: 'آجل هذا الشهر', kind: 'money' },
  collected_this_month: { label: 'محصّل هذا الشهر', kind: 'money' },
  total_outstanding: { label: 'إجمالي المستحق', kind: 'money' },
  brought_forward: { label: 'رصيد مرحّل', kind: 'money' },
  not_due_amount: { label: 'لم يستحق', kind: 'money' },
  due_today_amount: { label: 'مستحق اليوم', kind: 'money' },
  overdue_amount: { label: 'متأخر', kind: 'money' },
  unbilled_amount: { label: 'لم يُفوتر', kind: 'money' },
  total_amount: { label: 'الإجمالي', kind: 'money' },

  // Cold chain
  min_celsius: { label: 'أدنى حرارة °م' },
  max_celsius: { label: 'أعلى حرارة °م' },
  reading_hour: { label: 'ساعة القراءة', kind: 'number' },
  celsius: { label: 'الحرارة °م' },

  /*
   * Task 6: keys that stay hidden behind empty demo data. Collected by reading the backend
   * presenters (see task-6-report.md) rather than live samples, since every list below returns
   * `[]` on the seeded local branch.
   */

  // Nested containers (become section titles or grouped sub-columns)
  customer: { label: 'العميل' },
  vehicle: { label: 'العربية' },
  product: { label: 'المنتج' },
  session: { label: 'الجلسة' },
  items: { label: 'البنود' },
  next_service: { label: 'الصيانة القادمة' },
  with_customer: { label: 'مع العميل' },
  payment: { label: 'السداد' },
  subject: { label: 'المرجع' },
  changed_by: { label: 'عدّلها' },
  approved_by: { label: 'اعتمده' },
  commission: { label: 'العمولة' },

  // Identifiers and free text
  sale_no: { label: 'رقم الفاتورة' },
  invoice_no: { label: 'رقم الفاتورة' },
  salesbuzz_invoice_no: { label: 'رقم فاتورة SalesBuzz' },
  collection_no: { label: 'رقم التحصيل' },
  handover_no: { label: 'رقم التسليم' },
  cheque_no: { label: 'رقم الشيك' },
  transfer_reference: { label: 'مرجع التحويل' },
  return_no: { label: 'رقم المرتجع' },
  visit_no: { label: 'رقم الزيارة' },
  no_sale_reason: { label: 'سبب عدم البيع' },
  voucher_no: { label: 'رقم البون' },
  expense_no: { label: 'رقم المصروف' },
  driver: { label: 'السائق' },
  issued_by: { label: 'صرفها' },
  station: { label: 'المحطة' },
  redeemed_by: { label: 'استخدمها' },
  route: { label: 'الخط' },
  seal_no: { label: 'رقم الرصاصة' },
  recorded_by: { label: 'سجّلها' },
  detail: { label: 'التفاصيل' },
  employee: { label: 'الموظف' },
  verification_notes: { label: 'ملاحظات المراجعة' },
  review_notes: { label: 'ملاحظات المراجعة' },
  payroll_period: { label: 'فترة الرواتب' },
  written_off_by: { label: 'شطبها' },
  write_off_reason: { label: 'سبب الشطب' },
  stocktake_no: { label: 'رقم الجرد' },
  plate_number: { label: 'رقم اللوحة' },
  model: { label: 'الموديل' },
  capacity: { label: 'السعة' },
  warehouse: { label: 'المخزن' },
  reviewed_by: { label: 'راجعها' },
  request_no: { label: 'رقم الطلب' },
  supplier: { label: 'المورد' },
  supplier_name: { label: 'المورد' },
  document_no: { label: 'رقم المستند' },
  receipt_no: { label: 'رقم الاستلام' },
  delivery_note_no: { label: 'رقم إذن التسليم' },
  payment_reference: { label: 'مرجع التحويل' },
  reference: { label: 'المرجع' },
  lot_no: { label: 'رقم اللوت' },
  product_code: { label: 'كود المنتج' },
  message: { label: 'الرسالة' },
  subject_type: { label: 'نوع السجل' },
  subject_name: { label: 'اسم السجل' },
  field: { label: 'الحقل' },
  old_value: { label: 'القيمة القديمة' },
  new_value: { label: 'القيمة الجديدة' },
  receivable_no: { label: 'رقم الذمة' },
  delivered_on: { label: 'تاريخ التوصيلة', kind: 'date' },
  earliest_delivery: { label: 'أول توصيلة', kind: 'date' },
  latest_delivery: { label: 'آخر توصيلة', kind: 'date' },
  unbilled_total: { label: 'غير مفوتر', kind: 'money' },

  // Enums
  payment_type: { label: 'طريقة الدفع', kind: 'enum' },
  funding_source: { label: 'جهة التمويل', kind: 'enum' },
  payment_method: { label: 'وسيلة التحصيل', kind: 'enum' },
  clearance_status: { label: 'حالة التحصيل', kind: 'enum' },
  reason: { label: 'السبب', kind: 'enum' },
  requested_action: { label: 'الإجراء المطلوب', kind: 'enum' },
  direction: { label: 'الاتجاه', kind: 'enum' },
  shift: { label: 'الوردية', kind: 'enum' },
  difference_type: { label: 'نوع الفرق', kind: 'enum' },
  source: { label: 'المصدر', kind: 'enum' },
  verification_status: { label: 'حالة المراجعة', kind: 'enum' },
  period_type: { label: 'دورية الجرد', kind: 'enum' },
  expected_status: { label: 'الحالة المتوقعة', kind: 'enum' },
  found_status: { label: 'الحالة الفعلية', kind: 'enum' },
  verdict: { label: 'النتيجة', kind: 'enum' },
  reasons: { label: 'الأسباب', kind: 'enum' },
  payment_status: { label: 'حالة السداد', kind: 'enum' },
  aging_status: { label: 'حالة التقادم', kind: 'enum' },
  aging_bucket: { label: 'شريحة التقادم', kind: 'enum' },

  // Dates
  effective_from: { label: 'ساري من', kind: 'date' },
  effective_to: { label: 'ساري حتى', kind: 'date' },
  due_date: { label: 'تاريخ الاستحقاق', kind: 'date' },
  cheque_due_date: { label: 'استحقاق الشيك', kind: 'date' },
  issued_on: { label: 'تاريخ الصرف', kind: 'date' },
  redeemed_on: { label: 'تاريخ الاستخدام', kind: 'date' },
  licence_expires_on: { label: 'انتهاء الرخصة', kind: 'date' },
  insurance_expires_on: { label: 'انتهاء التأمين', kind: 'date' },
  due_on: { label: 'تاريخ الاستحقاق', kind: 'date' },
  placed_on: { label: 'تاريخ التركيب', kind: 'date' },
  returned_on: { label: 'تاريخ السحب', kind: 'date' },
  requested_for: { label: 'مطلوب بتاريخ', kind: 'date' },
  expense_date: { label: 'تاريخ المصروف', kind: 'date' },
  received_on: { label: 'تاريخ الاستلام', kind: 'date' },
  paid_on: { label: 'تاريخ السداد', kind: 'date' },
  best_before: { label: 'تاريخ الانتهاء', kind: 'date' },

  // Datetimes
  collected_at: { label: 'وقت التحصيل', kind: 'datetime' },
  returned_at: { label: 'وقت المرتجع', kind: 'datetime' },
  created_at: { label: 'وقت الإنشاء', kind: 'datetime' },
  updated_at: { label: 'وقت آخر تعديل', kind: 'datetime' },
  started_at: { label: 'وقت البدء', kind: 'datetime' },
  completed_at: { label: 'وقت الانتهاء', kind: 'datetime' },
  occurred_at: { label: 'وقت الحركة', kind: 'datetime' },
  checked_in_at: { label: 'وقت الحضور', kind: 'datetime' },
  checked_out_at: { label: 'وقت الانصراف', kind: 'datetime' },
  written_off_at: { label: 'وقت الشطب', kind: 'datetime' },
  sent_at: { label: 'وقت الإرسال', kind: 'datetime' },
  reviewed_at: { label: 'وقت المراجعة', kind: 'datetime' },
  changed_at: { label: 'وقت التعديل', kind: 'datetime' },
  sold_at: { label: 'وقت البيع', kind: 'datetime' },

  // Counts and quantities
  line_count: { label: 'عدد البنود', kind: 'number' },
  sales_count: { label: 'عدد المبيعات', kind: 'number' },
  collections_count: { label: 'عدد التحصيلات', kind: 'number' },
  returns_count: { label: 'عدد المرتجعات', kind: 'number' },
  litres: { label: 'اللترات', kind: 'number' },
  odometer_reading: { label: 'قراءة العداد', kind: 'number' },
  fuel_issued_litres: { label: 'سولار مصروف (لتر)', kind: 'number' },
  distance_km: { label: 'المسافة (كم)', kind: 'number' },
  quantity_cartons: { label: 'الكمية (كراتين)', kind: 'number' },
  days_left: { label: 'الأيام المتبقية', kind: 'number' },
  due_at_km: { label: 'الاستحقاق عند (كم)', kind: 'number' },
  km_remaining: { label: 'الكيلومترات المتبقية', kind: 'number' },
  system_cartons: { label: 'كراتين النظام', kind: 'number' },
  counted_cartons: { label: 'كراتين معدودة', kind: 'number' },
  difference: { label: 'الفرق', kind: 'number' },
  lines: { label: 'عدد الأصناف', kind: 'number' },
  short_lines: { label: 'أصناف بالعجز', kind: 'number' },
  over_lines: { label: 'أصناف بالزيادة', kind: 'number' },
  not_counted_yet: { label: 'لم تُجرد بعد', kind: 'number' },
  matched: { label: 'مطابقة', kind: 'number' },
  state_differs: { label: 'حالتها مختلفة', kind: 'number' },
  not_found: { label: 'غير موجودة', kind: 'number' },
  ordered_cartons: { label: 'كراتين مطلوبة', kind: 'number' },
  received_cartons: { label: 'كراتين مستلمة', kind: 'number' },
  variance: { label: 'الفرق', kind: 'number' },
  pos_target: { label: 'مستهدف POS', kind: 'number' },
  days_overdue: { label: 'أيام التأخير', kind: 'number' },
  delivery_count: { label: 'عدد التسليمات', kind: 'number' },
  units_per_carton: { label: 'قطع في الكرتونة', kind: 'number' },

  /*
   * Fix round 1: the nps/invoices/new_customers/drop_size sheets in
   * `SalesPerformanceReportService::rowFor` (sales_performance, team_performance, supervisors,
   * my_performance) reuse these same child keys inside each metric block, but the value type
   * changes per parent — nps and drop_size are money, invoices and new_customers are plain
   * counts. A single global kind would mis-render one or the other, so these carry no kind
   * (label only): a money-string value still renders correctly with no kind (plain text), and a
   * number still renders correctly via the numeric fallback in ReportValue. Only the percent
   * children are always ratios regardless of parent, so those get kind 'percent'.
   */
  target: { label: 'المستهدف' },
  actual: { label: 'الفعلي' },
  day_target: { label: 'مستهدف اليوم' },
  last_day: { label: 'آخر يوم' },
  remaining: { label: 'المتبقي' },
  percent: { label: 'النسبة', kind: 'percent' },
  last_day_percent: { label: 'نسبة آخر يوم', kind: 'percent' },
  percent_vs_time_gone: { label: 'النسبة مقابل الوقت المنقضي', kind: 'percent' },
  achieved_percent: { label: 'نسبة التحقيق', kind: 'percent' },

  // Money
  amount: { label: 'المبلغ', kind: 'money' },
  subtotal: { label: 'الإجمالي قبل الخصم', kind: 'money' },
  discount_total: { label: 'إجمالي الخصم', kind: 'money' },
  net_total: { label: 'الصافي', kind: 'money' },
  unit_cost: { label: 'تكلفة الوحدة', kind: 'money' },
  settled_amount: { label: 'المسدد', kind: 'money' },
  written_off_amount: { label: 'المشطوب', kind: 'money' },
  deposit_amount: { label: 'قيمة التأمين', kind: 'money' },
  refund_amount: { label: 'المردود', kind: 'money' },
  difference_value: { label: 'قيمة الفرق', kind: 'money' },
  shortage_value: { label: 'قيمة العجز', kind: 'money' },
  excess_value: { label: 'قيمة الزيادة', kind: 'money' },
  drop_size_target: { label: 'مستهدف متوسط الفاتورة', kind: 'money' },
  nps: { label: 'NPS', kind: 'money' },
  pos: { label: 'POS', kind: 'money' },
  original_amount: { label: 'المبلغ الأصلي', kind: 'money' },
  paid_amount: { label: 'المسدد', kind: 'money' },
  commission_amount: { label: 'العمولة', kind: 'money' },
  price_difference_amount: { label: 'فرق السعر', kind: 'money' },

  // Booleans
  refrigeration_ok: { label: 'التبريد سليم', kind: 'boolean' },
  confirmed: { label: 'مؤكد', kind: 'boolean' },
  has_variance: { label: 'به فرق', kind: 'boolean' },
  qualifies: { label: 'مستحق', kind: 'boolean' },
  // Every other key the API returns (detail views show all keys).
  account: { label: 'الحساب' },
  account_customer_id: { label: 'رقم حساب العميل' },
  acknowledged_at: { label: 'وقت الاطلاع', kind: 'datetime' },
  acknowledged_by: { label: 'اطلع عليه' },
  actions: { label: 'الإجراءات' },
  active_on: { label: 'ساري في', kind: 'date' },
  actual_quantity_cartons: { label: 'الكمية الفعلية (كرتونة)', kind: 'number' },
  address: { label: 'العنوان' },
  aging: { label: 'أعمار الديون' },
  allocations: { label: 'التوزيع' },
  allowed_filters: { label: 'الفلاتر المتاحة' },
  amount_written_off: { label: 'المبلغ المعدوم', kind: 'money' },
  area: { label: 'المنطقة' },
  area_id: { label: 'رقم المنطقة' },
  areas: { label: 'المناطق' },
  assigned_salesmen_count: { label: 'عدد المندوبين المسندين', kind: 'number' },
  assignment: { label: 'الإسناد' },
  attachable_id: { label: 'رقم السجل المرفق به' },
  attachable_type: { label: 'نوع السجل المرفق به' },
  attachment_count: { label: 'عدد المرفقات', kind: 'number' },
  attachments: { label: 'المرفقات' },
  available: { label: 'المتاح', kind: 'number' },
  balance: { label: 'الرصيد', kind: 'money' },
  barcode: { label: 'الباركود' },
  billing_cycle: { label: 'دورة الفوترة', kind: 'enum' },
  bonus_quantity: { label: 'كمية البونص', kind: 'number' },
  branch: { label: 'الفرع' },
  branch_required: { label: 'يتطلب اختيار فرع', kind: 'boolean' },
  branch_scoped: { label: 'لكل فرع على حدة', kind: 'boolean' },
  by: { label: 'حتى تاريخ', kind: 'date' },
  by_category: { label: 'حسب الفئة' },
  by_expected_status: { label: 'حسب الحالة المتوقعة' },
  capabilities: { label: 'الصلاحيات' },
  captured_at: { label: 'وقت التصوير', kind: 'datetime' },
  cartons_over: { label: 'كراتين زيادة', kind: 'number' },
  cartons_short: { label: 'كراتين عجز', kind: 'number' },
  cash_closing: { label: 'إقفال النقدية' },
  cash_closing_ids: { label: 'أرقام إقفالات النقدية' },
  cash_movement_id: { label: 'رقم حركة النقدية' },
  chain: { label: 'السلسلة' },
  change_percent: { label: 'نسبة التغير', kind: 'percent' },
  channel: { label: 'القناة' },
  chassis_number: { label: 'رقم الشاسيه' },
  checksum: { label: 'رمز التحقق' },
  cheque_bank: { label: 'بنك الشيك' },
  city: { label: 'المدينة' },
  client_transaction_uuid: { label: 'معرّف العملية' },
  closing_balance: { label: 'رصيد الإقفال', kind: 'money' },
  closing_no: { label: 'رقم الإقفال' },
  cold_chain: { label: 'سلسلة التبريد' },
  cold_room_id: { label: 'رقم غرفة التبريد' },
  commit: { label: 'حفظ' },
  company_wide: { label: 'على مستوى الشركة', kind: 'boolean' },
  compliance: { label: 'الالتزام' },
  condition: { label: 'الحالة الفنية', kind: 'enum' },
  costs: { label: 'التكاليف' },
  counted: { label: 'المعدود', kind: 'number' },
  counted_quantity_cartons: { label: 'الكمية المعدودة (كرتونة)', kind: 'number' },
  created_by: { label: 'أنشأه' },
  created_session_id: { label: 'رقم يومية الإنشاء' },
  credit_account: { label: 'حساب الآجل' },
  credit_days: { label: 'أيام الآجل', kind: 'number' },
  credit_limit: { label: 'حد الآجل', kind: 'money' },
  current_odometer: { label: 'العداد الحالي', kind: 'number' },
  customer_code: { label: 'كود العميل' },
  customer_id: { label: 'رقم العميل' },
  customer_replacement_id: { label: 'رقم الاستبدال' },
  customer_return: { label: 'المرتجع' },
  customer_return_id: { label: 'رقم المرتجع' },
  customer_return_item_id: { label: 'رقم بند المرتجع' },
  customer_type: { label: 'نوع العميل' },
  customer_visit_id: { label: 'رقم الزيارة' },
  customers_with_outstanding_balance: { label: 'عملاء عليهم رصيد', kind: 'number' },
  daily_session_id: { label: 'رقم اليومية' },
  date: { label: 'التاريخ', kind: 'date' },
  days_1_30: { label: '1–30 يوم', kind: 'money' },
  days_31_60: { label: '31–60 يوم', kind: 'money' },
  days_61_90: { label: '61–90 يوم', kind: 'money' },
  days_over_90: { label: 'أكثر من 90 يوم', kind: 'money' },
  delivered: { label: 'المسلَّم', kind: 'number' },
  delivered_at: { label: 'وقت التسليم', kind: 'datetime' },
  delivered_quantity_cartons: { label: 'الكمية المسلمة (كرتونة)', kind: 'number' },
  deliveries: { label: 'التسليمات' },
  delivery_customer_visit_id: { label: 'رقم زيارة التسليم' },
  delivery_visit: { label: 'زيارة التسليم' },
  description: { label: 'الوصف' },
  device_name: { label: 'اسم الجهاز' },
  difference_cartons: { label: 'الفرق (كرتونة)', kind: 'number' },
  discount_rate: { label: 'نسبة الخصم', kind: 'percent' },
  download_url: { label: 'رابط التحميل' },
  driver_id: { label: 'رقم السائق' },
  drivers: { label: 'السائقون' },
  drop_size_commission: { label: 'عمولة حجم الطلبية', kind: 'money' },
  email: { label: 'البريد الإلكتروني' },
  employee_id: { label: 'رقم الموظف' },
  end_date: { label: 'تاريخ الانتهاء', kind: 'date' },
  engine_number: { label: 'رقم الموتور' },
  entry_count: { label: 'عدد القيود', kind: 'number' },
  excess_quantity_cartons: { label: 'الزيادة (كرتونة)', kind: 'number' },
  expense_categories: { label: 'بنود المصروفات' },
  expense_category_id: { label: 'رقم بند المصروف' },
  expense_id: { label: 'رقم المصروف' },
  expires_at: { label: 'ينتهي في', kind: 'datetime' },
  file: { label: 'الملف' },
  file_size: { label: 'حجم الملف', kind: 'number' },
  fridge_deposits: { label: 'تأمينات الثلاجات' },
  fuel_litres: { label: 'لترات الوقود', kind: 'number' },
  fuel_type: { label: 'نوع الوقود' },
  fulfillment_source: { label: 'مصدر التنفيذ', kind: 'enum' },
  goods_receipts: { label: 'أذونات الاستلام' },
  gross_amount: { label: 'الإجمالي قبل الخصم', kind: 'money' },
  handover_id: { label: 'رقم التسليم' },
  has_login: { label: 'له حساب دخول', kind: 'boolean' },
  headroom: { label: 'المتاح من حد الآجل', kind: 'money' },
  hire_date: { label: 'تاريخ التعيين', kind: 'date' },
  id: { label: 'الرقم' },
  include_retired: { label: 'يشمل الموقوف', kind: 'boolean' },
  include_settled: { label: 'يشمل المسدد', kind: 'boolean' },
  inspection: { label: 'الفحص' },
  insurance_days_left: { label: 'أيام متبقية على التأمين', kind: 'number' },
  invoice_commission: { label: 'عمولة الفواتير', kind: 'money' },
  invoiced: { label: 'مفوتر', kind: 'money' },
  invoiced_on: { label: 'تاريخ الفوترة', kind: 'date' },
  is_credit_account: { label: 'حساب آجل', kind: 'boolean' },
  is_open: { label: 'مفتوح', kind: 'boolean' },
  is_route_expense: { label: 'مصروف خط سير', kind: 'boolean' },
  issue_no: { label: 'رقم إذن الصرف' },
  issued_at: { label: 'وقت الصرف', kind: 'datetime' },
  items_count: { label: 'عدد البنود', kind: 'number' },
  job_title: { label: 'المسمى الوظيفي' },
  key: { label: 'المفتاح' },
  last_counted: { label: 'آخر جرد' },
  latitude: { label: 'خط العرض' },
  licence_days_left: { label: 'أيام متبقية على الرخصة', kind: 'number' },
  limit: { label: 'الحد', kind: 'number' },
  lines_counted: { label: 'بنود معدودة', kind: 'number' },
  lines_over: { label: 'بنود بالزيادة', kind: 'number' },
  lines_short: { label: 'بنود بالعجز', kind: 'number' },
  litres_per_100km: { label: 'لتر لكل 100 كم', kind: 'number' },
  location: { label: 'الموقع' },
  locked: { label: 'مقفل', kind: 'boolean' },
  longitude: { label: 'خط الطول' },
  lots: { label: 'اللوطات' },
  make: { label: 'الماركة' },
  manager: { label: 'المدير' },
  manager_id: { label: 'رقم المدير' },
  measurement_complete: { label: 'القياس مكتمل', kind: 'boolean' },
  method: { label: 'الطريقة', kind: 'enum' },
  mime_type: { label: 'نوع الملف' },
  movement: { label: 'الحركة' },
  net_amount: { label: 'الصافي', kind: 'money' },
  next_due: { label: 'الاستحقاق القادم' },
  next_service_due_km: { label: 'الصيانة القادمة عند (كم)', kind: 'number' },
  next_service_due_on: { label: 'موعد الصيانة القادمة', kind: 'date' },
  nps_commission: { label: 'عمولة NPS', kind: 'money' },
  odometer_readings: { label: 'قراءات العداد' },
  odometer_readings_missing: { label: 'قراءات عداد ناقصة', kind: 'number' },
  oldest_unpaid_days: { label: 'أقدم دين (يوم)', kind: 'number' },
  only_overdue: { label: 'المتأخر فقط', kind: 'boolean' },
  open_only: { label: 'المفتوح فقط', kind: 'boolean' },
  open_visit: { label: 'الزيارة المفتوحة' },
  opening_balance: { label: 'رصيد أول المدة', kind: 'money' },
  opening_shortage_amount: { label: 'عجز أول المدة', kind: 'money' },
  optional: { label: 'اختياري' },
  original_name: { label: 'اسم الملف الأصلي' },
  original_sale: { label: 'الفاتورة الأصلية' },
  original_sale_id: { label: 'رقم الفاتورة الأصلية' },
  original_sale_item_id: { label: 'رقم بند الفاتورة الأصلية' },
  other_deposits_amount: { label: 'تأمينات أخرى', kind: 'money' },
  out_of_range: { label: 'خارج النطاق', kind: 'boolean' },
  outlet_count: { label: 'عدد المنافذ', kind: 'number' },
  outstanding_total: { label: 'إجمالي المستحق', kind: 'money' },
  over_limit: { label: 'تجاوز الحد', kind: 'boolean' },
  overdue_total: { label: 'إجمالي المتأخر', kind: 'money' },
  page: { label: 'الصفحة', kind: 'number' },
  parent_customer_id: { label: 'رقم الحساب الرئيسي' },
  parent_id: { label: 'رقم الأصل' },
  part_name: { label: 'اسم القطعة' },
  parts: { label: 'قطع الغيار' },
  parts_total: { label: 'إجمالي قطع الغيار', kind: 'money' },
  password: { label: 'كلمة المرور' },
  path: { label: 'المسار' },
  payload: { label: 'البيانات المرسلة' },
  payment_terms: { label: 'طريقة الدفع', kind: 'enum' },
  pending: { label: 'المعلق' },
  performed_on: { label: 'تاريخ التنفيذ', kind: 'date' },
  permissions: { label: 'الصلاحيات' },
  phone: { label: 'الهاتف' },
  placements: { label: 'الوضع عند العملاء' },
  pos_commission: { label: 'عمولة نقاط البيع', kind: 'money' },
  position_code: { label: 'الوظيفة', kind: 'enum' },
  posted: { label: 'مُرحّل', kind: 'boolean' },
  previous_cartons: { label: 'كراتين الفترة السابقة', kind: 'number' },
  previous_sales_amount: { label: 'مبيعات الفترة السابقة', kind: 'money' },
  price: { label: 'السعر', kind: 'money' },
  prices: { label: 'الأسعار' },
  problem: { label: 'المشكلة' },
  processed_at: { label: 'وقت المعالجة', kind: 'datetime' },
  processed_by: { label: 'عالجه' },
  product_id: { label: 'رقم الصنف' },
  product_name: { label: 'اسم الصنف' },
  progress: { label: 'التقدم' },
  q: { label: 'بحث' },
  qualifying_percent: { label: 'نسبة الاستحقاق', kind: 'percent' },
  quantity: { label: 'الكمية', kind: 'number' },
  quantity_pieces: { label: 'الكمية (قطعة)', kind: 'number' },
  raised: { label: 'مرفوع' },
  receipt_required: { label: 'يتطلب إيصال', kind: 'boolean' },
  receivable: { label: 'المديونية' },
  receivable_id: { label: 'رقم المديونية' },
  received_quantity_cartons: { label: 'الكمية المستلمة (كرتونة)', kind: 'number' },
  recorded_at: { label: 'وقت التسجيل', kind: 'datetime' },
  refrigerator: { label: 'الثلاجة' },
  refrigerator_code: { label: 'كود الثلاجة' },
  refrigerator_id: { label: 'رقم الثلاجة' },
  replacement_no: { label: 'رقم الاستبدال' },
  reports: { label: 'التقارير' },
  requested_by: { label: 'طلبه' },
  requested_quantity_cartons: { label: 'الكمية المطلوبة (كرتونة)', kind: 'number' },
  required: { label: 'مطلوب' },
  required_quantity_cartons: { label: 'الكمية المطلوبة (كرتونة)', kind: 'number' },
  requires_odometer: { label: 'يتطلب قراءة العداد', kind: 'boolean' },
  requires_vehicle: { label: 'يتطلب سيارة', kind: 'boolean' },
  restored_to_service: { label: 'عادت للخدمة', kind: 'boolean' },
  reverses_entry_id: { label: 'يعكس القيد رقم' },
  roles: { label: 'الأدوار' },
  room: { label: 'الغرفة' },
  route_completed_at: { label: 'وقت انتهاء خط السير', kind: 'datetime' },
  route_id: { label: 'رقم خط السير' },
  route_started_at: { label: 'وقت بدء خط السير', kind: 'datetime' },
  routes: { label: 'خطوط السير' },
  running: { label: 'الرصيد الجاري', kind: 'money' },
  sale_id: { label: 'رقم الفاتورة' },
  sales: { label: 'المبيعات' },
  sales_target_id: { label: 'رقم التارجت' },
  salesbuzz_code: { label: 'كود SalesBuzz' },
  salesbuzz_invoice_total: { label: 'إجمالي فاتورة SalesBuzz', kind: 'money' },
  salesman_counted_quantity_cartons: { label: 'عدّ المندوب (كرتونة)', kind: 'number' },
  salesman_id: { label: 'رقم المندوب' },
  salesman_received_at: { label: 'وقت استلام المندوب', kind: 'datetime' },
  salesman_stock_request: { label: 'طلب البضاعة' },
  salesman_stock_request_id: { label: 'رقم طلب البضاعة' },
  salesmen: { label: 'المندوبون' },
  search: { label: 'بحث' },
  sellable: { label: 'قابل للبيع', kind: 'boolean' },
  service_history: { label: 'سجل الصيانة' },
  service_no: { label: 'رقم الصيانة' },
  session_no: { label: 'رقم اليومية' },
  severity: { label: 'الأهمية', kind: 'enum' },
  share_percent: { label: 'النسبة', kind: 'percent' },
  shelf_life_days: { label: 'مدة الصلاحية (يوم)', kind: 'number' },
  shortage_id: { label: 'رقم العجز' },
  shortage_quantity_cartons: { label: 'العجز (كرتونة)', kind: 'number' },
  sort: { label: 'الترتيب' },
  sort_order: { label: 'ترتيب العرض', kind: 'number' },
  start_date: { label: 'تاريخ البدء', kind: 'date' },
  start_latitude: { label: 'خط العرض عند البدء' },
  start_longitude: { label: 'خط الطول عند البدء' },
  stock_closing: { label: 'جرد نهاية اليوم' },
  stock_issue_id: { label: 'رقم إذن الصرف' },
  stop_count: { label: 'عدد المحطات', kind: 'number' },
  stops: { label: 'المحطات' },
  storage_temp_max: { label: 'أقصى حرارة تخزين', kind: 'number' },
  storage_temp_min: { label: 'أدنى حرارة تخزين', kind: 'number' },
  storekeeper_received_quantity_cartons: { label: 'استلام أمين المخزن (كرتونة)', kind: 'number' },
  subject_id: { label: 'رقم السجل' },
  submitted_at: { label: 'وقت الإرسال', kind: 'datetime' },
  submitted_by: { label: 'أرسله' },
  subordinate_id: { label: 'رقم المرؤوس' },
  subordinates: { label: 'المرؤوسون' },
  success: { label: 'نجاح', kind: 'boolean' },
  supervisor_id: { label: 'رقم المشرف' },
  supplier_id: { label: 'رقم المورد' },
  supply_request_id: { label: 'رقم طلب التوريد' },
  synced_at: { label: 'وقت المزامنة', kind: 'datetime' },
  system_quantity_cartons: { label: 'كمية النظام (كرتونة)', kind: 'number' },
  tank_capacity_litres: { label: 'سعة الخزان (لتر)', kind: 'number' },
  tax_rate: { label: 'نسبة الضريبة', kind: 'percent' },
  tax_registration_no: { label: 'الرقم الضريبي' },
  team_summary: { label: 'ملخص الفريق' },
  title_ar: { label: 'العنوان' },
  title_en: { label: 'العنوان بالإنجليزية' },
  token: { label: 'رمز الدخول' },
  total_active: { label: 'إجمالي المفعّل', kind: 'number' },
  total_overdue: { label: 'إجمالي المتأخر', kind: 'money' },
  trip: { label: 'الرحلة' },
  trip_no: { label: 'رقم الرحلة' },
  uncleared_receipts: { label: 'تحصيلات غير محصلة بعد' },
  unit_price: { label: 'سعر الوحدة', kind: 'money' },
  uploaded_at: { label: 'وقت الرفع', kind: 'datetime' },
  uploaded_by: { label: 'رفعه' },
  user: { label: 'المستخدم' },
  vehicle_id: { label: 'رقم السيارة' },
  vehicle_stock: { label: 'مخزون السيارة' },
  visit_order: { label: 'ترتيب الزيارة', kind: 'number' },
  voucher_nos: { label: 'أرقام البونات' },
  waiting_on_warehouse: { label: 'بانتظار المخزن' },
  warehouse_id: { label: 'رقم المخزن' },
  warehouse_issued_at: { label: 'وقت صرف المخزن', kind: 'datetime' },
  warehouse_issued_by: { label: 'صرفه من المخزن' },
  warehouse_issued_quantity_cartons: { label: 'المصروف من المخزن (كرتونة)', kind: 'number' },
  warehouses: { label: 'المخازن' },
  with_salesman: { label: 'مع المندوب' },
  within_days: { label: 'خلال (يوم)', kind: 'number' },
  workshop: { label: 'الورشة' },
  year_of_manufacture: { label: 'سنة الصنع', kind: 'number' },
};

/** Backend enum values → Arabic. Unknown values show as sent. */
export const ENUM_LABELS: Record<string, string> = {
  ACTIVE: 'نشط',
  INACTIVE: 'غير نشط',
  OPEN: 'مفتوح',
  CLOSED: 'مغلق',
  ACKNOWLEDGED: 'تم الاطلاع',
  SUBMITTED: 'بانتظار التأكيد',
  NOT_HANDED_OVER: 'لم يُسلَّم',
  INFO: 'معلومة',
  WARNING: 'تحذير',
  CRITICAL: 'حرج',
  OUT: 'نفد',
  LOW: 'منخفض',
  DEAD: 'راكد',
  OK: 'سليم',
  ISSUED: 'صادر',
  REDEEMED: 'مصروف',
  CANCELLED: 'ملغى',
  NEW: 'جديدة',
  IN_STORE: 'في المخزن',
  WITH_CUSTOMER: 'عند العميل',
  DAMAGED: 'تالفة',
  SCRAP: 'خردة',
  MATCHED: 'مطابقة',
  STATE_DIFFERS: 'حالتها مختلفة',
  NOT_FOUND: 'غير موجودة',
  COUNTED: 'تم العدّ',
  REVIEWED: 'تمت المراجعة',
  DRAFT: 'مسودة',
  SENT: 'مُرسل',
  RECEIVED: 'مُستلم',
  CONFIRMED: 'مؤكد',
  ASSET: 'أصول',
  LIABILITY: 'خصوم',
  EQUITY: 'حقوق ملكية',
  REVENUE: 'إيرادات',
  EXPENSE: 'مصروفات',
  DEBIT: 'مدين',
  CREDIT: 'دائن',
  BOTH: 'الكل',
  BRANCH: 'الفرع',
  account: 'حساب',
  value: 'القيمة',
  trade_price: 'سعر الجملة',
  mine: 'فريقي فقط',

  /*
   * Task 6: values seen only in backend presenters (empty demo lists), plus the fault/alert
   * type constants. `CREDIT` and `OUT` are also used above for the accounting and stock-cover
   * contexts (`دائن`, `نفد`) — `payment_type` (SaleController/StoreSaleRequest: CASH|CREDIT) and
   * `direction` (GateMovement::DIRECTION_IN/OUT) reuse those same string values with a different
   * real-world meaning (credit sale, truck leaving). Fix round 2: resolved via `FIELD_ENUM_LABELS`
   * below, which overrides by field name before falling back to this global map.
   */
  CASH: 'نقدي',
  VISA: 'فيزا',
  BANK_TRANSFER: 'تحويل بنكي',
  CLEARED: 'تم التحصيل',
  PENDING: 'معلّق',
  EXPIRED: 'منتهي الصلاحية',
  CUSTOMER_REFUSAL: 'رفض العميل',
  OTHER: 'أخرى',
  RETURN: 'استرجاع',
  REPLACEMENT: 'استبدال',
  received_by_salesman: 'استلمه المندوب',
  inspected: 'تم الفحص',
  PARTIALLY_COMPLETED: 'مكتمل جزئيًا',
  COMPLETED: 'مكتمل',
  started: 'بدأت',
  sale_and_collection: 'بيع وتحصيل',
  sale_and_return: 'بيع ومرتجع',
  collection_and_return: 'تحصيل ومرتجع',
  sale: 'بيع',
  collection_only: 'تحصيل فقط',
  return_only: 'مرتجع فقط',
  no_sale: 'بدون بيع',
  IN: 'دخول',
  STILL_OUT: 'لم تعد بعد',
  ODOMETER_MISSING: 'العداد غير مسجل',
  ZERO_DISTANCE: 'بدون حركة',
  EXCESSIVE_DISTANCE: 'مسافة غير معتادة',
  MORNING: 'صباحية',
  EVENING: 'مسائية',
  SHORTAGE: 'عجز',
  EXCESS: 'زيادة',
  VEHICLE_COUNT: 'جرد العربية',
  CASH_RECONCILIATION: 'تسوية نقدية',
  WAREHOUSE_COUNT: 'جرد المخزن',
  PENDING_VERIFICATION: 'قيد المراجعة',
  VERIFIED: 'تمت المراجعة',
  REJECTED: 'مرفوض',
  SETTLED: 'تمت التسوية',
  DAILY: 'يومي',
  MONTHLY: 'شهري',
  QUARTERLY: 'ربع سنوي',
  ANNUAL: 'سنوي',
  LICENCE: 'الرخصة',
  INSURANCE: 'التأمين',
  SERVICE: 'الصيانة',
  REFRIGERATION_FAILED: 'عطل التبريد',
  COLD_ROOM_OUT_OF_RANGE: 'خروج غرفة التبريد عن النطاق',
  VEHICLE_STILL_OUT: 'العربية لم تعد بعد',
  TRIP_UNSETTLED: 'رحلة غير مُسواة',
  DELIVERY_SHORT: 'تسليم ناقص',
  DEBTOR_UNROUTED: 'مديون بدون خط',
  CREDIT_PAST_MONTH_END: 'آجل تجاوز نهاية الشهر',
  VAN_NOT_COUNTED: 'عربية لم تُجرد',
  draft: 'مسودة',
  confirmed: 'مؤكد',
  // Lowercase: the daily-session `status` value (`DailySession::STATUS_OPEN` = 'open'), distinct
  // from the uppercase `OPEN` used for stock alerts etc.
  open: 'مفتوحة',
  BALANCED: 'متوازن',
  unbilled: 'غير مفوتر',
  unpaid: 'غير مسدد',
  partially_paid: 'مسدد جزئيًا',
  overdue: 'متأخر',
  paid: 'مسدد',
  PAID: 'مسدد',
  UNBILLED: 'غير مفوتر',
  NOT_DUE: 'لم يستحق',
  DUE_TODAY: 'مستحق اليوم',
  OVERDUE: 'متأخر',
  issued: 'صادرة',

  /*
   * Fix round 1: `CreditFollowUpService::agingBucket()` aging-bucket values for
   * `credit_receivables.aging_bucket` (previously left unmapped as an uncertain guess).
   */
  '1_7_DAYS': 'متأخر 1–7 أيام',
  '8_15_DAYS': 'متأخر 8–15 يوم',
  '16_30_DAYS': 'متأخر 16–30 يوم',
  '31_60_DAYS': 'متأخر 31–60 يوم',
  '61_PLUS_DAYS': 'متأخر أكثر من 60 يوم',

  /*
   * Task 2 (customers): billing cycle values (`Customer::billing_cycle`). New keys, no collision
   * with anything above.
   */
  PER_DELIVERY: 'مع كل توصيلة',
  MONTHLY_ARREARS: 'شهري مؤجل',

  /*
   * Task 1 (expenses): funding source, payment method and review status values
   * (`ExpenseController`/`Expense` model). `CASH`, `BANK_TRANSFER` and `REJECTED` above already
   * cover the shared values; only the new ones are added here.
   */
  SOUTH: 'الجنوب',
  FRONERI: 'فرونيري',
  PETTY_CASH: 'عهدة نثرية',
  APPROVED: 'معتمد',

  /*
   * Task 1 (ledger): journal entry status values (`LedgerController`/`JournalEntry`).
   */
  POSTED: 'مُرحَّل',
  REVERSED: 'معكوس',
};

/**
 * Per-field overrides for enum values whose Arabic label depends on which field they belong to.
 * `ENUM_LABELS` is global by value, so `CREDIT`/`OUT` there mean "accounting credit" and "out of
 * stock" — wrong for a sale's payment type or a truck's gate direction. Checked against
 * SaleController/StoreSaleRequest (`payment_type`: CASH|CREDIT) and GateMovement (`direction`:
 * IN|OUT).
 */
export const FIELD_ENUM_LABELS: Record<string, Record<string, string>> = {
  payment_type: { CREDIT: 'آجل' },
  direction: { OUT: 'خروج', IN: 'دخول' },
  // Task 2 (customers): `payment_terms` (Customer::credit.payment_terms) reuses CASH/CREDIT with
  // the same "credit sale" meaning as `payment_type` above, not the global accounting one.
  payment_terms: { CREDIT: 'آجل' },
  fuel_voucher_status: { REDEEMED: 'مُسوّى' },
  // Vehicle statuses are lowercase; an unknown value (e.g. legacy uppercase data) falls back to the raw text.
  vehicle_status: { available: 'متاحة', in_workshop: 'في الورشة', out_of_service: 'خارج الخدمة' },
};

/** Resolves an enum value's label: field-specific override first, then the global map, then the raw value. */
export function enumLabel(field: string, value: string): string {
  return FIELD_ENUM_LABELS[field]?.[value] ?? ENUM_LABELS[value] ?? value;
}

export function fieldLabel(key: string): string {
  return FIELDS[key]?.label ?? key;
}

export function fieldKind(key: string): FieldKind {
  return FIELDS[key]?.kind ?? 'text';
}
